/**
 * modules-21-25.mjs
 * Detailed curriculum data for Modules 21 through 25 (55 topics total)
 */

export const MODULES_21_25 = {
  "M21": [
    {
      "id": "M21-01",
      "number": "01",
      "title": "Why API Documentation?",
      "khmerTitle": "សារៈសំខាន់នៃការបង្កើត API Documentation",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "An API is only as good as its documentation. Without clear specifications, frontend developers, mobile engineers, and third-party consumers waste countless hours guessing request payloads, header requirements, query parameters, and error shapes. Comprehensive documentation acts as a living contract that bridges the gap between frontend and backend teams.",
      "tip": "Treat API documentation as part of your code review checklist. An endpoint is never considered 'Done' until its documentation is updated and verified.",
      "objective": "Understand the critical role of standardized API documentation in enterprise engineering teams.",
      "expectedOutcome": "Adoption of documentation-first principles across API development workflows.",
      "codeSnippet": "// The Cost of Undocumented APIs:\n// - Miscommunicated field names (camelCase vs snake_case)\n// - Unexpected 400 validation failures without clear error bodies\n// - Unclear auth expectations (Bearer token vs cookie vs API key)\n// - Broken mobile/frontend integrations upon backend deploys\n//\n// The Solution: OpenAPI Specification (OAS 3.0) + Interactive Swagger UI"
    },
    {
      "id": "M21-02",
      "number": "02",
      "title": "OpenAPI",
      "khmerTitle": "ស្វែងយល់ពី OpenAPI Specification (OAS 3.0)",
      "type": "concept",
      "codeLanguage": "yaml",
      "summary": "The OpenAPI Specification (formerly Swagger) is the broadly adopted, vendor-neutral standard for describing RESTful APIs. Written in YAML or JSON, an OpenAPI document describes endpoints, HTTP methods, input parameters, request payloads, response bodies, status codes, and authentication mechanisms in a machine-readable format.",
      "tip": "Use OpenAPI 3.0+ rather than legacy Swagger 2.0. OAS 3.0 offers better component reusability, multiple server URLs, and flexible request body definitions.",
      "objective": "Learn the core anatomy and schema structure of OpenAPI 3.0 specifications.",
      "expectedOutcome": "Ability to read and structure machine-readable OpenAPI contracts.",
      "codeSnippet": "openapi: 3.0.3\ninfo:\n  title: E-Commerce REST API\n  version: 1.0.0\n  description: Enterprise backend API for products and orders\nservers:\n  - url: http://localhost:5000/api/v1\n    description: Development server\n  - url: https://api.myenterprise.com/v1\n    description: Production server\npaths:\n  /products:\n    get:\n      summary: Retrieve all products\n      responses:\n        '200':\n          description: A list of products"
    },
    {
      "id": "M21-03",
      "number": "03",
      "title": "Swagger",
      "khmerTitle": "ការស្វែងយល់ពីប្រព័ន្ធអេកូឡូស៊ី Swagger",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Swagger is a suite of open-source tools built around the OpenAPI specification. It includes Swagger Editor for designing API contracts, Swagger Codegen for generating client SDKs in multiple programming languages, and Swagger UI for rendering interactive, browser-based documentation from OpenAPI documents.",
      "tip": "In Node.js backends, pair `swagger-jsdoc` (which parses JSDoc comments into OpenAPI specs) with `swagger-ui-express` for automated interactive docs.",
      "objective": "Differentiate between OpenAPI (the standard specification) and Swagger (the toolset).",
      "expectedOutcome": "Clear understanding of how Swagger tools integrate with Node.js and Express.",
      "codeSnippet": "// Key Swagger Tools:\n// 1. OpenAPI Specification -> The standard grammar and format\n// 2. swagger-jsdoc          -> Reads JSDoc annotations from Express route files\n// 3. swagger-ui-express     -> Express middleware serving interactive HTML docs\n// 4. Swagger Codegen        -> Generates TypeScript/Swift/Kotlin client SDKs from OAS"
    },
    {
      "id": "M21-04",
      "number": "04",
      "title": "Swagger UI",
      "khmerTitle": "ការដំឡើង Swagger UI ក្នុង Express ជាមួយ swagger-ui-express",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Swagger UI generates an interactive, human-readable documentation website directly from your OpenAPI specification. Developers can explore endpoints, inspect schemas, and test live HTTP requests directly within the browser using the built-in 'Try it out' console.",
      "tip": "Mount your Swagger documentation at `/api/docs` and restrict access in production environments using basic authentication if the API is internal.",
      "objective": "Mount Swagger UI interactive documentation in an Express application.",
      "expectedOutcome": "Working interactive API documentation hosted live at /api/docs.",
      "codeSnippet": "import express from \"express\";\nimport swaggerUi from \"swagger-ui-express\";\nimport swaggerJsdoc from \"swagger-jsdoc\";\n\nconst app = express();\n\nconst swaggerOptions = {\n  definition: {\n    openapi: \"3.0.0\",\n    info: {\n      title: \"Node.js Express API Documentation\",\n      version: \"1.0.0\",\n      description: \"Interactive documentation with live request testing\",\n    },\n  },\n  apis: [\"./src/routes/*.js\"], // Scan route files for JSDoc annotations\n};\n\nconst swaggerSpec = swaggerJsdoc(swaggerOptions);\n\n// Serve Swagger UI at /api/docs\napp.use(\"/api/docs\", swaggerUi.serve, swaggerUi.setup(swaggerSpec));"
    },
    {
      "id": "M21-05",
      "number": "05",
      "title": "API Schemas",
      "khmerTitle": "ការកំណត់ Schemas និង DTOs ក្នុង Swagger Components",
      "type": "lab",
      "codeLanguage": "yaml",
      "summary": "OpenAPI schemas define the shape, types, and constraints of data models used across endpoints. Centralizing data models inside `components.schemas` promotes reuse and avoids duplicating object definitions across multiple route annotations.",
      "tip": "Reference reusable schemas using the `$ref` pointer (e.g. `'$ref': '#/components/schemas/User'`) to keep route docs DRY and maintainable.",
      "objective": "Define reusable data schemas with typed properties and validation rules in OpenAPI.",
      "expectedOutcome": "Consistent, reusable component schemas reflecting database and DTO models.",
      "codeSnippet": "/**\n * @openapi\n * components:\n *   schemas:\n *     Product:\n *       type: object\n *       required:\n *         - title\n *         - price\n *       properties:\n *         id:\n *           type: string\n *           example: \"64f1a2b3c4d5e6f7a8b9c0d1\"\n *         title:\n *           type: string\n *           example: \"Wireless Mechanical Keyboard\"\n *         price:\n *           type: number\n *           example: 89.99\n *         category:\n *           type: string\n *           enum: [Electronics, Furniture, Clothing]\n *           example: \"Electronics\"\n */"
    },
    {
      "id": "M21-06",
      "number": "06",
      "title": "Request Documentation",
      "khmerTitle": "ការសរសេរឯកសារ Params, Query, និង Request Body",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Documenting API requests requires detailing URL path parameters (e.g. `:id`), query parameters (e.g. `?page=1&limit=10`), and JSON request bodies with required attributes, data types, and realistic mock examples.",
      "tip": "Always provide realistic `example` values in your annotations — Swagger UI uses these to prepopulate the 'Try it out' request body automatically.",
      "objective": "Annotate route parameters, query filters, and JSON request bodies using JSDoc.",
      "expectedOutcome": "Crystal-clear documentation instructing consumers on how to formulate requests.",
      "codeSnippet": "/**\n * @openapi\n * /api/v1/products/{id}:\n *   put:\n *     summary: Update an existing product\n *     tags: [Products]\n *     parameters:\n *       - in: path\n *         name: id\n *         required: true\n *         schema:\n *           type: string\n *         description: MongoDB ObjectId of the product\n *     requestBody:\n *       required: true\n *       content:\n *         application/json:\n *           schema:\n *             $ref: '#/components/schemas/UpdateProductDTO'\n */"
    },
    {
      "id": "M21-07",
      "number": "07",
      "title": "Response Documentation",
      "khmerTitle": "ការសរសេរឯកសារ HTTP Responses (200, 201, 400, 404, 500)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Endpoints must document every possible HTTP status response, including both successful outcomes (200 OK, 201 Created) and failure scenarios. Response bodies should link to component schemas or define clear JSON response structures.",
      "tip": "Document common error codes (400, 401, 403, 404) for every endpoint so frontend engineers can handle all branch conditions.",
      "objective": "Document standard success and failure HTTP responses with payload schemas.",
      "expectedOutcome": "Predictable API contracts defining both happy path and failure scenarios.",
      "codeSnippet": "/**\n * @openapi\n * /api/v1/products:\n *   post:\n *     summary: Create a new product\n *     tags: [Products]\n *     responses:\n *       201:\n *         description: Product created successfully\n *         content:\n *           application/json:\n *             schema:\n *               type: object\n *               properties:\n *                 status:\n *                   type: string\n *                   example: success\n *                 data:\n *                   $ref: '#/components/schemas/Product'\n *       400:\n *         description: Bad Request (Validation failure)\n */"
    },
    {
      "id": "M21-08",
      "number": "08",
      "title": "Authentication Documentation",
      "khmerTitle": "ការកត់ត្រា Auth Security Schemes (Bearer JWT & Cookies)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Documenting authentication informs consumers which security schemes protect an endpoint. OpenAPI supports Bearer JWT tokens, API keys, and HTTP cookies. Setting up a `bearerAuth` security scheme in Swagger UI enables the green 'Authorize' padlock button, allowing developers to paste a JWT token and test protected endpoints live.",
      "tip": "Define `bearerAuth` in `components.securitySchemes` and add `security: - bearerAuth: []` to all protected routes in Swagger annotations.",
      "objective": "Configure Bearer JWT security schemes in OpenAPI and enable interactive authorization.",
      "expectedOutcome": "Fully functional 'Authorize' button in Swagger UI allowing authenticated API testing.",
      "codeSnippet": "/**\n * @openapi\n * components:\n *   securitySchemes:\n *     bearerAuth:\n *       type: http\n *       scheme: bearer\n *       bearerFormat: JWT\n *       description: Enter your JWT Bearer token to authorize requests\n *\n * /api/v1/users/me:\n *   get:\n *     summary: Get current authenticated user profile\n *     tags: [Users]\n *     security:\n *       - bearerAuth: []\n *     responses:\n *       200:\n *         description: User profile retrieved successfully\n *       401:\n *         description: Unauthorized - Token missing or expired\n */"
    },
    {
      "id": "M21-09",
      "number": "09",
      "title": "Error Documentation",
      "khmerTitle": "ការរៀបចំទម្រង់ Error Response ជាលក្ខណៈស្តង់ដារក្នុង Swagger",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Standardized error responses streamline API troubleshooting. Documenting a centralized `ErrorResponse` component schema with `status`, `message`, and optional `errors` array provides a consistent blueprint that all 4xx and 5xx responses conform to.",
      "tip": "Ensure your global Express error middleware emits the exact same JSON keys documented in your OpenAPI `ErrorResponse` schema.",
      "objective": "Define and reference unified error response schemas across all endpoints.",
      "expectedOutcome": "Consistent error documentation matching real runtime Express errors.",
      "codeSnippet": "/**\n * @openapi\n * components:\n *   schemas:\n *     ErrorResponse:\n *       type: object\n *       properties:\n *         status:\n *           type: string\n *           example: \"fail\"\n *         statusCode:\n *           type: integer\n *           example: 404\n *         message:\n *           type: string\n *           example: \"Resource not found\"\n *         errors:\n *           type: array\n *           items:\n *             type: string\n *           example: [\"Email already registered\"]\n */"
    },
    {
      "id": "M21-10",
      "number": "10",
      "title": "Complete API Documentation",
      "khmerTitle": "ស្ថាបត្យកម្មប្រព័ន្ធ Documentation ពេញលេញកម្រិត Production",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "A production-grade API documentation architecture automates spec generation from route files, exposes interactive Swagger UI for development, and generates static HTML or Markdown for public developer portals. Versioning your documentation (`/api/v1/docs`, `/api/v2/docs`) guarantees backward compatibility for enterprise consumers.",
      "tip": "Export your generated OpenAPI specification as a raw JSON file (`/api/docs.json`) so external tools like Postman and SDK generators can import it automatically.",
      "objective": "Architect a comprehensive, versioned API documentation system in Node.js.",
      "expectedOutcome": "Self-updating, interactive, and exportable API documentation for production backends.",
      "codeSnippet": "// Expose raw spec for Postman / SDK generators\napp.get(\"/api/docs.json\", (req, res) => {\n  res.setHeader(\"Content-Type\", \"application/json\");\n  res.send(swaggerSpec);\n});\n\n// Mount interactive documentation UI\napp.use(\"/api/docs\", swaggerUi.serve, swaggerUi.setup(swaggerSpec, {\n  explorer: true,\n  customCss: \".swagger-ui .topbar { display: none }\", // Clean look\n  customSiteTitle: \"Enterprise REST API Documentation\",\n}));"
    }
  ],
  "M22": [
    {
      "id": "M22-01",
      "number": "01",
      "title": "Why Test APIs?",
      "khmerTitle": "សារៈសំខាន់នៃការធ្វើតេស្ត API (Software Quality & Confidence)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Automated API testing ensures your backend behaves correctly under all conditions, catches regressions before deployments, and provides the confidence to refactor code without fear. Relying solely on manual Postman clicking is slow, error-prone, and cannot scale as endpoints multiply.",
      "tip": "Automated tests act as executable specifications — they prove how your code actually runs, unlike comments that easily become outdated.",
      "objective": "Understand the software quality pyramid and the return on investment (ROI) of automated tests.",
      "expectedOutcome": "Appreciation of testing as a foundational engineering discipline.",
      "codeSnippet": "// The Testing Pyramid:\n//\n//        ///       /       E2E Tests (Supertest across complete flows)\n//      /----//     /         Integration Tests (Routes + Middleware + DB queries)\n//    /--------//   /           Unit Tests (Services, utility functions, pure logic)\n//  --------------"
    },
    {
      "id": "M22-02",
      "number": "02",
      "title": "Unit Testing",
      "khmerTitle": "គោលការណ៍គ្រឹះនៃ Unit Testing",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Unit testing verifies individual units of source code — typically isolated functions or service classes — in complete isolation from external dependencies like databases, file systems, or network sockets. By mocking out external systems, unit tests execute in milliseconds.",
      "tip": "Keep unit tests deterministic: given the same input, a unit test must always produce the exact same assertion output regardless of environment.",
      "objective": "Learn the principles of isolated unit testing and the Arrange-Act-Assert (AAA) pattern.",
      "expectedOutcome": "Ability to identify testable units and write fast, deterministic unit tests.",
      "codeSnippet": "// Arrange - Act - Assert (AAA) Pattern:\nimport { describe, it, expect } from \"vitest\";\nimport { calculateDiscount } from \"../services/pricing.service.js\";\n\ndescribe(\"calculateDiscount\", () => {\n  it(\"should apply 20% discount for orders exceeding $100\", () => {\n    // 1. Arrange\n    const originalPrice = 120;\n    const discountRate = 0.20;\n\n    // 2. Act\n    const finalPrice = calculateDiscount(originalPrice, discountRate);\n\n    // 3. Assert\n    expect(finalPrice).toBe(96);\n  });\n});"
    },
    {
      "id": "M22-03",
      "number": "03",
      "title": "Integration Testing",
      "khmerTitle": "គោលការណ៍ Integration Testing លើ API Endpoints",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Integration testing verifies that multiple system components work harmoniously together — for example, confirming that an Express route handler correctly passes through middleware, executes database queries via Mongoose, and formats JSON responses.",
      "tip": "Integration tests give the highest confidence per line of test code because they test the real HTTP request-response pipeline.",
      "objective": "Understand how integration tests validate cross-layer interactions in web backends.",
      "expectedOutcome": "Solid grasp of integration testing strategies for Express and MongoDB.",
      "codeSnippet": "// Integration Test Flow:\n// HTTP Request -> Routing -> Auth Middleware -> Validation -> Controller -> MongoDB -> JSON Response\n//\n// Unlike unit tests, integration tests run through the entire pipeline,\n// confirming that middleware and database queries work together as intended."
    },
    {
      "id": "M22-04",
      "number": "04",
      "title": "API Testing",
      "khmerTitle": "ការធ្វើតេស្ត HTTP API តាមបែបស្វ័យប្រវត្តិ",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "API testing treats the backend as a black box, dispatching synthetic HTTP requests and asserting on status codes, response headers, JSON payload structures, and response latency. It verifies contract compliance without coupling tests to internal implementation details.",
      "tip": "Always test both success status codes (200, 201) and error responses (400, 401, 403, 404, 409) for complete endpoint coverage.",
      "objective": "Formulate automated HTTP assertion suites evaluating status codes, headers, and payloads.",
      "expectedOutcome": "Robust test specifications validating public API behavior.",
      "codeSnippet": "// API Testing Expectations:\n// 1. Correct HTTP Status Code (200, 201, 400, 401, 404)\n// 2. Correct Content-Type Header (application/json; charset=utf-8)\n// 3. JSON Payload Contract (contains expected fields and data types)\n// 4. Database Side Effects (record created, updated, or deleted in DB)"
    },
    {
      "id": "M22-05",
      "number": "05",
      "title": "Vitest",
      "khmerTitle": "ការដំឡើង និងដំណើរការ Vitest ក្នុង Node.js",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Vitest is a blazing-fast, modern next-generation test runner powered by Vite. It features out-of-the-box native TypeScript and ES Modules support, instantaneous hot module reloading (watch mode), Jest-compatible assertion syntax, and multi-threaded test execution.",
      "tip": "Add `\"test\": \"vitest run\"` and `\"test:watch\": \"vitest\"` to your `package.json` scripts for lightning-fast test execution.",
      "objective": "Install, configure, and execute automated test suites using Vitest.",
      "expectedOutcome": "Configured Vitest environment running tests with sub-second execution speeds.",
      "codeSnippet": "// vitest.config.js\nimport { defineConfig } from \"vitest/config\";\n\nexport default defineConfig({\n  test: {\n    globals: true,\n    environment: \"node\",\n    testTimeout: 10000,\n    coverage: {\n      provider: \"v8\",\n      reporter: [\"text\", \"json\", \"html\"],\n    },\n  },\n});"
    },
    {
      "id": "M22-06",
      "number": "06",
      "title": "Jest",
      "khmerTitle": "ការប្រៀបធៀប Jest និង Vitest ក្នុង Node.js Backends",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Jest has historically been the standard testing framework in Node.js. While highly feature-rich, configuring Jest with modern ECMAScript Modules (ESM) often requires complex Babel or ts-jest configurations. Vitest provides identical APIs (`describe`, `it`, `expect`, `vi.fn()`) while handling ESM and TypeScript natively.",
      "tip": "Vitest is 99% API-compatible with Jest. If migrating from Jest, simply replace `jest.fn()` with `vi.fn()`.",
      "objective": "Understand differences between Jest and Vitest and learn to write compatible test suites.",
      "expectedOutcome": "Fluency with modern JavaScript testing assertions and mock APIs.",
      "codeSnippet": "// Vitest / Jest Compatible Test:\nimport { describe, it, expect, vi } from \"vitest\";\n\ndescribe(\"User Notification\", () => {\n  it(\"should trigger callback when user registers\", () => {\n    const mockNotifier = vi.fn(); // Mock function\n\n    mockNotifier(\"user@example.com\");\n\n    expect(mockNotifier).toHaveBeenCalledTimes(1);\n    expect(mockNotifier).toHaveBeenCalledWith(\"user@example.com\");\n  });\n});"
    },
    {
      "id": "M22-07",
      "number": "07",
      "title": "Supertest",
      "khmerTitle": "ការធ្វើតេស្ត HTTP Requests ជាមួយ Supertest",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Supertest provides high-level HTTP abstractions for testing Node.js Express applications without binding to a physical network port. It boots the Express app in-memory, transmits simulated HTTP requests, and asserts against status codes and headers in a fluent chainable syntax.",
      "tip": "Pass your `app` instance directly to `request(app)` without calling `app.listen()` — this avoids port collision errors when running tests concurrently.",
      "objective": "Use Supertest to dispatch HTTP verbs (GET, POST, PUT, DELETE) and assert responses.",
      "expectedOutcome": "Fast in-memory HTTP endpoint testing without opening network sockets.",
      "codeSnippet": "import request from \"supertest\";\nimport { describe, it, expect } from \"vitest\";\nimport app from \"../src/app.js\";\n\ndescribe(\"GET /api/v1/health\", () => {\n  it(\"should return 200 OK with system status\", async () => {\n    const res = await request(app)\n      .get(\"/api/v1/health\")\n      .expect(\"Content-Type\", /json/)\n      .expect(200);\n\n    expect(res.body.status).toBe(\"success\");\n    expect(res.body.data).toHaveProperty(\"uptime\");\n  });\n});"
    },
    {
      "id": "M22-08",
      "number": "08",
      "title": "Testing Controllers",
      "khmerTitle": "ការធ្វើតេស្ត Controllers តាមរយៈ Supertest",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Testing controllers verifies that request parameters, body payloads, and query filters are processed correctly and appropriate status codes and JSON envelopes are returned. Mocking underlying service methods allows testing controller edge cases like validation errors and custom exceptions.",
      "tip": "Export your Express `app` from `app.js` without calling `listen()`, and create a separate `server.js` for startup. This allows tests to import `app` cleanly.",
      "objective": "Write targeted tests validating controller responses, status codes, and JSON bodies.",
      "expectedOutcome": "Verified controllers handling both valid inputs and error conditions.",
      "codeSnippet": "describe(\"POST /api/v1/products\", () => {\n  it(\"should return 400 when title is missing\", async () => {\n    const invalidProduct = { price: 29.99 };\n\n    const res = await request(app)\n      .post(\"/api/v1/products\")\n      .send(invalidProduct)\n      .expect(400);\n\n    expect(res.body.status).toBe(\"fail\");\n    expect(res.body.message).toMatch(/title is required/i);\n  });\n});"
    },
    {
      "id": "M22-09",
      "number": "09",
      "title": "Testing Services",
      "khmerTitle": "ការធ្វើតេស្ត Business Logic ក្នុង Service Layer",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Services encapsulate core business logic independent of Express request and response objects. Because service functions accept plain JavaScript parameters and return data, testing them requires no HTTP overhead, resulting in blistering test execution speeds.",
      "tip": "Keep business logic in services rather than controllers — this makes testing business logic 10x faster because you don't need HTTP request simulation.",
      "objective": "Write isolated unit tests for business logic methods inside the service layer.",
      "expectedOutcome": "High test coverage over core business algorithms and data transformations.",
      "codeSnippet": "import { describe, it, expect } from \"vitest\";\nimport { OrderService } from \"../services/order.service.js\";\n\ndescribe(\"OrderService.calculateTotal\", () => {\n  it(\"should compute subtotal, tax, and shipping correctly\", () => {\n    const items = [\n      { price: 50, quantity: 2 },\n      { price: 100, quantity: 1 },\n    ];\n    const taxRate = 0.10; // 10%\n\n    const total = OrderService.calculateTotal(items, taxRate);\n\n    // Subtotal: 200, Tax: 20 -> Total: 220\n    expect(total).toBe(220);\n  });\n});"
    },
    {
      "id": "M22-10",
      "number": "10",
      "title": "Testing API Endpoints",
      "khmerTitle": "ការធ្វើតេស្ត CRUD Endpoints ពេញលេញ (Full CRUD Test Suite)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "A complete CRUD test suite covers the entire lifecycle of a resource: creating a new record (POST 201), fetching the collection (GET 200), retrieving by ID (GET 200), modifying properties (PATCH 200), and deleting the record (DELETE 204 or 200).",
      "tip": "Save the created resource's `_id` in a variable during the POST test and reuse it across GET by ID, PATCH, and DELETE tests.",
      "objective": "Construct an end-to-end CRUD test suite exercising all REST operations.",
      "expectedOutcome": "Comprehensive test suite guaranteeing functional integrity of CRUD endpoints.",
      "codeSnippet": "describe(\"Products CRUD API\", () => {\n  let createdProductId = \"\";\n\n  it(\"POST /api/products -> 201 Created\", async () => {\n    const res = await request(app)\n      .post(\"/api/products\")\n      .send({ title: \"Gaming Mouse\", price: 49.99 })\n      .expect(201);\n\n    createdProductId = res.body.data.product._id;\n    expect(createdProductId).toBeDefined();\n  });\n\n  it(\"GET /api/products/:id -> 200 OK\", async () => {\n    const res = await request(app)\n      .get(`/api/products/${createdProductId}`)\n      .expect(200);\n\n    expect(res.body.data.product.title).toBe(\"Gaming Mouse\");\n  });\n\n  it(\"DELETE /api/products/:id -> 200 OK\", async () => {\n    await request(app)\n      .delete(`/api/products/${createdProductId}`)\n      .expect(200);\n  });\n});"
    },
    {
      "id": "M22-11",
      "number": "11",
      "title": "Testing Authentication",
      "khmerTitle": "ការធ្វើតេស្ត Protected Endpoints ជាមួយ Authorization Headers",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Testing protected routes requires simulating authenticated sessions. Tests can either execute a live login request before protected calls to obtain a real token, or generate a signed test JWT directly using test secret keys and attach it via `.set('Authorization', 'Bearer ' + token)`.",
      "tip": "Create a test helper `getAuthToken(user)` to sign test JWTs quickly without making repetitive HTTP login calls in every test.",
      "objective": "Test route access control, valid token acceptance, and rejection of unauthorized calls.",
      "expectedOutcome": "Automated verification of authentication and role guards.",
      "codeSnippet": "import { generateAccessToken } from \"../utils/jwt.js\";\n\ndescribe(\"Protected Routes Auth Testing\", () => {\n  it(\"should reject requests without a Bearer token with 401\", async () => {\n    const res = await request(app)\n      .get(\"/api/v1/users/me\")\n      .expect(401);\n\n    expect(res.body.message).toMatch(/not logged in/i);\n  });\n\n  it(\"should permit access when a valid JWT token is provided\", async () => {\n    const testToken = generateAccessToken(\"test_user_id_123\", \"user\");\n\n    const res = await request(app)\n      .get(\"/api/v1/users/me\")\n      .set(\"Authorization\", `Bearer ${testToken}`)\n      .expect(200);\n\n    expect(res.body.data.user).toBeDefined();\n  });\n});"
    },
    {
      "id": "M22-12",
      "number": "12",
      "title": "Mocking",
      "khmerTitle": "ការ Mock 3rd-party Services (Stripe, Email, SMS) ជាមួយ vi.fn()",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Mocking replaces real external dependencies (payment gateways like Stripe, email providers like SendGrid, or SMS APIs) with dummy simulations during tests. This prevents tests from incurring financial costs, sending real emails to users, or failing when third-party servers experience outages.",
      "tip": "Never call real payment gateways or SMTP servers during automated tests! Always mock external network calls.",
      "objective": "Mock third-party services using Vitest vi.spyOn and vi.mock.",
      "expectedOutcome": "Reliable, isolated test suites that execute without external network dependencies.",
      "codeSnippet": "import { describe, it, expect, vi } from \"vitest\";\nimport * as mailService from \"../services/mail.service.js\";\n\ndescribe(\"Registration with Email Mock\", () => {\n  it(\"should register user and dispatch welcome email\", async () => {\n    // Spy on mailService.sendEmail and mock its implementation\n    const emailSpy = vi.spyOn(mailService, \"sendEmail\").mockResolvedValue({ success: true });\n\n    const res = await request(app)\n      .post(\"/api/v1/auth/register\")\n      .send({ name: \"Alice\", email: \"alice@test.com\", password: \"Password123!\" })\n      .expect(201);\n\n    // Verify email was sent with right params without actually contacting SMTP server\n    expect(emailSpy).toHaveBeenCalledTimes(1);\n    expect(emailSpy).toHaveBeenCalledWith(expect.objectContaining({ to: \"alice@test.com\" }));\n\n    emailSpy.mockRestore(); // Restore original function\n  });\n});"
    },
    {
      "id": "M22-13",
      "number": "13",
      "title": "Test Database",
      "khmerTitle": "ការរៀបចំ Test Database ជាមួយ mongodb-memory-server",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Automated tests must never execute against production or shared development databases. Using `mongodb-memory-server` spins up a lightweight, ephemeral MongoDB instance running entirely in system RAM. Each test suite runs against isolated in-memory collections that are wiped clean after tests finish.",
      "tip": "Use `mongodb-memory-server` in test hooks (`beforeAll`, `afterEach`, `afterAll`) to guarantee zero cross-test data pollution.",
      "objective": "Configure an isolated in-memory MongoDB environment for integration testing.",
      "expectedOutcome": "Fast, isolated database testing with automatic cleanup after test completion.",
      "codeSnippet": "import { MongoMemoryServer } from \"mongodb-memory-server\";\nimport mongoose from \"mongoose\";\nimport { beforeAll, afterAll, afterEach } from \"vitest\";\n\nlet mongoServer;\n\nbeforeAll(async () => {\n  mongoServer = await MongoMemoryServer.create();\n  const uri = mongoServer.getUri();\n  await mongoose.connect(uri);\n});\n\nafterEach(async () => {\n  // Clear all collections between individual tests\n  const collections = mongoose.connection.collections;\n  for (const key in collections) {\n    await collections[key].deleteMany({});\n  }\n});\n\nafterAll(async () => {\n  await mongoose.disconnect();\n  await mongoServer.stop();\n});"
    }
  ],
  "M23": [
    {
      "id": "M23-01",
      "number": "01",
      "title": "Postman",
      "khmerTitle": "ការស្វែងយល់ពីឧបករណ៍ Postman សម្រាប់ API Development",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Postman is the industry-leading API development and testing platform. It provides a visual graphical interface to compose HTTP requests, inspect headers and JSON responses, organize endpoints into hierarchical collections, manage environment variables, and automate assertions using JavaScript.",
      "tip": "Use the Postman desktop client rather than the web version to avoid CORS limitations when testing local `localhost` servers.",
      "objective": "Understand Postman features for interactive testing, debugging, and team collaboration.",
      "expectedOutcome": "Proficiency navigating Postman workspaces, requests, and consoles.",
      "codeSnippet": "// Postman Core Capabilities:\n// 1. Request Builder: Formulate GET, POST, PUT, DELETE with headers & bodies\n// 2. Collections: Group related API endpoints into shareable folders\n// 3. Environments: Toggle seamlessly between Local, Staging, and Production\n// 4. Scripts: Automate pre-request token generation and test assertions\n// 5. Runner & Newman: Execute test suites in batch from the terminal/CI"
    },
    {
      "id": "M23-02",
      "number": "02",
      "title": "Creating Collections",
      "khmerTitle": "ការបង្កើត និងរៀបចំ API Collections ក្នុង Postman",
      "type": "lab",
      "codeLanguage": "json",
      "summary": "A Postman Collection is a group of saved API requests organized into logical folders (e.g. Auth, Users, Products, Orders). Collections can be exported as JSON files and checked into Git repositories alongside backend source code, allowing entire engineering teams to share verified API requests.",
      "tip": "Store your exported Postman collection JSON inside a `/docs/postman` folder in your project repo so all developers stay in sync.",
      "objective": "Structure and organize enterprise REST API requests into modular Postman collections.",
      "expectedOutcome": "Structured, shareable Postman collection mirroring your backend routing hierarchy.",
      "codeSnippet": "// Postman Collection Structure:\n// 📁 My-Enterprise-API\n//   ├── 📁 01-Authentication\n//   │   ├── POST Register\n//   │   ├── POST Login\n//   │   └── POST Refresh Token\n//   ├── 📁 02-Products\n//   │   ├── GET All Products\n//   │   ├── POST Create Product\n//   │   └── DELETE Product\n//   └── 📁 03-Orders\n//       ├── POST Checkout\n//       └── GET My Orders"
    },
    {
      "id": "M23-03",
      "number": "03",
      "title": "Environment Variables",
      "khmerTitle": "ការប្រើប្រាស់ Environment Variables ក្នុង Postman ({{base_url}})",
      "type": "lab",
      "codeLanguage": "json",
      "summary": "Postman environments allow you to define key-value variables that adapt dynamically across different hosting stages. By parameterizing URLs as `{{base_url}}/products` and tokens as `{{auth_token}}`, switching between Local (`http://localhost:5000`), Staging, and Production requires a single dropdown click.",
      "tip": "Always reference `{{base_url}}` instead of hardcoding `http://localhost:5000` in individual requests.",
      "objective": "Configure dynamic environment variables to switch between development and staging environments.",
      "expectedOutcome": "Flexible Postman requests parameterizing domains, ports, and tokens.",
      "codeSnippet": "// In Postman URL Bar:\n// {{base_url}}/api/v1/products/{{product_id}}\n//\n// Environment: \"Local Development\"\n// base_url   -> http://localhost:5000\n// auth_token -> eyJhbGciOiJIUzI1Ni...\n//\n// Environment: \"Production\"\n// base_url   -> https://api.myenterprise.com\n// auth_token -> eyJhbGciOiJIUzI1Ni..."
    },
    {
      "id": "M23-04",
      "number": "04",
      "title": "Testing API Requests",
      "khmerTitle": "ការផ្ញើ និងត្រួតពិនិត្យ HTTP Requests ក្នុង Postman",
      "type": "lab",
      "codeLanguage": "json",
      "summary": "Inspecting API responses requires examining status codes, response times (ms), payload sizes (KB), and HTTP response headers. Postman's pretty-printed JSON viewer highlights syntax, formats responses, and renders cookies sent by the server.",
      "tip": "Use the Postman Console (`Ctrl+Alt+C` or `Cmd+Option+C`) to view raw network traffic, exact headers sent, and `console.log()` outputs.",
      "objective": "Analyze HTTP response metrics, headers, and payload structures in Postman.",
      "expectedOutcome": "Detailed diagnostic capability when debugging live backend endpoints.",
      "codeSnippet": "// Response Inspection Checklist:\n// Status:       200 OK\n// Time:         48 ms (< 200 ms is optimal)\n// Size:         1.24 KB\n// Headers:      Content-Type: application/json; charset=utf-8\n//               X-RateLimit-Remaining: 99\n// Body:         { \"status\": \"success\", \"results\": 10, \"data\": [...] }"
    },
    {
      "id": "M23-05",
      "number": "05",
      "title": "Authentication in Postman",
      "khmerTitle": "ការកំណត់ Authentication ស្វ័យប្រវត្តិតាមរយៈ Collection Variables",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Configuring authentication at the Collection root level allows all nested requests to inherit authentication credentials automatically (`Inherit auth from parent`). Upon successful login, a Postman script automatically captures the returned JWT token and writes it to `{{auth_token}}`.",
      "tip": "Set the Authorization type to `Bearer Token` with value `{{auth_token}}` at the collection folder level so you never have to configure tokens on individual routes.",
      "objective": "Automate token injection across all collection requests using Postman scripts.",
      "expectedOutcome": "Seamless authenticated testing across all protected endpoints without manual copy-pasting.",
      "codeSnippet": "// Postman Tests Script on POST /login:\n// Save JWT token automatically to environment variables!\nconst response = pm.response.json();\n\nif (response.token) {\n  pm.environment.set(\"auth_token\", response.token);\n  console.log(\"Updated auth_token variable successfully!\");\n}\n\n// In Collection Root -> Authorization Tab:\n// Type: Bearer Token\n// Token: {{auth_token}}"
    },
    {
      "id": "M23-06",
      "number": "06",
      "title": "Testing CRUD APIs",
      "khmerTitle": "លំហូរនៃការធ្វើតេស្ត CRUD APIs ជាខ្សែសង្វាក់ក្នុង Postman",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Testing CRUD APIs effectively involves chaining requests: POST creates an entity and writes its ID to `{{entity_id}}`, subsequent GET/PUT requests reference `{{entity_id}}`, and DELETE removes it. This verifies the complete lifecycle in a continuous workflow.",
      "tip": "Use Postman Collection Runner to execute your entire CRUD workflow from start to finish with a single click.",
      "objective": "Chain CRUD operations together using dynamic Postman variables.",
      "expectedOutcome": "Automated end-to-end CRUD verification sequence.",
      "codeSnippet": "// In POST /products Tests tab:\nconst jsonData = pm.response.json();\npm.test(\"Product created successfully\", () => {\n  pm.response.to.have.status(201);\n  // Store created ID for subsequent GET/PATCH/DELETE calls:\n  pm.environment.set(\"product_id\", jsonData.data.product._id);\n});\n\n// In next request:\n// GET {{base_url}}/api/v1/products/{{product_id}}"
    },
    {
      "id": "M23-07",
      "number": "07",
      "title": "Testing Error Responses",
      "khmerTitle": "ការធ្វើតេស្តកំហុសផ្សេងៗ (Negative Testing ក្នុង Postman)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Negative testing deliberately sends malformed bodies, missing headers, or invalid IDs to confirm that the API returns appropriate 4xx status codes and descriptive error messages rather than unhandled 500 internal server crashes.",
      "tip": "Always create dedicated negative test requests in your collection (e.g. 'Create Product - Missing Title -> 400').",
      "objective": "Validate edge cases and error handling paths using Postman assertions.",
      "expectedOutcome": "Resilient APIs validated against invalid and adversarial payloads.",
      "codeSnippet": "// Postman Tests Tab for 400 Bad Request:\npm.test(\"Status code is 400 Bad Request\", () => {\n  pm.response.to.have.status(400);\n});\n\npm.test(\"Error response contains fail status\", () => {\n  const jsonData = pm.response.json();\n  pm.expect(jsonData.status).to.eql(\"fail\");\n  pm.expect(jsonData.message).to.be.a(\"string\");\n});"
    },
    {
      "id": "M23-08",
      "number": "08",
      "title": "Postman Scripts",
      "khmerTitle": "ការសរសេរ Pre-request Scripts និង Test Scripts (Chai Assertions)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Postman scripts execute JavaScript before requests are dispatched (Pre-request scripts) and after responses arrive (Test scripts). Using the built-in Chai assertion library, tests validate response latency, status codes, and data types automatically.",
      "tip": "Pre-request scripts can compute timestamps, MD5 hashes, or dynamic random data using `pm.variables.replaceIn('{{$randomEmail}}')`.",
      "objective": "Write advanced JavaScript pre-request workflows and Chai test assertions.",
      "expectedOutcome": "Automated assertion suites validating contract rules on every request execution.",
      "codeSnippet": "// Postman Test Script using Chai BDD syntax:\npm.test(\"Response time is under 200ms\", () => {\n  pm.expect(pm.response.responseTime).to.be.below(200);\n});\n\npm.test(\"Response has required schema properties\", () => {\n  const json = pm.response.json();\n  pm.expect(json).to.have.property(\"status\", \"success\");\n  pm.expect(json.data).to.be.an(\"object\");\n  pm.expect(json.data.user.email).to.match(/@/);\n});"
    },
    {
      "id": "M23-09",
      "number": "09",
      "title": "Swagger UI",
      "khmerTitle": "ការប្រៀបធៀប និងការធ្វើសមាហរណកម្ម Swagger UI ជាមួយ Postman",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Swagger UI and Postman complement each other. Swagger UI serves as the official, self-documenting contract embedded in the backend codebase, while Postman serves as an exploratory workbench and CI test runner. Postman can directly import OpenAPI JSON specs to instantly generate ready-to-test collections.",
      "tip": "Import your live `/api/docs.json` URL directly into Postman using 'Import -> Link' to generate fully configured Postman collections in seconds.",
      "objective": "Import OpenAPI specifications into Postman to synchronize documentation and test collections.",
      "expectedOutcome": "Automated collection generation directly from OpenAPI/Swagger definitions.",
      "codeSnippet": "// Workflow:\n// 1. Express server exposes OpenAPI spec at: http://localhost:5000/api/docs.json\n// 2. Open Postman -> Click \"Import\"\n// 3. Paste URL: http://localhost:5000/api/docs.json\n// 4. Select: \"Generate Postman Collection\"\n// 5. Result: Complete collection generated automatically with all paths, params, and schemas!"
    },
    {
      "id": "M23-10",
      "number": "10",
      "title": "API Testing Workflow",
      "khmerTitle": "ស្ថាបត្យកម្ម API Testing Workflow និង Newman CLI ក្នុង CI/CD",
      "type": "architecture",
      "codeLanguage": "bash",
      "summary": "Newman is the command-line collection runner for Postman. It allows running Postman test suites directly from terminal scripts and automated GitHub Actions CI/CD pipelines, outputting structured test reports and failing pull requests if any assertion breaks.",
      "tip": "Run `npx newman run collection.json -e env.json` in your GitHub Actions pipeline to run your API tests on every pull request.",
      "objective": "Integrate Newman CLI into automated continuous integration workflows.",
      "expectedOutcome": "Automated API regression testing integrated into CI/CD pipelines.",
      "codeSnippet": "# Run Postman Collection headless via Newman CLI\nnpx newman run ./docs/postman/collection.json   --environment ./docs/postman/local-env.json   --reporters cli,htmlextra   --reporter-htmlextra-export ./reports/api-test-report.html\n\n# In GitHub Actions:\n# - name: Run Postman Tests via Newman\n#   run: npx newman run ./docs/postman/collection.json -e ./docs/postman/ci-env.json"
    }
  ],
  "M24": [
    {
      "id": "M24-01",
      "number": "01",
      "title": "Real-time Applications",
      "khmerTitle": "ស្វែងយល់ពីកម្មវិធី Real-time (Polling vs WebSockets)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Traditional HTTP is a unidirectional request-response protocol: the client must initiate every interaction, and the server cannot push data proactively. While short-polling or long-polling periodically checks for updates, they create massive HTTP overhead. True real-time applications (chat, live tracking, financial tickers, collaborative editing) require persistent, bidirectional communication channels.",
      "tip": "Don't use HTTP short-polling for real-time features! Polling every 2 seconds consumes massive bandwidth and wastes server CPU.",
      "objective": "Understand the differences between HTTP Polling, Server-Sent Events (SSE), and WebSockets.",
      "expectedOutcome": "Clear criteria for choosing between HTTP, SSE, and full-duplex WebSockets.",
      "codeSnippet": "// Comparison:\n// 1. Short Polling:   Client asks every 2s: \"New data? New data? New data?\" (High overhead)\n// 2. Long Polling:    Client asks; server holds connection open until data arrives (Moderate)\n// 3. SSE:             Unidirectional server-to-client streaming over HTTP (Great for tickers)\n// 4. WebSocket:       Bi-directional, persistent TCP connection with sub-millisecond frames (Ideal for chat/gaming)"
    },
    {
      "id": "M24-02",
      "number": "02",
      "title": "WebSocket Concept",
      "khmerTitle": "គោលការណ៍គ្រឹះនៃ WebSocket Protocol (RFC 6455)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "The WebSocket protocol (RFC 6455) provides full-duplex communication over a single long-lived TCP connection. It begins with an HTTP Upgrade handshake (`Upgrade: websocket`). Once established, tiny 2-to-10 byte binary frames replace bloated 1KB+ HTTP headers, enabling lightning-fast real-time messaging with minimal latency.",
      "tip": "WebSocket connections use the `ws://` (unencrypted) or `wss://` (TLS encrypted) URL schemes. Always use `wss://` in production.",
      "objective": "Understand the WebSocket upgrade handshake and frame architecture.",
      "expectedOutcome": "Technical understanding of low-overhead full-duplex socket protocols.",
      "codeSnippet": "// WebSocket Upgrade Handshake:\n// Client -> GET /chat HTTP/1.1\n//           Host: server.example.com\n//           Upgrade: websocket\n//           Connection: Upgrade\n//           Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\n//           Sec-WebSocket-Version: 13\n//\n// Server -> HTTP/1.1 101 Switching Protocols\n//           Upgrade: websocket\n//           Connection: Upgrade\n//           Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=\n//\n// Connection upgraded! Direct TCP full-duplex streaming begins."
    },
    {
      "id": "M24-03",
      "number": "03",
      "title": "Socket.IO",
      "khmerTitle": "ការស្វែងយល់ពីបណ្ណាល័យ Socket.IO",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Socket.IO is a feature-rich library that builds on top of WebSocket and HTTP long-polling fallbacks. Unlike raw WebSockets, Socket.IO provides automatic reconnection, connection buffering, heartbeat packet heartbeats, event-based multiplexing, rooms, and namespaces out of the box.",
      "tip": "Socket.IO is NOT a raw WebSocket implementation — a raw WebSocket client cannot connect to a Socket.IO server. Both client and server must use Socket.IO libraries.",
      "objective": "Understand Socket.IO advantages over raw WebSockets in production applications.",
      "expectedOutcome": "Knowledge of Socket.IO primitives: fallbacks, events, rooms, and auto-reconnection.",
      "codeSnippet": "// Why Socket.IO over raw ws:\n// 1. Reliability: Falls back to HTTP long-polling if corporate firewalls block WebSockets\n// 2. Auto-reconnect: Automatically reconnects and flushes buffered messages\n// 3. Named Events: emit(\"order:paid\", payload) instead of JSON.stringify({ type: ... })\n// 4. Broadcasting: Easily emit to all clients EXCEPT sender: socket.broadcast.emit(...)\n// 5. Rooms: Group sockets into virtual channels: socket.join(\"room-123\")"
    },
    {
      "id": "M24-04",
      "number": "04",
      "title": "Socket.IO Server",
      "khmerTitle": "ការបង្កើត និងភ្ជាប់ Socket.IO ជាមួយ Express HTTP Server",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "In Node.js, Socket.IO attaches to a native Node `http.Server` instance rather than directly to the Express `app` object. Express handles traditional REST endpoints while Socket.IO handles real-time WebSocket traffic over the exact same port.",
      "tip": "Configure CORS on the Socket.IO server separately from Express, as WebSocket upgrade handshakes require distinct origin verification.",
      "objective": "Initialize and attach a Socket.IO server to an Express HTTP server instance.",
      "expectedOutcome": "Unified HTTP and WebSocket server listening on a single port.",
      "codeSnippet": "import http from \"node:http\";\nimport express from \"express\";\nimport { Server } from \"socket.io\";\n\nconst app = express();\nconst server = http.createServer(app);\n\n// Initialize Socket.IO with CORS\nconst io = new Server(server, {\n  cors: {\n    origin: process.env.CLIENT_URL || \"http://localhost:3000\",\n    methods: [\"GET\", \"POST\"],\n    credentials: true,\n  },\n});\n\nio.on(\"connection\", (socket) => {\n  console.log(\"New client connected. Socket ID:\", socket.id);\n\n  socket.on(\"disconnect\", (reason) => {\n    console.log(`Client ${socket.id} disconnected: ${reason}`);\n  });\n});\n\nserver.listen(5000, () => console.log(\"Server listening on port 5000\"));"
    },
    {
      "id": "M24-05",
      "number": "05",
      "title": "Socket.IO Client",
      "khmerTitle": "ការភ្ជាប់ Client ទៅកាន់ Socket.IO Server",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Frontend clients connect using the `socket.io-client` library. The client establishes a persistent connection, listens for server-dispatched events via `socket.on()`, and transmits client events using `socket.emit()`.",
      "tip": "Always clean up socket listeners (`socket.off()`) when unmounting React components to prevent memory leaks and duplicate event firings.",
      "objective": "Connect frontend clients to Socket.IO and establish bidirectional event communication.",
      "expectedOutcome": "Operational client-server socket connection handling connect and disconnect states.",
      "codeSnippet": "// In Frontend (React or Vanilla JS):\nimport { io } from \"socket.io-client\";\n\nconst socket = io(\"http://localhost:5000\", {\n  autoConnect: true,\n  reconnectionAttempts: 5,\n  reconnectionDelay: 1000,\n});\n\nsocket.on(\"connect\", () => {\n  console.log(\"Connected to server with ID:\", socket.id);\n});\n\nsocket.on(\"connect_error\", (err) => {\n  console.error(\"Connection failed:\", err.message);\n});"
    },
    {
      "id": "M24-06",
      "number": "06",
      "title": "Events",
      "khmerTitle": "ការបញ្ជូន និងទទួល Events (Custom Events & Acknowledgments)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Socket.IO communication revolves around named custom events. `socket.emit('event', payload)` sends data, `socket.on('event', callback)` receives data, and Acknowledgments allow the receiver to invoke a callback to confirm message processing.",
      "tip": "Use acknowledgments (callbacks passed to `emit`) for guaranteed delivery confirmation without needing to create separate 'received' events.",
      "objective": "Emit and listen for custom events with payload delivery confirmations.",
      "expectedOutcome": "Robust message transmission with bidirectional request-response acknowledgments.",
      "codeSnippet": "// Server:\nio.on(\"connection\", (socket) => {\n  // Listen for message with acknowledgment callback\n  socket.on(\"send_message\", (data, callback) => {\n    console.log(\"Received:\", data);\n\n    // Broadcast to all other connected clients\n    socket.broadcast.emit(\"new_message\", data);\n\n    // Acknowledge receipt to the sender\n    if (typeof callback === \"function\") {\n      callback({ status: \"delivered\", timestamp: Date.now() });\n    }\n  });\n});"
    },
    {
      "id": "M24-07",
      "number": "07",
      "title": "Rooms",
      "khmerTitle": "ការគ្រប់គ្រង Channels តាមរយៈ Socket.IO Rooms",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Rooms are virtual server-side channels that sockets can join (`socket.join('room-id')`) and leave (`socket.leave('room-id')`). Broadcasting to a room (`io.to('room-id').emit(...)`) delivers messages only to the clients currently subscribed to that specific room, ideal for private chat rooms or order tracking.",
      "tip": "Every socket automatically joins a private room identified by its own `socket.id`. You can send a direct private message to any user with `io.to(recipientSocketId).emit(...)`.",
      "objective": "Implement room subscriptions for targeted channel messaging.",
      "expectedOutcome": "Isolated communication channels delivering messages strictly to room members.",
      "codeSnippet": "io.on(\"connection\", (socket) => {\n  // Join a specific chat channel or project room\n  socket.on(\"join_room\", (roomId) => {\n    socket.join(roomId);\n    console.log(`Socket ${socket.id} joined room: ${roomId}`);\n\n    // Notify others in that room only\n    socket.to(roomId).emit(\"user_joined\", { userId: socket.id });\n  });\n\n  // Send message strictly to members of this room\n  socket.on(\"chat_in_room\", ({ roomId, message }) => {\n    io.to(roomId).emit(\"receive_room_message\", {\n      sender: socket.id,\n      message,\n      sentAt: new Date(),\n    });\n  });\n});"
    },
    {
      "id": "M24-08",
      "number": "08",
      "title": "Real-time Notifications",
      "khmerTitle": "ការបញ្ជូន Real-time Notifications ទៅកាន់អ្នកប្រើប្រាស់ជាក់លាក់",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Real-time notifications inform specific users of instant updates (e.g. 'Your order has shipped', 'Someone liked your photo'). By associating an authenticated user's MongoDB `_id` with their active socket connection, the backend can target notification events directly to individual users across devices.",
      "tip": "Map user IDs to socket rooms: on connection, have each user join `socket.join('user:' + user._id)`. Then trigger notifications with `io.to('user:' + targetUserId).emit('notification', payload)`.",
      "objective": "Build a targeted real-time user notification pipeline.",
      "expectedOutcome": "Targeted push notifications delivered instantly to specific authenticated users.",
      "codeSnippet": "// Authenticate socket and join personal notification channel:\nio.use((socket, next) => {\n  const token = socket.handshake.auth.token;\n  try {\n    const user = jwt.verify(token, process.env.JWT_SECRET);\n    socket.user = user;\n    next();\n  } catch (err) {\n    next(new Error(\"Authentication failed\"));\n  }\n});\n\nio.on(\"connection\", (socket) => {\n  // Join room named after user's database ID\n  socket.join(`user:${socket.user.id}`);\n});\n\n// Anywhere in your backend (e.g. Order Service):\nexport const notifyUserOrderShipped = (io, userId, order) => {\n  io.to(`user:${userId}`).emit(\"notification\", {\n    type: \"ORDER_SHIPPED\",\n    title: \"Order on the way!\",\n    message: `Order #${order.id} has been dispatched.`,\n  });\n};"
    },
    {
      "id": "M24-09",
      "number": "09",
      "title": "Online Users",
      "khmerTitle": "ការតាមដានវត្តមាន Online Users (Presence Tracking)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Tracking user presence (online, away, offline) requires managing connected state across socket lifecycles. Maintaining a connected user registry in memory or a Redis Set allows broadcasting presence updates to all clients whenever a user connects or disconnects.",
      "tip": "Use Redis Sets (`SADD online_users userId` / `SREM online_users userId`) for presence tracking in multi-server architectures so all cluster nodes share the active user list.",
      "objective": "Implement online presence tracking with connection registries and disconnect event hooks.",
      "expectedOutcome": "Live user presence system updating contact online/offline indicators in real time.",
      "codeSnippet": "// In-memory or Redis presence tracking:\nconst onlineUsers = new Map(); // userId -> Set of socketIds\n\nio.on(\"connection\", (socket) => {\n  const userId = socket.user?.id;\n  if (userId) {\n    if (!onlineUsers.has(userId)) onlineUsers.set(userId, new Set());\n    onlineUsers.get(userId).add(socket.id);\n\n    // Broadcast user is online\n    io.emit(\"user_status_change\", { userId, status: \"online\" });\n  }\n\n  socket.on(\"disconnect\", () => {\n    if (userId && onlineUsers.has(userId)) {\n      const userSockets = onlineUsers.get(userId);\n      userSockets.delete(socket.id);\n      if (userSockets.size === 0) {\n        onlineUsers.delete(userId);\n        io.emit(\"user_status_change\", { userId, status: \"offline\" });\n      }\n    }\n  });\n});"
    },
    {
      "id": "M24-10",
      "number": "10",
      "title": "Chat Application",
      "khmerTitle": "ស្ថាបត្យកម្មប្រព័ន្ធ Real-time Chat ពេញលេញ",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "An enterprise real-time chat architecture combines persistent database storage with WebSocket delivery. When a message is sent, the server validates the payload, persists the chat document to MongoDB for conversation history, and broadcasts the event to the chat room via Socket.IO for sub-100ms real-time delivery.",
      "tip": "Always persist messages to MongoDB BEFORE broadcasting over Socket.IO so message history is guaranteed even if a client disconnects mid-delivery.",
      "objective": "Architect a full-featured real-time chat pipeline uniting MongoDB persistence with Socket.IO rooms.",
      "expectedOutcome": "End-to-end chat engine with message persistence, typing indicators, and delivery receipts.",
      "codeSnippet": "// Complete Real-Time Chat Handler:\nsocket.on(\"send_chat_message\", async ({ conversationId, text }, ack) => {\n  try {\n    // 1. Persist message in MongoDB\n    const message = await Message.create({\n      conversation: conversationId,\n      sender: socket.user.id,\n      text,\n      createdAt: new Date(),\n    });\n\n    // 2. Broadcast to all members in this conversation room\n    io.to(`conversation:${conversationId}`).emit(\"new_chat_message\", message);\n\n    // 3. Acknowledge back to sender\n    if (ack) ack({ success: true, messageId: message._id });\n  } catch (err) {\n    if (ack) ack({ success: false, error: err.message });\n  }\n});"
    }
  ],
  "M25": [
    {
      "id": "M25-01",
      "number": "01",
      "title": "Node.js Performance",
      "khmerTitle": "ការស្វែងយល់ពីប្រសិទ្ធភាព និង Performance Metrics ក្នុង Node.js",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Node.js is exceptionally fast for I/O-heavy operations due to its event-driven non-blocking architecture, but its single-threaded nature requires careful performance management. Key metrics to monitor include CPU utilization, Event Loop Lag, Resident Set Size (RSS) memory consumption, garbage collection pauses, and response latency percentiles (p95, p99).",
      "tip": "Monitor p95 and p99 response times rather than averages. An average of 50ms can easily hide the fact that 5% of your users are experiencing 3-second delays.",
      "objective": "Identify key performance metrics and bottlenecks in Node.js backend services.",
      "expectedOutcome": "Comprehensive understanding of performance profiling indicators.",
      "codeSnippet": "// Key Performance Metrics in Node.js:\n// 1. Event Loop Lag: Delay before scheduled callbacks execute (<20ms is healthy)\n// 2. Memory (RSS): Total memory allocated for the process (watch for memory leaks!)\n// 3. Heap Used: Actual memory utilized by V8 objects\n// 4. Latency Percentiles: p50 (median), p95 (95% of users), p99 (tail latency)"
    },
    {
      "id": "M25-02",
      "number": "02",
      "title": "Event Loop Performance",
      "khmerTitle": "ការទប់ស្កាត់ការស្ទះ Event Loop (Blocking the Event Loop)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Because JavaScript runs on a single main thread, any synchronous CPU-intensive computation (complex regex, synchronous file reading `fs.readFileSync`, heavy JSON stringification, cryptography) freezes the entire event loop. While blocked, the server cannot accept new requests or process timers, causing all concurrent users to experience connection timeouts.",
      "tip": "Never use synchronous methods (`readFileSync`, `crypto.pbkdf2Sync`, `bcrypt.hashSync`) inside Express request handlers in production.",
      "objective": "Diagnose and prevent Event Loop starvation caused by synchronous operations.",
      "expectedOutcome": "Non-blocking codebase keeping the main thread free to handle concurrent requests.",
      "codeSnippet": "// DANGEROUS: Blocks the entire server for all concurrent users!\napp.get(\"/bad\", (req, res) => {\n  const data = fs.readFileSync(\"/huge-file.csv\"); // Event loop BLOCKED!\n  res.send(data);\n});\n\n// PROPER: Non-blocking asynchronous I/O allows thousands of concurrent requests\napp.get(\"/good\", async (req, res) => {\n  const data = await fs.promises.readFile(\"/huge-file.csv\"); // Event loop stays FREE!\n  res.send(data);\n});"
    },
    {
      "id": "M25-03",
      "number": "03",
      "title": "Async Best Practices",
      "khmerTitle": "ការអនុវត្ត Async ល្អបំផុត (Promise.all vs Sequential Await)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "A common performance anti-pattern is sequentially awaiting independent asynchronous operations one after another. If fetching user details takes 100ms and fetching user orders takes 100ms, sequential awaits total 200ms. Running independent promises concurrently via `Promise.all()` executes them in parallel, reducing total latency to just 100ms.",
      "tip": "Use `Promise.all([promise1, promise2])` whenever two or more async operations do not depend on each other's return values.",
      "objective": "Optimize async execution workflows using parallel promise resolution.",
      "expectedOutcome": "Halved endpoint latency by eliminating sequential waterfalls.",
      "codeSnippet": "// SLOW: Waterfall execution (Total: ~200ms)\nconst user = await User.findById(userId);       // 100ms\nconst orders = await Order.find({ user: userId }); // 100ms\n\n// FAST: Parallel concurrent execution (Total: ~100ms!)\nconst [user, orders] = await Promise.all([\n  User.findById(userId),\n  Order.find({ user: userId }),\n]);"
    },
    {
      "id": "M25-04",
      "number": "04",
      "title": "MongoDB Query Optimization",
      "khmerTitle": "ការបង្កើនល្បឿន MongoDB Queries ជាមួយ Lean និង Projections",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "By default, Mongoose wraps query results in full Mongoose Document instances complete with change tracking, getters, and schema methods. For read-heavy endpoints, appending `.lean()` skips document instantiation and returns plain JavaScript objects, reducing memory allocation and improving query execution speeds by up to 400%.",
      "tip": "Always append `.lean()` to GET queries where you do not need to call `.save()` on the returned documents.",
      "objective": "Apply query optimizations including .lean(), field projections (.select()), and limit clauses.",
      "expectedOutcome": "Substantially reduced memory footprint and faster JSON serialization.",
      "codeSnippet": "// High Performance Query:\n// 1. .select() only fetches necessary fields (reduces network transfer)\n// 2. .lean() skips heavy Mongoose Document overhead (returns plain JS objects)\n// 3. .limit() restricts total document count\nconst products = await Product.find({ isPublished: true })\n  .select(\"title price thumbnail rating\") // Field projection\n  .limit(20)\n  .lean(); // 3-4x faster than default find()!"
    },
    {
      "id": "M25-05",
      "number": "05",
      "title": "MongoDB Indexing",
      "khmerTitle": "ការបង្កើត និងគ្រប់គ្រង Database Indexes (Single & Compound)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Without indexes, MongoDB must perform a Collection Scan (`COLLSCAN`), inspecting every single document in the collection to satisfy a query. Indexes create ordered B-tree data structures that locate matching documents in milliseconds (`IXSCAN`). Single-field, compound, and text indexes are essential for scalable databases.",
      "tip": "Use `explain('executionStats')` on your queries to verify they use `IXSCAN` (index scan) instead of `COLLSCAN` (table scan).",
      "objective": "Design efficient single-field and compound indexes supporting common query patterns.",
      "expectedOutcome": "Transformation of slow collection scans into high-speed index lookups.",
      "codeSnippet": "const productSchema = new mongoose.Schema({\n  name: { type: String, required: true },\n  category: { type: String, index: true }, // Single-field index\n  price: Number,\n  createdAt: Date,\n});\n\n// Compound index for queries that filter by category and sort by price:\n// db.products.find({ category: \"Electronics\" }).sort({ price: -1 })\nproductSchema.index({ category: 1, price: -1 });\n\n// Verify query execution in MongoDB:\n// await Product.find({ category: \"Electronics\" }).explain(\"executionStats\");"
    },
    {
      "id": "M25-06",
      "number": "06",
      "title": "API Pagination",
      "khmerTitle": "យុទ្ធសាស្ត្រ Pagination (Offset vs Cursor-based Pagination)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Returning entire collections in a single API call degrades database performance and crashes mobile clients. Offset pagination (`skip` + `limit`) is simple to implement but suffers from performance degradation at high offsets (`skip(100000)` scans 100,000 documents). Cursor-based pagination (`_id: { $gt: lastId }`) maintains constant O(1) performance regardless of dataset depth.",
      "tip": "Use cursor-based pagination (keyset pagination) for infinite scroll feeds to achieve constant O(1) query time.",
      "objective": "Implement both offset and high-performance cursor-based pagination in Express APIs.",
      "expectedOutcome": "Scalable pagination strategies preventing memory saturation and slow deep queries.",
      "codeSnippet": "// 1. Offset Pagination (Good for numbered page UI):\nconst page = Number(req.query.page) || 1;\nconst limit = Number(req.query.limit) || 20;\nconst skip = (page - 1) * limit;\nconst items = await Product.find().skip(skip).limit(limit).lean();\n\n// 2. Cursor Pagination (Optimal for Infinite Scroll & Massive Datasets):\n// Query: /api/products?cursor=64f1a2b3c4...&limit=20\nconst { cursor, limit = 20 } = req.query;\nconst query = cursor ? { _id: { $lt: cursor } } : {}; // uses indexed _id directly!\n\nconst products = await Product.find(query)\n  .sort({ _id: -1 })\n  .limit(Number(limit))\n  .lean();"
    },
    {
      "id": "M25-07",
      "number": "07",
      "title": "Caching",
      "khmerTitle": "គោលការណ៍គ្រឹះនៃ Caching (Cache-Aside Pattern & TTL)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Caching stores copies of frequently accessed data in high-speed, volatile storage layers (such as RAM) so future requests can be served instantly without querying the primary database. In the Cache-Aside pattern, the application checks the cache first: if found (cache hit), it returns data immediately; if missing (cache miss), it queries the database, populates the cache with a Time-To-Live (TTL), and responds.",
      "tip": "Always configure a Time-To-Live (TTL) on cached items to prevent stale data from lingering permanently.",
      "objective": "Master the Cache-Aside pattern, cache hit/miss flows, and TTL expiration strategies.",
      "expectedOutcome": "Solid theoretical and practical grasp of distributed caching concepts.",
      "codeSnippet": "// Cache-Aside Workflow:\n//\n// Client Request -> [Check Cache (Redis)]\n//                         │\n//            ┌────────────┴────────────┐\n//         Hit (Data exists)        Miss (Not in cache)\n//            │                         │\n//            ↓                         ↓\n//     Return cached data      Query Primary Database (MongoDB)\n//                                      │\n//                                      ↓\n//                             Save to Cache (with TTL)\n//                                      │\n//                                      ↓\n//                             Return data to client"
    },
    {
      "id": "M25-08",
      "number": "08",
      "title": "Redis",
      "khmerTitle": "ការស្វែងយល់ពី In-Memory Data Store (Redis)",
      "type": "concept",
      "codeLanguage": "bash",
      "summary": "Redis (Remote Dictionary Server) is an open-source, in-memory key-value data structure store. Because it holds all data in RAM rather than spinning disks or flash memory, read and write operations execute in sub-millisecond speeds (over 100,000 operations per second). Redis supports versatile data types: strings, hashes, lists, sets, and sorted sets.",
      "tip": "Run Redis locally in one command using Docker: `docker run -d -p 6379:6379 redis:alpine`.",
      "objective": "Understand Redis architecture, memory-first performance, and supported data structures.",
      "expectedOutcome": "Preparedness to integrate Redis as an application caching and state layer.",
      "codeSnippet": "# Common Redis CLI commands:\nSET user:100:name \"Alice\" EX 3600  # Set key with 1-hour expiration (TTL)\nGET user:100:name                  # Retrieve value -> \"Alice\"\nDEL user:100:name                  # Delete key immediately\nKEYS product:*                     # Search keys (use SCAN in production!)\nTTL user:100:name                  # Check remaining seconds before expiry"
    },
    {
      "id": "M25-09",
      "number": "09",
      "title": "Redis with Node.js",
      "khmerTitle": "ការភ្ជាប់ និងប្រើប្រាស់ Redis ក្នុង Node.js (ioredis)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "`ioredis` is a robust, full-featured Redis client for Node.js. It features built-in support for Promises, cluster configurations, sentinel failover, and automatic reconnection. Establishing a single shared Redis client singleton provides high-throughput caching throughout your Express services.",
      "tip": "Use `ioredis` instead of the legacy `redis` package for superior cluster management and better TypeScript support.",
      "objective": "Connect to a Redis instance from Node.js using ioredis with error handling.",
      "expectedOutcome": "Operational Redis client connection handling read/write operations.",
      "codeSnippet": "import Redis from \"ioredis\";\n\nexport const redis = new Redis({\n  host: process.env.REDIS_HOST || \"localhost\",\n  port: Number(process.env.REDIS_PORT) || 6379,\n  password: process.env.REDIS_PASSWORD || undefined,\n  retryStrategy: (times) => Math.min(times * 50, 2000), // Exponential backoff\n});\n\nredis.on(\"connect\", () => console.log(\"Connected to Redis successfully!\"));\nredis.on(\"error\", (err) => console.error(\"Redis connection error:\", err));"
    },
    {
      "id": "M25-10",
      "number": "10",
      "title": "Response Caching",
      "khmerTitle": "ការបង្កើត Express Cache Middleware ជាមួយ Redis",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Response caching intercepts incoming GET requests, constructs a cache key from the request URL, and checks Redis. If cached, it sends the stored JSON string immediately (<2ms), bypassing database lookups and controller handlers entirely. When data mutations occur (POST/PUT/DELETE), the cache key is purged.",
      "tip": "Use `req.originalUrl` as the Redis cache key so query parameters (e.g. `?page=1&limit=10`) are preserved in distinct cache entries.",
      "objective": "Construct an Express caching middleware that automatically intercepts and caches responses.",
      "expectedOutcome": "Dramatic response time reduction from ~150ms to ~2ms for cached endpoints.",
      "codeSnippet": "// middleware/cache.js\nimport { redis } from \"../config/redis.js\";\n\nexport const cache = (durationInSeconds = 300) => async (req, res, next) => {\n  if (req.method !== \"GET\") return next();\n\n  const key = `cache:${req.originalUrl}`;\n  try {\n    const cachedData = await redis.get(key);\n    if (cachedData) {\n      return res.status(200).json(JSON.parse(cachedData));\n    }\n\n    // Intercept res.json to capture response before sending\n    const originalJson = res.json.bind(res);\n    res.json = (body) => {\n      // Store in Redis with TTL\n      redis.set(key, JSON.stringify(body), \"EX\", durationInSeconds);\n      return originalJson(body);\n    };\n\n    next();\n  } catch (err) {\n    next(); // On cache failure, gracefully proceed to database\n  }\n};"
    },
    {
      "id": "M25-11",
      "number": "11",
      "title": "Compression",
      "khmerTitle": "ការបង្រួម HTTP Responses ជាមួយ compression (Gzip / Brotli)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "The `compression` middleware compresses HTTP response bodies using Gzip or Brotli algorithms before transmitting them over the network. Compressing JSON payloads reduces transfer sizes by 60% to 80%, resulting in dramatically faster page loads on mobile networks and reduced cloud bandwidth costs.",
      "tip": "Place `app.use(compression())` near the top of your middleware stack to compress all responses exceeding 1KB.",
      "objective": "Enable Gzip compression in Express to reduce data payload size.",
      "expectedOutcome": "Up to 80% reduction in transmitted network byte sizes for JSON responses.",
      "codeSnippet": "import express from \"express\";\nimport compression from \"compression\";\n\nconst app = express();\n\n// Compress all HTTP responses exceeding 1KB\napp.use(\n  compression({\n    level: 6, // Optimal balance between compression ratio and CPU usage\n    threshold: 1024, // Only compress responses larger than 1KB\n    filter: (req, res) => {\n      if (req.headers[\"x-no-compression\"]) return false;\n      return compression.filter(req, res);\n    },\n  })\n);"
    },
    {
      "id": "M25-12",
      "number": "12",
      "title": "Performance Monitoring",
      "khmerTitle": "ការតាមដាន Performance តាមរយៈ APM (Prometheus & Grafana)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Continuous performance monitoring tracks production application health. Application Performance Monitoring (APM) tools (Prometheus, Grafana, New Relic, Datadog) measure endpoint latency distributions, error rates, throughput (requests per second), and database query times to detect performance regressions before users complain.",
      "tip": "Expose a `/metrics` endpoint using `prom-client` to scrape runtime metrics into Prometheus and visualize real-time dashboards in Grafana.",
      "objective": "Architect performance instrumentation and application telemetry collection.",
      "expectedOutcome": "Production-ready observability monitoring latency, memory, and throughput.",
      "codeSnippet": "// Instrumentation with prom-client:\nimport client from \"prom-client\";\n\n// Collect default Node.js system metrics (event loop, memory, CPU)\nclient.collectDefaultMetrics({ prefix: \"app_\" });\n\n// Custom HTTP request duration histogram\nexport const httpRequestDuration = new client.Histogram({\n  name: \"http_request_duration_seconds\",\n  help: \"Duration of HTTP requests in seconds\",\n  labelNames: [\"method\", \"route\", \"status_code\"],\n  buckets: [0.05, 0.1, 0.3, 0.5, 1, 2, 5],\n});\n\n// Expose /metrics endpoint for Prometheus scraping\napp.get(\"/metrics\", async (req, res) => {\n  res.set(\"Content-Type\", client.register.contentType);\n  res.end(await client.register.metrics());\n});"
    }
  ]
};
