/**
 * modules-26-29.mjs
 * Detailed curriculum data for Modules 26 through 29 (53 topics total)
 */

export const MODULES_26_29 = {
  "M26": [
    {
      "id": "M26-01",
      "number": "01",
      "title": "Background Jobs",
      "khmerTitle": "ការស្វែងយល់ពី Background Jobs ក្នុង Web Backend",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Background jobs are asynchronous tasks that execute outside the critical request-response cycle of an HTTP server. Heavy computations (video transcoding, large CSV generation, external API syncs, batch emails) that take seconds or minutes to complete are moved out of HTTP handlers so users receive instant HTTP responses.",
      "tip": "If a task takes longer than 200ms to complete, offload it to a background job instead of holding the HTTP connection open.",
      "objective": "Understand why long-running computational tasks must run asynchronously in the background.",
      "expectedOutcome": "Clear criteria for identifying tasks that should be offloaded from HTTP threads.",
      "codeSnippet": "// Synchronous (Bad UX - 5s delay):\n// POST /checkout -> [Charge Card] -> [Generate PDF Invoice (4s)] -> [Send Email (1s)] -> 200 OK (5.2s total!)\n\n// Asynchronous Background Jobs (Great UX - 50ms):\n// POST /checkout -> [Charge Card] -> [Enqueue Job: invoice + email] -> 200 OK (50ms!)\n// [Background Worker] consumes job in background and emails PDF without blocking user."
    },
    {
      "id": "M26-02",
      "number": "02",
      "title": "Why Background Jobs?",
      "khmerTitle": "មូលហេតុចម្បងដែលត្រូវប្រើប្រាស់ Background Processing",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Background jobs solve three critical production challenges: responsiveness, reliability, and scalability. Responsiveness ensures end-users experience snappy, sub-100ms API responses. Reliability ensures transient failures (e.g. SMTP outages) are automatically retried without losing user actions. Scalability allows workers to scale independently from API web servers.",
      "tip": "Separating API web servers from background workers lets you scale worker CPU independently during heavy batch workloads without impacting web API throughput.",
      "objective": "Analyze responsiveness, reliability, and resource isolation benefits of job architectures.",
      "expectedOutcome": "Understanding of enterprise asynchronous job decoupling and fault tolerance.",
      "codeSnippet": "// 3 Pillars of Background Jobs:\n// 1. User Responsiveness: Return 202 Accepted or 201 Created immediately\n// 2. Failure Resilience: Automated retries with exponential backoff on network dropouts\n// 3. Rate-Limiting External APIs: Throttle outgoing requests to avoid 3rd-party rate limits"
    },
    {
      "id": "M26-03",
      "number": "03",
      "title": "Queue Concept",
      "khmerTitle": "គោលការណ៍គ្រឹះនៃ Message Queue (FIFO, Priority, Dead Letter)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "A Message Queue acts as a durable buffer between job producers (Express API) and consumers (background workers). Queues adhere to First-In-First-Out (FIFO) ordering by default, but support priority scheduling (e.g. password resets jump ahead of marketing newsletters) and Dead Letter Queues (DLQ) for isolating permanently failing jobs.",
      "tip": "Use Dead Letter Queues (DLQ) to capture jobs that failed all retry attempts so developers can inspect error payloads and replay them once fixed.",
      "objective": "Master message queue patterns: FIFO ordering, priority queues, and dead letter queues.",
      "expectedOutcome": "Architectural blueprint for reliable distributed task queues.",
      "codeSnippet": "// Message Queue Lifecycle:\n//\n// [Producer (Express API)]\n//          │\n//          ↓ (Enqueues Job)\n// [Redis Queue: \"reports\"]\n//          │\n//          ├── Job 1 (Priority: Low)\n//          ├── Job 2 (Priority: Normal)\n//          └── Job 3 (Priority: Urgent - Jumps to Front!)\n//          │\n//          ↓ (Pulls Job)\n// [Worker Process (Node.js)] ─── Fails 5x ───> [Dead Letter Queue (DLQ)]"
    },
    {
      "id": "M26-04",
      "number": "04",
      "title": "Redis",
      "khmerTitle": "តួនាទីរបស់ Redis ក្នុងប្រព័ន្ធ Message Queues",
      "type": "concept",
      "codeLanguage": "bash",
      "summary": "Redis is the industry standard backing store for Node.js message queues because of its atomic data structures (`LPUSH`, `BRPOP`, `ZADD`). In-memory storage provides microsecond task scheduling, while Redis Streams and Pub/Sub primitives ensure guaranteed at-least-once message delivery across clustered workers.",
      "tip": "Enable Redis AOF (Append-Only File) persistence (`appendonly yes`) in production so pending queue jobs survive unexpected Redis server restarts.",
      "objective": "Understand how Redis atomic data structures power distributed message queues.",
      "expectedOutcome": "Confidence configuring Redis as a high-throughput job queue engine.",
      "codeSnippet": "# Redis atomic operations for queues:\nLPUSH queue:jobs '{\"id\": 101, \"task\": \"send_email\"}' # Producer adds job\nBRPOP queue:jobs 0                                    # Worker blocks waiting for job atomically\nZADD queue:delayed 1773729600 '{\"id\": 102}'            # Scheduled delayed job sorted by timestamp"
    },
    {
      "id": "M26-05",
      "number": "05",
      "title": "BullMQ",
      "khmerTitle": "ការស្វែងយល់ពីបណ្ណាល័យ BullMQ ទំនើប",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "BullMQ is the fastest, most reliable, TypeScript-native Redis-based queue library for Node.js. It features automatic parent-child job flows, rate-limited queues, concurrency controls, cron-based repeatable scheduling, sandboxed worker processes, and pause/resume capabilities.",
      "tip": "Use BullMQ instead of the legacy 'bull' library. BullMQ is written from scratch in modern TypeScript with better Redis Stream support and lower memory overhead.",
      "objective": "Understand the core architecture and features of the BullMQ queue system.",
      "expectedOutcome": "Familiarity with BullMQ Queue, Worker, and QueueEvents abstractions.",
      "codeSnippet": "// Core BullMQ Primitives:\n// 1. Queue:       Used by producers to add jobs with options (delay, priority, retries)\n// 2. Worker:      Background process that consumes jobs and executes business logic\n// 3. QueueEvents: Emits lifecycle events ('completed', 'failed', 'progress') for monitoring"
    },
    {
      "id": "M26-06",
      "number": "06",
      "title": "Producers",
      "khmerTitle": "ការបង្កើត Job Producer ដើម្បីបញ្ជូន Tasks ទៅកាន់ Queue",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "A producer is any service that constructs and pushes tasks into a BullMQ queue using `queue.add(name, data, opts)`. The Express controller or service layer functions as the producer, submitting jobs with options such as retry counts, exponential backoff, and execution delays.",
      "tip": "Always pass serializable JSON data (strings, numbers, plain objects) into `queue.add()` — never pass complex class instances or database connection handles.",
      "objective": "Construct BullMQ producer utilities pushing payloads with retry options.",
      "expectedOutcome": "Fast job creation that returns immediate HTTP confirmation to clients.",
      "codeSnippet": "import { Queue } from \"bullmq\";\nimport { redisConnection } from \"../config/redis.js\";\n\n// Initialize Queue instance\nexport const videoQueue = new Queue(\"video-processing\", {\n  connection: redisConnection,\n});\n\n// Producer function called from Express controller:\nexport const enqueueVideoTranscode = async (videoId, filePath, targetResolution) => {\n  const job = await videoQueue.add(\n    \"transcode\",\n    { videoId, filePath, targetResolution },\n    {\n      attempts: 3, // Retry up to 3 times on crash\n      backoff: { type: \"exponential\", delay: 2000 }, // 2s, 4s, 8s\n      removeOnComplete: true, // Auto-cleanup succeeded jobs\n    }\n  );\n\n  console.log(`Job enqueued: ${job.id}`);\n  return job.id;\n};"
    },
    {
      "id": "M26-07",
      "number": "07",
      "title": "Workers",
      "khmerTitle": "ការបង្កើត Background Worker ដើម្បីទាញយក និងដំណើរការ Jobs",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "A Worker is a background process that listens to a specific BullMQ queue and processes incoming jobs. Workers run in separate Node.js processes or separate Docker containers, ensuring CPU-heavy job execution never impacts the responsiveness of user-facing Express API servers.",
      "tip": "Set `concurrency: 5` (or match your server CPU cores) in worker options to process multiple jobs simultaneously on a single worker instance.",
      "objective": "Build dedicated BullMQ worker processes with concurrency configuration.",
      "expectedOutcome": "Asynchronous worker consuming and processing jobs concurrently in the background.",
      "codeSnippet": "import { Worker } from \"bullmq\";\nimport { redisConnection } from \"../config/redis.js\";\n\nexport const videoWorker = new Worker(\n  \"video-processing\",\n  async (job) => {\n    console.log(`[Worker] Processing job ${job.id}: transcode ${job.data.videoId}`);\n\n    // Simulate heavy CPU transcoding\n    await transcodeVideoFile(job.data.filePath, job.data.targetResolution);\n\n    console.log(`[Worker] Job ${job.id} completed successfully!`);\n    return { status: \"processed\", path: `/videos/${job.data.videoId}.mp4` };\n  },\n  {\n    connection: redisConnection,\n    concurrency: 4, // Process 4 video jobs concurrently\n  }\n);"
    },
    {
      "id": "M26-08",
      "number": "08",
      "title": "Job Processing",
      "khmerTitle": "ការតាមដាន Job Progress និងការបញ្ជូនទិន្នន័យត្រឡប់មកវិញ",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "During execution, long-running jobs can report real-time progress percentages using `job.updateProgress(percent)`. Workers return a final result object upon completion, or throw an error to signal failure. Clients can query job progress via polling or real-time Socket.IO broadcasts.",
      "tip": "Emit `job.updateProgress()` during multi-step jobs so frontend progress bars can update dynamically via WebSockets.",
      "objective": "Track and broadcast job execution progress in real-time.",
      "expectedOutcome": "Granular progress monitoring for long-running backend processes.",
      "codeSnippet": "const reportWorker = new Worker(\"reports\", async (job) => {\n  await job.updateProgress(10); // 10%\n\n  const data = await queryLargeDataset();\n  await job.updateProgress(50); // 50%\n\n  const pdfBuffer = await generatePdf(data);\n  await job.updateProgress(90); // 90%\n\n  const fileUrl = await uploadToCloud(pdfBuffer);\n  await job.updateProgress(100); // 100%\n\n  return { reportUrl: fileUrl };\n}, { connection: redisConnection });"
    },
    {
      "id": "M26-09",
      "number": "09",
      "title": "Retry",
      "khmerTitle": "យុទ្ធសាស្ត្រ Retry ជាមួយ Exponential Backoff",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "External networks and APIs experience transient glitches (rate limits, timeouts, temporary 503s). Configuring automatic retries with Exponential Backoff (`2s`, `4s`, `8s`, `16s`) ensures that temporary network drops resolve automatically without dropping messages or spamming failing endpoints.",
      "tip": "Always use exponential backoff rather than fixed delay retries — exponential backoff gives recovering third-party servers breathing room to stabilize.",
      "objective": "Configure resilient automated retry policies with exponential backoff.",
      "expectedOutcome": "Automated self-healing job execution resilient to network interruptions.",
      "codeSnippet": "// Producer configuring exponential backoff retries:\nawait orderQueue.add(\n  \"process-payment\",\n  { orderId: \"ord_10293\", amount: 99.00 },\n  {\n    attempts: 5, // Try 5 times before declaring permanent failure\n    backoff: {\n      type: \"exponential\",\n      delay: 3000, // 3s, 6s, 12s, 24s...\n    },\n  }\n);"
    },
    {
      "id": "M26-10",
      "number": "10",
      "title": "Failed Jobs",
      "khmerTitle": "ការគ្រប់គ្រង និងត្រួតពិនិត្យ Failed Jobs (Bull Board)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "When a job exhausts all configured retry attempts, it moves to the 'failed' state with the error stack trace attached. Mounting the `Bull Board` web dashboard provides a visual admin interface to inspect failed job payloads, view error stack traces, and manually retry jobs with a single click.",
      "tip": "Protect your Bull Board dashboard route (`/admin/queues`) behind admin authentication and IP whitelisting in production.",
      "objective": "Monitor failed jobs and mount Bull Board UI inside an Express application.",
      "expectedOutcome": "Visual web dashboard for queue inspection, metrics, and manual job retries.",
      "codeSnippet": "import { createBullBoard } from \"@bull-board/api\";\nimport { BullMQAdapter } from \"@bull-board/api/bullMQAdapter.js\";\nimport { ExpressAdapter } from \"@bull-board/express\";\n\nconst serverAdapter = new ExpressAdapter();\nserverAdapter.setBasePath(\"/admin/queues\");\n\ncreateBullBoard({\n  queues: [new BullMQAdapter(emailQueue), new BullMQAdapter(videoQueue)],\n  serverAdapter,\n});\n\n// Protect with admin auth guard and mount:\napp.use(\"/admin/queues\", protect, restrictTo(\"admin\"), serverAdapter.getRouter());"
    },
    {
      "id": "M26-11",
      "number": "11",
      "title": "Scheduled Jobs",
      "khmerTitle": "ការកំណត់ Scheduled Cron Jobs ក្នុង BullMQ (Repeatable Jobs)",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Repeatable jobs execute automatically on a scheduled recurring basis using standard 5-part cron syntax (e.g. `0 0 * * *` for daily at midnight). Unlike local OS crontabs or in-process node-cron schedulers, BullMQ repeatable jobs are synchronized across cluster instances via Redis, preventing duplicate execution.",
      "tip": "BullMQ repeatable jobs automatically deduplicate across multiple server instances — only ONE worker in your cluster will run the scheduled job at midnight.",
      "objective": "Configure cluster-safe repeatable scheduled jobs using cron expressions.",
      "expectedOutcome": "Reliable scheduled tasks (daily digest, database vacuum, report exports).",
      "codeSnippet": "// Schedule a repeatable job to run every day at midnight (UTC)\nawait reportQueue.add(\n  \"daily-sales-summary\",\n  { department: \"ecommerce\" },\n  {\n    repeat: {\n      pattern: \"0 0 * * *\", // Standard Cron: minute hour day month weekday\n    },\n  }\n);\n\nconsole.log(\"Repeatable daily job scheduled!\");"
    },
    {
      "id": "M26-12",
      "number": "12",
      "title": "Email Queue",
      "khmerTitle": "ស្ថាបត្យកម្ម Email Queue System ពេញលេញក្នុង Production",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "An enterprise email queue architecture combines an Express producer, a Redis buffer, and dedicated Nodemailer workers. By segregating queues into high-priority transactional streams (password resets) and lower-priority batch streams (marketing campaigns), mission-critical emails are never delayed by bulk marketing broadcasts.",
      "tip": "Create two separate queues: `email:critical` (concurrency 10) and `email:bulk` (concurrency 2 with rate limits) to guarantee zero latency on password resets.",
      "objective": "Architect a production-grade multi-tier email processing queue.",
      "expectedOutcome": "Decoupled, fault-tolerant email dispatch system with zero impact on HTTP latency.",
      "codeSnippet": "// Complete Architecture Blueprint:\n//\n// Express Route: POST /auth/forgot-password\n//      │\n//      ↓ (Enqueues job in 2ms)\n// [Redis Queue: \"email-critical\"]\n//      │\n//      ↓ (Worker pulls job)\n// [Email Worker Process]\n//      ├── Formats HTML template\n//      ├── Contacts SMTP Relay (Brevo/SES)\n//      └── If SMTP fails: Retries automatically in 3s (Exponential backoff)"
    }
  ],
  "M27": [
    {
      "id": "M27-01",
      "number": "01",
      "title": "Backend Folder Structure",
      "khmerTitle": "រចនាសម្ព័ន្ធ Folder ស្តង់ដារសម្រាប់ Enterprise Backend",
      "type": "architecture",
      "codeLanguage": "bash",
      "summary": "A scalable backend codebase enforces strict Separation of Concerns (SoC). Organizing code into discrete layers (`config`, `routes`, `controllers`, `services`, `models`, `middleware`, `validators`, `utils`) prevents messy monolithic files and ensures code remains testable and maintainable as the project grows.",
      "tip": "Keep business logic strictly inside `services/` and HTTP protocol logic inside `controllers/`. This makes swapping Express for Fastify or writing unit tests trivial.",
      "objective": "Organize a modular, production-ready directory structure for Node.js Express projects.",
      "expectedOutcome": "Standardized enterprise project layout adopted across all features.",
      "codeSnippet": "src/\n├── config/         # Environment vars, database connections, logger\n├── controllers/    # Request/response handling, HTTP status codes\n├── services/       # Core business logic, data calculations, 3rd party APIs\n├── models/         # Mongoose schemas and database models\n├── routes/         # Express router endpoint definitions\n├── middleware/     # Auth, error handling, rate limiters, upload guards\n├── validators/     # Zod/Joi request validation schemas\n├── utils/          # AppError class, formatters, helpers\n├── jobs/           # BullMQ queue producers and workers\n└── app.js          # Express app assembly (no listen())"
    },
    {
      "id": "M27-02",
      "number": "02",
      "title": "Routes",
      "khmerTitle": "តួនាទី និងការរៀបចំ Routes Layer",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The Routes layer defines the API's public URL surface and maps incoming HTTP verbs and paths to corresponding controller handlers. Route files should remain lean: they declare paths, mount validation and auth middleware, and delegate immediately to controllers without executing business logic.",
      "tip": "Group related endpoints using `router.route('/path').get(...).post(...)` for clean, readable endpoint declarations.",
      "objective": "Structure declarative Express routers free of embedded business logic.",
      "expectedOutcome": "Clean, readable route definitions acting purely as HTTP routing maps.",
      "codeSnippet": "// routes/product.routes.js\nimport express from \"express\";\nimport { protect } from \"../middleware/auth.js\";\nimport { restrictTo } from \"../middleware/role.js\";\nimport { validate } from \"../middleware/validate.js\";\nimport { createProductSchema } from \"../validators/product.validator.js\";\nimport * as productController from \"../controllers/product.controller.js\";\n\nconst router = express.Router();\n\nrouter.route(\"/\")\n  .get(productController.getAllProducts)\n  .post(protect, restrictTo(\"admin\"), validate(createProductSchema), productController.createProduct);\n\nrouter.route(\"/:id\")\n  .get(productController.getProductById)\n  .patch(protect, restrictTo(\"admin\"), productController.updateProduct)\n  .delete(protect, restrictTo(\"admin\"), productController.deleteProduct);\n\nexport default router;"
    },
    {
      "id": "M27-03",
      "number": "03",
      "title": "Controllers",
      "khmerTitle": "តួនាទី និងការរៀបចំ Controllers Layer",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Controllers handle the HTTP transport protocol. A controller extracts inputs from `req.body`, `req.query`, and `req.params`, invokes appropriate service layer methods to perform work, and formats the output into standard JSON envelopes with correct HTTP status codes (200, 201, 204).",
      "tip": "Never write raw database queries (`Product.find()`) directly inside controllers — delegate queries to the service layer to keep controllers focused solely on HTTP.",
      "objective": "Implement clean controllers translating HTTP requests to service calls.",
      "expectedOutcome": "Lean controllers decoupled from database drivers and raw business logic.",
      "codeSnippet": "// controllers/product.controller.js\nimport * as productService from \"../services/product.service.js\";\n\nexport const createProduct = async (req, res, next) => {\n  try {\n    const product = await productService.createProduct(req.body, req.user._id);\n\n    res.status(201).json({\n      status: \"success\",\n      data: { product },\n    });\n  } catch (err) {\n    next(err);\n  }\n};"
    },
    {
      "id": "M27-04",
      "number": "04",
      "title": "Services",
      "khmerTitle": "តួនាទី និងការរៀបចំ Services Layer (Core Business Logic)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The Service layer contains the core business logic of the application. Services know nothing about Express, `req`, or `res`. They receive plain JavaScript objects, perform computations, execute database operations, dispatch emails, and return data or throw errors. This makes services 100% reusable across CLI scripts, tests, and API routes.",
      "tip": "Because services do not touch `req` or `res`, you can unit test them without needing Supertest or HTTP simulation.",
      "objective": "Encapsulate business operations inside transport-agnostic service functions.",
      "expectedOutcome": "Portable, testable business logic isolated from HTTP routing frameworks.",
      "codeSnippet": "// services/product.service.js\nimport { Product } from \"../models/product.model.js\";\nimport { AppError } from \"../utils/AppError.js\";\n\nexport const createProduct = async (productData, authorId) => {\n  // Business rule: Check duplicate title\n  const existing = await Product.findOne({ title: productData.title });\n  if (existing) {\n    throw new AppError(\"A product with this title already exists\", 409);\n  }\n\n  // Calculate pricing margin or business logic\n  const profitMargin = productData.price - (productData.costPrice || 0);\n\n  const product = await Product.create({\n    ...productData,\n    creator: authorId,\n    profitMargin,\n  });\n\n  return product;\n};"
    },
    {
      "id": "M27-05",
      "number": "05",
      "title": "Models",
      "khmerTitle": "តួនាទី និងការរៀបចំ Models Layer (Mongoose Schemas)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The Models layer defines the database schema, data validation rules, indexes, virtuals, and lifecycle hooks (pre/post middleware). Models represent the single source of truth for database structure and data integrity.",
      "tip": "Encapsulate instance-specific helper logic (like password hashing or token verification) as Mongoose instance methods directly on the model.",
      "objective": "Design cohesive Mongoose schemas with validation, indexes, and virtual fields.",
      "expectedOutcome": "Robust data models enforcing schema integrity at the database layer.",
      "codeSnippet": "// models/order.model.js\nimport mongoose from \"mongoose\";\n\nconst orderSchema = new mongoose.Schema({\n  user: { type: mongoose.Schema.Types.ObjectId, ref: \"User\", required: true },\n  items: [{\n    product: { type: mongoose.Schema.Types.ObjectId, ref: \"Product\" },\n    quantity: { type: Number, default: 1 },\n    price: Number,\n  }],\n  totalAmount: { type: Number, required: true },\n  status: {\n    type: String,\n    enum: [\"pending\", \"processing\", \"shipped\", \"delivered\", \"cancelled\"],\n    default: \"pending\",\n  },\n}, { timestamps: true });\n\norderSchema.index({ user: 1, createdAt: -1 });\n\nexport const Order = mongoose.model(\"Order\", orderSchema);"
    },
    {
      "id": "M27-06",
      "number": "06",
      "title": "Middleware",
      "khmerTitle": "តួនាទី និងការរៀបចំ Middleware Layer (Auth, Guard, Logging)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Middleware functions execute during the lifecycle of an HTTP request before the controller is reached. They handle cross-cutting concerns: authenticating tokens, verifying role permissions, logging requests, parsing body limits, and catching uncaught exceptions in global error handlers.",
      "tip": "Keep middleware focused on a single responsibility. Create separate middleware for authentication (`protect`) and role checking (`restrictTo`) rather than combining them.",
      "objective": "Organize reusable Express middleware for security, logging, and access control.",
      "expectedOutcome": "Modular middleware pipeline intercepting and validating requests cleanly.",
      "codeSnippet": "// middleware/logger.middleware.js\nexport const requestLogger = (req, res, next) => {\n  const start = Date.now();\n  res.on(\"finish\", () => {\n    const duration = Date.now() - start;\n    console.log(`[${req.method}] ${req.originalUrl} ${res.statusCode} - ${duration}ms`);\n  });\n  next();\n};"
    },
    {
      "id": "M27-07",
      "number": "07",
      "title": "Validators",
      "khmerTitle": "តួនាទី និងការរៀបចំ Validators Layer (Zod Schemas)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The Validators layer houses Zod or Joi schemas defining the contract for every incoming request body, query parameter, and route parameter. Grouping validation schemas into dedicated files keeps controllers clean and allows schemas to be reused across API endpoints and tests.",
      "tip": "Name validation schemas descriptively: `createProductSchema`, `updateProductSchema`, `queryProductsSchema`.",
      "objective": "Define structured request validation schemas separate from route handlers.",
      "expectedOutcome": "Clear, declarative data contracts isolating validation logic.",
      "codeSnippet": "// validators/product.validator.js\nimport { z } from \"zod\";\n\nexport const createProductSchema = z.object({\n  body: z.object({\n    title: z.string().min(3).max(100),\n    price: z.number().positive(),\n    category: z.string().min(1),\n    stock: z.number().int().nonnegative().default(0),\n  }),\n});"
    },
    {
      "id": "M27-08",
      "number": "08",
      "title": "Utils",
      "khmerTitle": "ការរៀបចំ Shared Utilities និង Helper Functions",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The Utils directory contains generic, reusable helper functions and classes that are domain-independent. Typical utilities include the `AppError` class, async handler wrappers (`catchAsync`), date formatters, cryptographic helpers, and string transformers.",
      "tip": "Only place functions in `utils/` if they are pure and have no direct dependency on database models or business rules.",
      "objective": "Build a shared utility toolbox for error handling, formatting, and async flow.",
      "expectedOutcome": "Clean, tested utility functions eliminating duplicate code across the project.",
      "codeSnippet": "// utils/catchAsync.js\n// Wraps async route handlers to catch rejected promises and forward to next(err)\nexport const catchAsync = (fn) => (req, res, next) => {\n  Promise.resolve(fn(req, res, next)).catch(next);\n};\n\n// utils/AppError.js\nexport class AppError extends Error {\n  constructor(message, statusCode) {\n    super(message);\n    this.statusCode = statusCode;\n    this.status = `${statusCode}`.startsWith(\"4\") ? \"fail\" : \"error\";\n    this.isOperational = true;\n    Error.captureStackTrace(this, this.constructor);\n  }\n}"
    },
    {
      "id": "M27-09",
      "number": "09",
      "title": "Config",
      "khmerTitle": "ការគ្រប់គ្រង Centralized Configuration និង Environment Validation",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The Config directory centralizes application settings and environment variables. Instead of scattering `process.env.VAR` references across dozens of files, a central `config/env.js` file reads, validates (via Zod), and exports typed configuration objects, failing fast at startup if any critical secret is missing.",
      "tip": "Validate your environment variables with Zod at startup so the server crashes immediately with a clear error message rather than failing mysteriously hours later.",
      "objective": "Centralize and validate all application configuration parameters.",
      "expectedOutcome": "Fail-fast configuration management preventing runtime crashes from missing environment variables.",
      "codeSnippet": "// config/env.js\nimport { z } from \"zod\";\n\nconst envSchema = z.object({\n  NODE_ENV: z.enum([\"development\", \"production\", \"test\"]).default(\"development\"),\n  PORT: z.coerce.number().default(5000),\n  MONGODB_URI: z.string().url(),\n  JWT_ACCESS_SECRET: z.string().min(32),\n  REDIS_URL: z.string().default(\"redis://localhost:6379\"),\n});\n\nconst parsed = envSchema.safeParse(process.env);\nif (!parsed.success) {\n  console.error(\"Invalid environment variables:\", parsed.error.format());\n  process.exit(1); // Fail fast!\n}\n\nexport const env = parsed.data;"
    },
    {
      "id": "M27-10",
      "number": "10",
      "title": "Database",
      "khmerTitle": "ការរៀបចំ Database Connection Pool និង Lifecycle Hooks",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The Database configuration module manages the MongoDB connection lifecycle. It configures connection pooling (`maxPoolSize`), handles initial connect attempts with retries, and registers event listeners for disconnects, reconnections, and errors.",
      "tip": "Set `maxPoolSize: 50` in Mongoose connection options for high-traffic servers to handle concurrent queries efficiently without socket starvation.",
      "objective": "Build a resilient MongoDB connection module with pooling and lifecycle logging.",
      "expectedOutcome": "Robust database connection singleton with auto-reconnect resilience.",
      "codeSnippet": "// config/database.js\nimport mongoose from \"mongoose\";\n\nexport const connectDatabase = async (uri) => {\n  try {\n    const conn = await mongoose.connect(uri, {\n      maxPoolSize: 50, // Connection pool size\n      serverSelectionTimeoutMS: 5000,\n      socketTimeoutMS: 45000,\n    });\n    console.log(`MongoDB Connected: ${conn.connection.host}`);\n  } catch (err) {\n    console.error(\"MongoDB Connection Error:\", err.message);\n    process.exit(1);\n  }\n};\n\nmongoose.connection.on(\"disconnected\", () => console.warn(\"MongoDB disconnected!\"));\nmongoose.connection.on(\"reconnected\", () => console.log(\"MongoDB reconnected!\"));"
    },
    {
      "id": "M27-11",
      "number": "11",
      "title": "Jobs",
      "khmerTitle": "ការរៀបចំ Jobs Directory សម្រាប់ Background Queues និង Workers",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The Jobs directory groups queue definitions, job producers, and worker processors. Keeping job definitions organized by domain (e.g. `jobs/email.job.js`, `jobs/report.job.js`) provides clear separation between scheduled cron tasks and transactional queue processing.",
      "tip": "Separate your worker startup script (`npm run worker`) from your web server startup (`npm start`) so they can run in isolated Docker containers.",
      "objective": "Organize background queue producers and worker processors into dedicated job modules.",
      "expectedOutcome": "Structured background task architecture supporting independent worker scaling.",
      "codeSnippet": "src/jobs/\n├── index.js          # Initializes all queues and workers\n├── email/\n│   ├── email.queue.js   # Queue initialization & producer helpers\n│   └── email.worker.js  # Worker logic processing email delivery\n└── reports/\n    ├── report.queue.js\n    └── report.worker.js"
    },
    {
      "id": "M27-12",
      "number": "12",
      "title": "Tests",
      "khmerTitle": "ការរៀបចំ Tests Directory (Unit, Integration, E2E)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Structuring tests into `unit/` (testing pure services and utilities in memory) and `integration/` (testing full HTTP routes with Supertest and MongoDB Memory Server) ensures quick test execution during development and comprehensive test coverage before production deployments.",
      "tip": "Keep unit tests fast (<1s total) so developers run them continuously on every file save.",
      "objective": "Structure scalable test directories separating fast unit tests from comprehensive integration suites.",
      "expectedOutcome": "Organized test suites matching the backend folder architecture.",
      "codeSnippet": "tests/\n├── setup.js            # Vitest global setup (in-memory MongoDB)\n├── helpers/            # getAuthToken(), createTestUser()\n├── unit/               # Fast, mocked tests\n│   ├── services/\n│   └── utils/\n└── integration/        # Route & HTTP tests\n    ├── auth.test.js\n    └── products.test.js"
    },
    {
      "id": "M27-13",
      "number": "13",
      "title": "Documentation",
      "khmerTitle": "ការរៀបចំឯកសារគម្រោង (README, ARCHITECTURE, OpenAPI)",
      "type": "architecture",
      "codeLanguage": "markdown",
      "summary": "Professional codebases include standard documentation: a `README.md` with setup and environment instructions, an `ARCHITECTURE.md` explaining data flow and module responsibilities, and an OpenAPI contract (`swagger.json`). This ensures frictionless onboarding for new engineers.",
      "tip": "Include a one-line 'Quick Start' in your README with Docker Compose commands so new developers can boot the entire stack in under 2 minutes.",
      "objective": "Author comprehensive project documentation covering setup, architecture, and deployment.",
      "expectedOutcome": "Professional documentation guiding new team members through local setup and design decisions.",
      "codeSnippet": "# Project Documentation Standards:\n# ├── README.md        -> Installation, environment setup, npm scripts\n# ├── ARCHITECTURE.md  -> Layer diagrams, data flow, external service dependencies\n# ├── CONTRIBUTING.md  -> Git branch naming conventions, PR guidelines, lint checks\n# └── /docs/           -> Swagger JSON specs, Postman collections, database schemas"
    },
    {
      "id": "M27-14",
      "number": "14",
      "title": "Environment Configuration",
      "khmerTitle": "ការគ្រប់គ្រងបរិស្ថាន Development, Staging, Production",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Applications behave differently across environments: development enables verbose error traces and mock SMTP servers; staging mirrors production configuration against isolated test databases; production enforces strict SSL, rate limiting, and structured JSON logging.",
      "tip": "Never conditionally check `if (env === 'dev')` everywhere in code. Instead, define an environment configuration matrix that supplies environment-specific constants cleanly.",
      "objective": "Architect multi-stage environment configurations with environment-specific behaviors.",
      "expectedOutcome": "Clean environment segregation without hardcoded stage checks.",
      "codeSnippet": "// config/environments.js\nconst configs = {\n  development: {\n    logLevel: \"debug\",\n    corsOrigin: \"http://localhost:3000\",\n    emailService: \"mailtrap\",\n  },\n  production: {\n    logLevel: \"error\",\n    corsOrigin: \"https://myenterprise.com\",\n    emailService: \"sendgrid\",\n  },\n};\n\nexport const currentConfig = configs[process.env.NODE_ENV || \"development\"];"
    },
    {
      "id": "M27-15",
      "number": "15",
      "title": "Scalable Backend Architecture",
      "khmerTitle": "ស្ថាបត្យកម្ម Scalable Backend កម្រិត Enterprise (Full Architecture Blueprint)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "An enterprise-grade scalable backend unites the layered architecture: Nginx reverse proxy load balancer -> stateless Express API servers (clustered horizontally) -> Redis caching & queue layer -> MongoDB database cluster with replica sets. Background workers scale independently to handle async tasks without consuming API web server resources.",
      "tip": "Design your Express servers to be 100% stateless — store no session data in local server RAM. This allows you to add or remove servers behind a load balancer with zero user disruption.",
      "objective": "Synthesize all backend layers into an enterprise-scale architecture blueprint.",
      "expectedOutcome": "Production-ready, highly available, and scalable backend architecture design.",
      "codeSnippet": "// Enterprise High-Availability Topology:\n//\n//              [Client Browser / Mobile App]\n//                           │ (HTTPS)\n//                           ↓\n//                [Nginx Reverse Proxy / CDN]\n//                           │\n//            ┌──────────────┴──────────────┐\n//            ↓ (Round-Robin)               ↓\n//   [Node.js API Server 1]       [Node.js API Server 2]\n//            │                             │\n//            ├──────────────┬──────────────┤\n//            ↓              ↓              ↓\n//    [Redis Cache]   [BullMQ Queue]   [MongoDB Replica Set]\n//                           │\n//                           ↓\n//                [Background Worker Nodes]"
    }
  ],
  "M28": [
    {
      "id": "M28-01",
      "number": "01",
      "title": "Development vs Production",
      "khmerTitle": "ភាពខុសគ្នារវាងបរិស្ថាន Development និង Production",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Development environments prioritize developer velocity: hot-reloading (nodemon/tsx), detailed error stack traces, mock SMTP inboxes, and verbose console logs. Production environments prioritize security, uptime, performance, and fault tolerance: optimized minified builds, structured JSON logging, strict CORS, HTTPS encryption, and sanitized error envelopes.",
      "tip": "Set `NODE_ENV=production` on production servers — Express and many packages automatically enable performance caching and suppress leaking internal stack traces when this flag is set.",
      "objective": "Contrast operational requirements between development and production environments.",
      "expectedOutcome": "Clear strategy for environment-dependent performance and security behaviors.",
      "codeSnippet": "// Key Differences:\n// Setting                | Development            | Production\n// -----------------------+------------------------+--------------------------\n// NODE_ENV               | \"development\"          | \"production\"\n// Error Responses        | Full stack trace       | Generic \"Something went wrong\"\n// Server Process         | nodemon / tsx watch    | PM2 cluster / Docker container\n// Logging                | Pretty console output  | Structured JSON (Winston/Pino)\n// HTTPS                  | Disabled (http://)     | Enforced (SSL/TLS certificate)"
    },
    {
      "id": "M28-02",
      "number": "02",
      "title": "Environment Variables",
      "khmerTitle": "ការគ្រប់គ្រង Environment Variables ក្នុង Production",
      "type": "lab",
      "codeLanguage": "bash",
      "summary": "In production, environment variables should be injected directly by the hosting platform (Docker environment flags, Kubernetes secrets, or VPS systemd environment configurations) rather than read from physical `.env` files on disk. This prevents secrets from persisting in container images or leaking via file permissions.",
      "tip": "Never commit `.env` files into Docker images or Git repositories. Use Docker Compose `environment:` or pass `--env-file` at runtime.",
      "objective": "Inject production environment variables securely via container runtimes and VPS environments.",
      "expectedOutcome": "Secure credential management without plaintext files in images or repositories.",
      "codeSnippet": "# 1. Passing env vars to Docker container at runtime:\ndocker run -d   -p 5000:5000   -e NODE_ENV=production   -e MONGODB_URI=\"mongodb+srv://admin:secret@cluster.mongodb.net/prod\"   --name my-api   my-enterprise-api:latest\n\n# 2. Or using Docker Compose secrets / env_file:\n# docker compose --env-file .env.production up -d"
    },
    {
      "id": "M28-03",
      "number": "03",
      "title": "Production Configuration",
      "khmerTitle": "ការកំណត់រចនាសម្ព័ន្ធ Production (Graceful Shutdown & Keep-Alive)",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "Production configuration requires handling process signals like `SIGTERM` and `SIGINT` gracefully. When a server restarts or redeploys, a graceful shutdown handler stops accepting new HTTP requests, waits for in-flight requests to complete, flushes background queues, closes database connection pools, and exits cleanly.",
      "tip": "Implement a 10-second timeout on graceful shutdown: if pending requests do not complete within 10 seconds, force exit (`process.exit(1)`) to avoid hanging deployments.",
      "objective": "Implement graceful shutdown handlers for zero-downtime rolling deployments.",
      "expectedOutcome": "Clean shutdown mechanics preserving in-flight transactions during redeployment.",
      "codeSnippet": "// Graceful Shutdown Implementation:\nconst server = app.listen(PORT, () => console.log(`Listening on port ${PORT}`));\n\nconst handleShutdown = async (signal) => {\n  console.log(`Received ${signal}. Starting graceful shutdown...`);\n  \n  // 1. Stop accepting new HTTP requests\n  server.close(async () => {\n    console.log(\"HTTP server closed.\");\n\n    try {\n      // 2. Disconnect from database and cache\n      await mongoose.connection.close();\n      await redis.quit();\n      console.log(\"Database and Redis connections closed.\");\n      process.exit(0);\n    } catch (err) {\n      console.error(\"Error during graceful shutdown:\", err);\n      process.exit(1);\n    }\n  });\n\n  // Force exit after 10s if connections hang\n  setTimeout(() => {\n    console.error(\"Forced shutdown after 10s timeout\");\n    process.exit(1);\n  }, 10000);\n};\n\nprocess.on(\"SIGTERM\", () => handleShutdown(\"SIGTERM\"));\nprocess.on(\"SIGINT\", () => handleShutdown(\"SIGINT\"));"
    },
    {
      "id": "M28-04",
      "number": "04",
      "title": "Logging",
      "khmerTitle": "ការកត់ត្រា Logs ប្រកបដោយស្តង់ដារជាមួយ Winston ឬ Pino",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "In production, `console.log()` is synchronous and can block the event loop under heavy throughput. Structured logging libraries like `pino` or `winston` output logs as machine-readable JSON strings formatted with timestamps, log levels (info, warn, error), request IDs, and context metadata for indexing in Datadog, ELK, or Logstash.",
      "tip": "Use `pino` for maximum performance — it is up to 5x faster than Winston and produces minimal CPU overhead under heavy traffic.",
      "objective": "Configure structured JSON logging with request tracing and error diagnostics.",
      "expectedOutcome": "High-performance structured logs ready for cloud log aggregator indexing.",
      "codeSnippet": "import pino from \"pino\";\n\nexport const logger = pino({\n  level: process.env.LOG_LEVEL || \"info\",\n  timestamp: pino.stdTimeFunctions.isoTime,\n  formatters: {\n    level: (label) => ({ level: label.toUpperCase() }),\n  },\n});\n\n// Usage across application:\n// logger.info({ userId: \"123\", action: \"ORDER_PLACED\" }, \"User completed purchase\");\n// logger.error({ err, route: \"/checkout\" }, \"Payment gateway timeout\");"
    },
    {
      "id": "M28-05",
      "number": "05",
      "title": "Process Management",
      "khmerTitle": "គោលការណ៍ Process Management ក្នុង Node.js (Cluster & Crash Recovery)",
      "type": "concept",
      "codeLanguage": "javascript",
      "summary": "Because Node.js runs on a single CPU core by default, a server with 8 CPU cores utilizes only 12.5% of available computing power unless clustered. Process managers fork multiple worker instances across all CPU cores, balance incoming network sockets across workers, and automatically restart crashed processes instantly.",
      "tip": "In modern containerized architectures (Docker/Kubernetes), run one Node.js process per container and scale container replicas via Kubernetes rather than using in-process clustering.",
      "objective": "Understand process clustering, auto-restart mechanics, and resource utilization.",
      "expectedOutcome": "Knowledge of multi-core scaling strategies for Node.js backends.",
      "codeSnippet": "// Node.js Multi-Core Utilization:\n// Single Process:      1 Node Process -> Utilizes 1 Core (3 Cores idle on quad-core VPS!)\n// Clustered (PM2/OS):  4 Node Processes -> Utilizes 100% of Quad-Core CPU!\n//\n// Load Balancer distributes requests across workers automatically."
    },
    {
      "id": "M28-06",
      "number": "06",
      "title": "PM2",
      "khmerTitle": "ការគ្រប់គ្រង Server Process ជាមួយ PM2 Cluster Mode",
      "type": "lab",
      "codeLanguage": "bash",
      "summary": "PM2 is the production process manager for Node.js. It features zero-downtime reloads, built-in cluster mode (`-i max` to spawn a worker per CPU core), automated startup on VPS system reboot, and real-time CPU/memory monitoring.",
      "tip": "Create an `ecosystem.config.cjs` file to define PM2 settings, environment variables, and log file paths in version control.",
      "objective": "Deploy, manage, and monitor Node.js applications using PM2 in cluster mode.",
      "expectedOutcome": "Self-healing Node.js application running in clustered production mode.",
      "codeSnippet": "# Start application in Cluster mode across all CPU cores:\npm2 start src/server.js -i max --name \"enterprise-api\"\n\n# Useful PM2 commands:\npm2 status          # View status, memory, CPU of all instances\npm2 logs            # Stream real-time logs\npm2 monit           # Visual interactive terminal dashboard\npm2 reload all      # Zero-downtime rolling reload!\npm2 startup         # Configure auto-start on VPS server reboot"
    },
    {
      "id": "M28-07",
      "number": "07",
      "title": "Docker",
      "khmerTitle": "គោលការណ៍គ្រឹះនៃ Containerization ជាមួយ Docker",
      "type": "concept",
      "codeLanguage": "dockerfile",
      "summary": "Docker containerizes applications by bundling backend source code, runtime dependencies, system libraries, and configurations into lightweight, standalone executable images. This guarantees identical behavior across development machines, CI runners, and production cloud servers ('works on my machine' eliminated permanently).",
      "tip": "Containers are lightweight compared to Virtual Machines: they share the host OS kernel and boot in milliseconds with minimal memory overhead.",
      "objective": "Understand containerization principles: images, containers, volumes, and networks.",
      "expectedOutcome": "Conceptual foundation for containerized application delivery.",
      "codeSnippet": "// Virtual Machine vs Docker Container:\n// VM:         [App] -> [Bins/Libs] -> [Guest OS (GBs)] -> [Hypervisor] -> [Host OS]\n// Container:  [App] -> [Bins/Libs] -> [Docker Engine]  -> [Host OS Kernel]\n// Result: Containers boot in 1 second and consume megabytes rather than gigabytes."
    },
    {
      "id": "M28-08",
      "number": "08",
      "title": "Dockerfile",
      "khmerTitle": "ការបង្កើត Multi-stage Dockerfile សម្រាប់ Node.js",
      "type": "lab",
      "codeLanguage": "dockerfile",
      "summary": "A production Dockerfile uses multi-stage builds to separate the build phase (compiling TypeScript, installing devDependencies) from the final production runtime. Multi-stage builds produce tiny, secure container images (<150MB) containing only production dependencies and compiled JavaScript.",
      "tip": "Always copy `package*.json` and run `npm ci` BEFORE copying source code — this leverages Docker layer caching so subsequent builds take 2 seconds instead of reinstalling dependencies.",
      "objective": "Author an optimized, secure multi-stage Dockerfile for Node.js backends.",
      "expectedOutcome": "Minimal, secure production Docker image with layer caching.",
      "codeSnippet": "# Stage 1: Build & Dependencies\nFROM node:20-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm ci\nCOPY . .\n\n# Stage 2: Production Runtime\nFROM node:20-alpine AS runner\nWORKDIR /app\nENV NODE_ENV=production\n# Run as non-root user for security\nUSER node\nCOPY --chown=node:node package*.json ./\nRUN npm ci --only=production\nCOPY --chown=node:node --from=builder /app/src ./src\n\nEXPOSE 5000\nCMD [\"node\", \"src/server.js\"]"
    },
    {
      "id": "M28-09",
      "number": "09",
      "title": "Docker Compose",
      "khmerTitle": "ការរៀបចំ Multi-Container Stack ជាមួយ Docker Compose",
      "type": "lab",
      "codeLanguage": "yaml",
      "summary": "Docker Compose coordinates multi-container environments (Node.js API, MongoDB, Redis, Nginx) defined in a single `docker-compose.yml` file. A single command (`docker compose up -d`) creates isolated internal networks, mounts storage volumes, and boots the entire application stack.",
      "tip": "Use named volumes for database storage (`volumes: - mongodb_data:/data/db`) so database records survive container restarts and updates.",
      "objective": "Define and orchestrate multi-container application stacks using Docker Compose.",
      "expectedOutcome": "One-command local environment bootstrapping Node.js, MongoDB, and Redis.",
      "codeSnippet": "version: \"3.8\"\n\nservices:\n  api:\n    build: .\n    ports:\n      - \"5000:5000\"\n    environment:\n      - NODE_ENV=production\n      - MONGODB_URI=mongodb://mongo:27017/app_prod\n      - REDIS_URL=redis://redis:6379\n    depends_on:\n      - mongo\n      - redis\n\n  mongo:\n    image: mongo:7-jammy\n    restart: always\n    volumes:\n      - mongo_data:/data/db\n\n  redis:\n    image: redis:alpine\n    restart: always\n\nvolumes:\n  mongo_data:"
    },
    {
      "id": "M28-10",
      "number": "10",
      "title": "Node.js Container",
      "khmerTitle": "ការ Build និង Run Node.js Production Container",
      "type": "lab",
      "codeLanguage": "bash",
      "summary": "Building and executing a production container requires building the image (`docker build -t my-api .`), tagging with a version tag, running with memory limits (`--memory=512m`), and passing environment variables via secret managers or environment files.",
      "tip": "Always enforce container memory limits (`--memory=512m`) to prevent a runaway memory leak from starving the host OS.",
      "objective": "Build, tag, run, and inspect production Node.js containers from the command line.",
      "expectedOutcome": "Operational Node.js container executing with resource boundaries.",
      "codeSnippet": "# 1. Build image\ndocker build -t enterprise-api:1.0.0 .\n\n# 2. Run container with restart policy and memory boundaries\ndocker run -d   --name enterprise-api-prod   -p 5000:5000   --memory=\"512m\"   --restart unless-stopped   enterprise-api:1.0.0\n\n# 3. View container health and logs\ndocker ps\ndocker logs -f enterprise-api-prod"
    },
    {
      "id": "M28-11",
      "number": "11",
      "title": "MongoDB Container",
      "khmerTitle": "ការរៀបចំ MongoDB Container ជាមួយ Persistent Volumes",
      "type": "lab",
      "codeLanguage": "bash",
      "summary": "Running MongoDB in Docker requires persistent volumes to store database files permanently on host disk. Without volumes, deleting or updating the MongoDB container permanently destroys all database records. Configuring root authentication credentials ensures database security inside the container network.",
      "tip": "Always configure `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD` when booting MongoDB containers.",
      "objective": "Deploy MongoDB inside a Docker container with persistent storage volumes and authentication.",
      "expectedOutcome": "Persistent, secure containerized database ready for application connections.",
      "codeSnippet": "# Run MongoDB with persistent named volume and authentication:\ndocker run -d   --name production-mongo   -p 27017:27017   -v mongo_data:/data/db   -e MONGO_INITDB_ROOT_USERNAME=admin   -e MONGO_INITDB_ROOT_PASSWORD=SuperSecretPassword123!   --restart always   mongo:7-jammy"
    },
    {
      "id": "M28-12",
      "number": "12",
      "title": "Redis Container",
      "khmerTitle": "ការរៀបចំ Redis Container សម្រាប់ Caching និង Queues",
      "type": "lab",
      "codeLanguage": "bash",
      "summary": "Deploying Redis via Docker provides an instant in-memory cache and queue engine. Configuring a password (`requirepass`), enabling AOF persistence (`--appendonly yes`), and attaching a data volume ensures Redis state survives restarts.",
      "tip": "Always append `--appendonly yes` to your Redis container command to ensure job queues persist across host reboots.",
      "objective": "Deploy an authenticated Redis container with persistent append-only storage.",
      "expectedOutcome": "Secure, durable Redis cache container ready for BullMQ and session caching.",
      "codeSnippet": "# Run authenticated Redis container with AOF persistence:\ndocker run -d   --name production-redis   -p 6379:6379   -v redis_data:/data   --restart always   redis:alpine   redis-server --appendonly yes --requirepass \"RedisSecurePassword2026!\""
    },
    {
      "id": "M28-13",
      "number": "13",
      "title": "Nginx",
      "khmerTitle": "ការស្វែងយល់ពីតួនាទីរបស់ Nginx ក្នុង Production Architecture",
      "type": "concept",
      "codeLanguage": "nginx",
      "summary": "Nginx is a high-performance HTTP web server and reverse proxy. Sitting between the public internet and your Node.js API, Nginx handles SSL/TLS termination, HTTP request routing, static file caching, client payload buffering, and Gzip compression, shielding Node.js from slow clients and DoS floods.",
      "tip": "Never expose Node.js directly to public port 80/443 in production. Always place Nginx or Cloudflare in front as a reverse proxy.",
      "objective": "Understand the architectural benefits of Nginx reverse proxying in front of Node.js.",
      "expectedOutcome": "Clear rationale for reverse proxy architecture separating web tier from application tier.",
      "codeSnippet": "// Architecture Flow:\n// [Public Internet Client] (HTTPS Port 443)\n//           │\n//           ↓\n// [Nginx Reverse Proxy]\n//   ├── Terminates SSL / TLS encryption\n//   ├── Serves static assets directly (/public)\n//   ├── Buffers slow client uploads\n//   └── Proxies clean requests via internal network -> [Node.js Express (Port 5000)]"
    },
    {
      "id": "M28-14",
      "number": "14",
      "title": "Reverse Proxy",
      "khmerTitle": "ការកំណត់រចនាសម្ព័ន្ធ Nginx Reverse Proxy (nginx.conf)",
      "type": "architecture",
      "codeLanguage": "nginx",
      "summary": "Configuring Nginx as a reverse proxy forwards HTTP requests to your Node.js backend using `proxy_pass`. Nginx preserves client IP addresses via `X-Forwarded-For` and `X-Real-IP` headers so Express rate limiters and loggers receive actual client IPs.",
      "tip": "Set `app.set('trust proxy', 1)` in Express when behind Nginx so `req.ip` correctly reads the forwarded client IP.",
      "objective": "Write an Nginx configuration file proxying traffic to an Express upstream server.",
      "expectedOutcome": "Production Nginx reverse proxy configuration passing client headers accurately.",
      "codeSnippet": "server {\n    listen 80;\n    server_name api.myenterprise.com;\n\n    location / {\n        proxy_pass http://127.0.0.1:5000;\n        proxy_http_version 1.1;\n        proxy_set_header Upgrade $http_upgrade;\n        proxy_set_header Connection 'upgrade';\n        proxy_set_header Host $host;\n        proxy_set_header X-Real-IP $remote_addr;\n        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $scheme;\n        proxy_cache_bypass $http_upgrade;\n    }\n}"
    },
    {
      "id": "M28-15",
      "number": "15",
      "title": "HTTPS",
      "khmerTitle": "ការដំឡើង HTTPS / SSL ដោយឥតគិតថ្លៃជាមួយ Certbot & Let's Encrypt",
      "type": "lab",
      "codeLanguage": "bash",
      "summary": "HTTPS encrypts network traffic between browser and server, preventing eavesdropping and man-in-the-middle attacks. Let's Encrypt provides free SSL certificates, and Certbot automates certificate issuance, Nginx SSL configuration, and automated 90-day renewals.",
      "tip": "Certbot installs a systemd timer that automatically renews your SSL certificate before expiration — test renewals with `certbot renew --dry-run`.",
      "objective": "Provision free Let's Encrypt SSL certificates and enforce HTTPS redirects via Certbot.",
      "expectedOutcome": "A+ rated SSL configuration with automatic certificate renewals.",
      "codeSnippet": "# 1. Install Certbot for Nginx on Ubuntu:\nsudo apt update\nsudo apt install certbot python3-certbot-nginx -y\n\n# 2. Automatically obtain and configure SSL in Nginx:\nsudo certbot --nginx -d api.myenterprise.com\n\n# 3. Test automated certificate renewal:\nsudo certbot renew --dry-run"
    },
    {
      "id": "M28-16",
      "number": "16",
      "title": "VPS Deployment",
      "khmerTitle": "ការរៀបចំ និងដាក់ឱ្យដំណើរការលើ Virtual Private Server (VPS)",
      "type": "lab",
      "codeLanguage": "bash",
      "summary": "Deploying to a Virtual Private Server (VPS from DigitalOcean, Linode, AWS EC2, or Hetzner) gives total root control over your hosting infrastructure. The workflow involves provisioning an Ubuntu server, configuring SSH key authentication, setting up firewalls (UFW), installing Docker, and pulling application images.",
      "tip": "Always disable password authentication in `/etc/ssh/sshd_config` (`PasswordAuthentication no`) and use SSH keys exclusively to protect against SSH brute-force attacks.",
      "objective": "Provision, secure, and deploy a containerized backend on a live cloud VPS.",
      "expectedOutcome": "Live production server reachable at a public IP/domain running your backend.",
      "codeSnippet": "# 1. Connect to VPS via SSH Key:\nssh -i ~/.ssh/id_ed25519 deploy@your-server-ip\n\n# 2. Configure Uncomplicated Firewall (UFW):\nsudo ufw default deny incoming\nsudo ufw default allow outgoing\nsudo ufw allow ssh        # Port 22\nsudo ufw allow http       # Port 80\nsudo ufw allow https      # Port 443\nsudo ufw enable"
    },
    {
      "id": "M28-17",
      "number": "17",
      "title": "Ubuntu Server",
      "khmerTitle": "ការរៀបចំ Ubuntu Server (Security Hardening & Swap Memory)",
      "type": "lab",
      "codeLanguage": "bash",
      "summary": "Securing an Ubuntu server requires creating a non-root user with `sudo` privileges, configuring automatic security updates via `unattended-upgrades`, and creating a Swap memory file to prevent Out-Of-Memory (OOM) kernel kills on entry-level 1GB/2GB RAM cloud servers.",
      "tip": "Add a 2GB Swap file on 1GB/2GB VPS instances — this prevents the Linux kernel from killing Node.js when memory spikes during builds.",
      "objective": "Harden an Ubuntu server and configure Swap memory for resource resilience.",
      "expectedOutcome": "Hardened Ubuntu server resistant to OOM kernel termination.",
      "codeSnippet": "# Create a 2GB Swap File on Ubuntu:\nsudo fallocate -l 2G /swapfile\nsudo chmod 600 /swapfile\nsudo mkswap /swapfile\nsudo swapon /swapfile\n\n# Make swap permanent across reboots:\necho '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab\n\n# Verify swap active:\nfree -h"
    },
    {
      "id": "M28-18",
      "number": "18",
      "title": "CI/CD",
      "khmerTitle": "គោលការណ៍ Continuous Integration & Continuous Deployment",
      "type": "concept",
      "codeLanguage": "yaml",
      "summary": "Continuous Integration (CI) automatically builds and tests code on every Git commit or pull request. Continuous Deployment (CD) automatically pushes passing code to staging or production servers without manual intervention. CI/CD catches regressions early and shortens delivery cycles from weeks to minutes.",
      "tip": "Require all CI checks (linting, TypeScript check, unit tests) to pass before permitting pull request merges to the `main` branch.",
      "objective": "Understand the CI/CD pipeline lifecycle from commit to production deployment.",
      "expectedOutcome": "Familiarity with automated testing, building, and deployment workflows.",
      "codeSnippet": "// Modern CI/CD Pipeline Lifecycle:\n//\n// 1. Developer pushes commit to 'main'\n// 2. GitHub Actions CI triggers automatically:\n//    ├── Runs ESLint check\n//    ├── Runs TypeScript check (tsc --noEmit)\n//    ├── Runs Vitest automated test suite\n//    └── Builds Docker image\n// 3. CD step deploys passing container to VPS / Cloud via SSH / Webhook\n// 4. Zero-downtime rolling update completes in under 2 minutes!"
    },
    {
      "id": "M28-19",
      "number": "19",
      "title": "GitHub Actions",
      "khmerTitle": "ការបង្កើត GitHub Actions Workflow សម្រាប់ Test និង Auto-deploy",
      "type": "lab",
      "codeLanguage": "yaml",
      "summary": "GitHub Actions automates your software workflows directly within your GitHub repository. A `.github/workflows/deploy.yml` file defines automated triggers (`push: branches: [main]`), spins up Ubuntu runners, executes tests, builds Docker images, and deploys the passing image to your VPS over SSH.",
      "tip": "Store sensitive deployment credentials (SSH private keys, Docker tokens) securely in GitHub Repository Secrets (`Settings -> Secrets and variables -> Actions`).",
      "objective": "Author an automated GitHub Actions workflow running tests and deploying to a server.",
      "expectedOutcome": "Automated pipeline that tests and deploys code on every push to main.",
      "codeSnippet": "name: CI/CD Pipeline\n\non:\n  push:\n    branches: [main]\n\njobs:\n  test-and-deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n          cache: \"npm\"\n\n      - run: npm ci\n      - run: npm run test:run\n\n      - name: Deploy to VPS over SSH\n        uses: appleboy/ssh-action@master\n        with:\n          host: ${{ secrets.VPS_HOST }}\n          username: ${{ secrets.VPS_USER }}\n          key: ${{ secrets.VPS_SSH_KEY }}\n          script: |\n            cd /opt/enterprise-app\n            git pull origin main\n            docker compose down\n            docker compose up -d --build"
    },
    {
      "id": "M28-20",
      "number": "20",
      "title": "Production Checklist",
      "khmerTitle": "បញ្ជីត្រួតពិនិត្យចុងក្រោយមុនពេល Launch (Production Go-Live Checklist)",
      "type": "architecture",
      "codeLanguage": "markdown",
      "summary": "Before launching an API to real users, engineers must verify a comprehensive production checklist. This covers environment secrets validation, database indexes, rate limiting, error logging to external tools (Sentry), automated backups, SSL encryption, and health checks.",
      "tip": "Always create an automated daily MongoDB backup cron job (`mongodump`) and upload archives to S3/R2 before opening your application to public users.",
      "objective": "Execute a thorough production readiness audit ensuring zero launch gaps.",
      "expectedOutcome": "Rock-solid, audit-verified backend ready for real-world enterprise traffic.",
      "codeSnippet": "## Enterprise Production Go-Live Checklist:\n- [ ] 1. Security: Helmet headers active & X-Powered-By removed\n- [ ] 2. CORS: Explicit origin whitelisting configured (No wildcard '*')\n- [ ] 3. Secrets: All passwords & JWT secrets have 32+ bytes entropy in env\n- [ ] 4. Database: Compound indexes created & query latency verified with explain()\n- [ ] 5. Rate Limiting: Active on all endpoints, strict on auth (/login)\n- [ ] 6. Caching: Redis TTL configured on read-heavy public endpoints\n- [ ] 7. Error Handling: No internal stack traces leaked in 500 responses\n- [ ] 8. Monitoring: Health check route (/health) returning DB + Redis status\n- [ ] 9. Backups: Daily automated database snapshots to Cloud storage (R2/S3)\n- [ ] 10. SSL/TLS: Valid HTTPS certificate with auto-renewal active"
    }
  ],
  "M29": [
    {
      "id": "M29-01",
      "number": "01",
      "title": "Project 01: Todo REST API",
      "khmerTitle": "គម្រោងទី ១ ៖ Todo REST API",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Build a robust Todo REST API with full CRUD functionality, status filtering (?completed=true), search by title, sorting by creation date, pagination with limit and skip, Zod input validation, central error handling, and MongoDB persistence. Teaches fundamental RESTful design principles and clean controller-service architecture.",
      "tip": "Use Promise.all to run the data query and the countDocuments query concurrently — this halves the response time on paginated endpoints.",
      "objective": "Build a production-quality CRUD REST API with filtering, pagination, and validation.",
      "expectedOutcome": "Clean, robust Todo API meeting REST standards and proper HTTP response contracts.",
      "codeSnippet": "// GET /api/v1/todos?completed=true&sort=-createdAt&page=1&limit=10\n\nexport const getTodos = catchAsync(async (req, res) => {\n  const { completed, sort = \"-createdAt\", page = 1, limit = 10 } = req.query;\n  const filter = completed !== undefined ? { completed: completed === \"true\" } : {};\n\n  const [todos, total] = await Promise.all([\n    Todo.find(filter)\n      .sort(sort)\n      .skip((Number(page) - 1) * Number(limit))\n      .limit(Number(limit)),\n    Todo.countDocuments(filter)\n  ]);\n\n  res.json({\n    success: true,\n    count: todos.length,\n    total,\n    page: Number(page),\n    pages: Math.ceil(total / Number(limit)),\n    data: todos\n  });\n});"
    },
    {
      "id": "M29-02",
      "number": "02",
      "title": "Project 02: Student Management API",
      "khmerTitle": "គម្រោងទី ២ ៖ Student Management API ជាមួយ Swagger",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Build a Student Management API with comprehensive CRUD, full-text student search, course enrollment relationships with Mongoose population, grade tracking, Zod schema validation, and complete OpenAPI/Swagger interactive documentation. Demonstrates professional data modeling and interactive documentation.",
      "tip": "Use Mongoose pre-populate middleware on find queries so course details are attached automatically without repeating populate() in every controller.",
      "objective": "Construct an educational records API with relational population and interactive Swagger documentation.",
      "expectedOutcome": "Fully documented Student Management API with relational data integrity.",
      "codeSnippet": "// routes/student.routes.js with OpenAPI annotations\n/**\n * @openapi\n * /api/v1/students:\n *   get:\n *     summary: Retrieve paginated students with course population\n *     tags: [Students]\n *     parameters:\n *       - in: query\n *         name: search\n *         schema:\n *           type: string\n *     responses:\n *       200:\n *         description: List of students\n */\nrouter.get(\"/students\", studentController.getStudents);"
    },
    {
      "id": "M29-03",
      "number": "03",
      "title": "Project 03: Authentication API",
      "khmerTitle": "គម្រោងទី ៣ ៖ Full Auth System ជាមួយ JWT និង HttpOnly Cookies",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Build a complete authentication system: registration with bcrypt hashing, login with dual JWT tokens (short-lived access token + long-lived refresh token in HttpOnly cookie), protected /me endpoint, logout (cookie invalidation and database token cleanup), forgot password with email reset token, and password reset. Serves as the authentication backbone for enterprise projects.",
      "tip": "Test your token expiry logic thoroughly — simulate expired access tokens, cookie-based refresh, and the full re-authentication cycle.",
      "objective": "Implement a complete, production-grade JWT authentication system with dual tokens and cookie security.",
      "expectedOutcome": "Secure authentication API: register, login, refresh, logout, and password recovery.",
      "codeSnippet": "export const login = async ({ email, password }) => {\n  const user = await User.findOne({ email }).select(\"+password\");\n  if (!user || !(await bcrypt.compare(password, user.password))) {\n    throw new AppError(\"Invalid email or password\", 401);\n  }\n  const accessToken = jwt.sign({ userId: user._id, role: user.role }, process.env.JWT_ACCESS_SECRET, { expiresIn: \"15m\" });\n  const refreshToken = jwt.sign({ userId: user._id }, process.env.JWT_REFRESH_SECRET, { expiresIn: \"7d\" });\n  return { user: sanitizeUser(user), accessToken, refreshToken };\n};"
    },
    {
      "id": "M29-04",
      "number": "04",
      "title": "Project 04: Product Management API",
      "khmerTitle": "គម្រោងទី ៤ ៖ E-Commerce Product Catalog API ជាមួយ Caching",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Build a full-featured e-commerce product catalog API with multi-image upload to Cloudflare R2, category management, text search with MongoDB $text indexes, compound indexes for fast query execution, price range filtering, Redis response caching on public endpoints, and RBAC admin guards for write operations.",
      "tip": "Apply the Redis cache-aside pattern on GET /products with a 60-second TTL, and invalidate the cache on every create/update/delete operation.",
      "objective": "Build a complete product catalog API with search, filtering, image uploads, and Redis caching.",
      "expectedOutcome": "High-performance product API with sub-10ms cached responses and admin RBAC.",
      "codeSnippet": "export const getProducts = catchAsync(async (req, res) => {\n  const cacheKey = `products:${JSON.stringify(req.query)}`;\n  const cached = await redis.get(cacheKey);\n  if (cached) return res.json(JSON.parse(cached));\n\n  const products = await Product.find(filter)\n    .sort(sort || \"-createdAt\")\n    .skip((page - 1) * limit).limit(Number(limit))\n    .populate(\"category\", \"name slug\");\n\n  const body = { success: true, count: products.length, data: products };\n  await redis.set(cacheKey, JSON.stringify(body), \"EX\", 60);\n  res.json(body);\n});"
    },
    {
      "id": "M29-05",
      "number": "05",
      "title": "Project 05: E-Commerce Backend",
      "khmerTitle": "គម្រោងទី ៥ ៖ Complete E-Commerce Backend Platform",
      "type": "lab",
      "codeLanguage": "javascript",
      "summary": "Build an end-to-end e-commerce backend platform including user cart management, wishlist, checkout order creation, Stripe payment integration, background email receipts via BullMQ, role-based order management for administrators, and stock inventory decrement with database transactions.",
      "tip": "Use MongoDB multi-document transactions (`session.withTransaction()`) during checkout to ensure stock decrement and order creation succeed or fail together atomically.",
      "objective": "Build an enterprise e-commerce backend with payments, background jobs, and ACID transactions.",
      "expectedOutcome": "Production-ready e-commerce platform orchestrating orders, payments, and background jobs.",
      "codeSnippet": "// Checkout with MongoDB Transaction:\nexport const checkout = async (userId, items) => {\n  const session = await mongoose.startSession();\n  return session.withTransaction(async () => {\n    // 1. Decrement stock atomically\n    for (const item of items) {\n      const product = await Product.findOneAndUpdate(\n        { _id: item.productId, stock: { $gte: item.quantity } },\n        { $inc: { stock: -item.quantity } },\n        { session, new: true }\n      );\n      if (!product) throw new AppError(`Insufficient stock for ${item.title}`, 400);\n    }\n    // 2. Create order document & trigger email job\n    const order = await Order.create([{ user: userId, items }], { session });\n    await emailQueue.add(\"order-confirmation\", { orderId: order[0]._id });\n    return order[0];\n  });\n};"
    },
    {
      "id": "M29-06",
      "number": "06",
      "title": "Project 06: Final Project (Production REST API)",
      "khmerTitle": "គម្រោងទី ៦ ៖ Final Production REST API Capstone",
      "type": "architecture",
      "codeLanguage": "javascript",
      "summary": "The capstone project integrates every concept from the entire course into a single production-grade application: Express REST API with authentication, RBAC, MongoDB + Mongoose, Redis caching, BullMQ background jobs, Socket.IO real-time features, file uploads, Swagger docs, Vitest integration tests, Docker containerization with Compose, Nginx reverse proxy, and GitHub Actions CI/CD.",
      "tip": "Before deploying, run through the production checklist: env validation, graceful shutdown handlers, connection pooling, rate limiting, Helmet security headers, structured logging, and health check endpoints.",
      "objective": "Ship a complete, production-grade Node.js API integrating all course technologies end-to-end.",
      "expectedOutcome": "A portfolio-ready, full-featured backend deployed to production with CI/CD automation.",
      "codeSnippet": "// Production startup with graceful shutdown\nimport app from \"./app.js\";\nimport { connectDB } from \"./config/database.js\";\nimport { redis } from \"./config/redis.js\";\nimport { startWorkers, stopWorkers } from \"./queues/index.js\";\n\nconst server = app.listen(process.env.PORT || 5000, async () => {\n  await connectDB();\n  await redis.connect();\n  await startWorkers();\n  console.log(`Server running on port ${process.env.PORT || 5000} [${process.env.NODE_ENV}]`);\n});\n\nconst shutdown = async (signal) => {\n  console.log(`${signal}: shutting down gracefully...`);\n  server.close(async () => {\n    await stopWorkers();\n    await redis.quit();\n    process.exit(0);\n  });\n  setTimeout(() => process.exit(1), 10_000);\n};\n\nprocess.on(\"SIGTERM\", () => shutdown(\"SIGTERM\"));\nprocess.on(\"SIGINT\", () => shutdown(\"SIGINT\"));"
    }
  ]
};
